clause1(hasAttributeValue(attribute101,'36120401'),true).
clause1(hasAttributeName(attribute101,'eClassClassificationClass'),true).
clause1(type(attribute101,attribute),true).
clause1(hasRefSemantic(attribute81,refSemantic51),true).
clause1(hasAttributeName(attribute81,'Product type description'),true).
clause1(type(attribute81,attribute),true).
clause1(hasRoleRequirements(internalElement11,roleRequirements31),true).
clause1(hasInternalElement(internalElement11,internalElement31),true).
clause1(hasInternalElement(internalElement11,internalElement21),true).
clause1(hasAttributeName(internalElement11,'Connection'),true).
clause1(identifier(internalElement11,'acf9f51b-3fbd-4f30-891d-f8daca50ed18'),true).
clause1(type(internalElement11,internalElement),true).
clause1(refBaseRoleClassPath(roleRequirements11,'BaseInterfaceClassLib@AutomationMLBaseRoleClassLib/AutomationMLBaseRole/Port'),true).
clause1(type(roleRequirements11,roleRequirements),true).
clause1(hasSystemUnitClassLib(cAEXFile11,systemUnitClassLib11),true).
clause1(hasInterfaceClassLib(cAEXFile11,interfaceClassLib11),true).
clause1(hasExternalReference(cAEXFile11,externalReference11),true).
clause1(hasAdditionalInfomation(cAEXFile11,additionalInformation21),true).
clause1(hasAdditionalInfomation(cAEXFile11,additionalInformation11),true).
clause1(hasSchemaVersion(cAEXFile11,'2.15'),true).
clause1(hasFileName(cAEXFile11,'seed-Granularity-0.aml'),true).
clause1(type(cAEXFile11,cAEXFile),true).
clause1(hasAttributeValue(attribute21,'27031402'),true).
clause1(hasAttributeName(attribute21,'eClassClassificationClass'),true).
clause1(type(attribute21,attribute),true).
clause1(hasCorrespondingAttributePath(refSemantic51,'0173-1#02-AAO847#002'),true).
clause1(type(refSemantic51,refSemantic),true).
clause1(refBaseClassPath(externalInterface21,'BaseInterfaceClassLib@AutomationMLInterfaceClassLib/AutomationMLBaseInterface/PortConnector'),true).
clause1(hasAttributeName(externalInterface21,'ConnectionPoint'),true).
clause1(identifier(externalInterface21,'c50f79eb-6634-4c7e-a32f-54bdef05cace'),true).
clause1(type(externalInterface21,externalInterface),true).
clause1(hasRefSemantic(attribute151,refSemantic91),true).
clause1(hasAttributeValue(attribute151,'35.0'),true).
clause1(hasAttributeName(attribute151,'maxTransportationWeight'),true).
clause1(type(attribute151,attribute),true).
clause1(hasRoleRequirements(internalElement61,roleRequirements51),true).
clause1(hasExternalInterface(internalElement61,externalInterface41),true).
clause1(hasAttribute(internalElement61,attribute151),true).
clause1(hasAttributeName(internalElement61,'Conveyor4'),true).
clause1(identifier(internalElement61,'819f4954-892a-4a46-9091-b6f75ddd1332'),true).
clause1(type(internalElement61,internalElement),true).
clause1(refBaseRoleClassPath(roleRequirements61,'BaseRoleClassLib@AutomationMLBaseRoleClassLib/AutomationMLBaseRole/Resource'),true).
clause1(type(roleRequirements61,roleRequirements),true).
clause1(hasLastWritingDateTime(additionalInformation21,'2012-02-20 '),true).
clause1(hasWriterID(additionalInformation21,'AutomationML e.V.'),true).
clause1(hasWriterRelease(additionalInformation21,'1.0'),true).
clause1(hasWriterVendorURL(additionalInformation21,'www.AutomationML.org'),true).
clause1(hasWriterName(additionalInformation21,'AutomationML e.V.'),true).
clause1(type(additionalInformation21,additionalInformation),true).
clause1(hasWriterProjectTitle(additionalInformation21,'AutomationML Tutorial Examples'),true).
clause1(hasWriterVersion(additionalInformation21,'1.0'),true).
clause1(hasWriterProjectID(additionalInformation21,'AutomationML Tutorial Examples '),true).
clause1(hasWriterVendor(additionalInformation21,'AutomationML e.V.'),true).
clause1(hasRefSemantic(attribute71,refSemantic41),true).
clause1(hasAttributeName(attribute71,'Manufacturer name'),true).
clause1(type(attribute71,attribute),true).
clause1(hasInternalElement(systemUnitClass11,internalElement41),true).
clause1(hasInternalElement(systemUnitClass11,internalElement11),true).
clause1(hasAttribute(systemUnitClass11,attribute111),true).
clause1(hasAttribute(systemUnitClass11,attribute101),true).
clause1(hasAttribute(systemUnitClass11,attribute91),true).
clause1(hasAttributeName(systemUnitClass11,'BASIC_36-12-04-01 Conveyor'),true).
clause1(type(systemUnitClass11,systemUnitClass),true).
clause1(hasSystemUnitClass(systemUnitClassLib11,systemUnitClass11),true).
clause1(hasVersion(systemUnitClassLib11,'1.0'),true).
clause1(hasAttributeName(systemUnitClassLib11,'Conveyors'),true).
clause1(type(systemUnitClassLib11,systemUnitClassLib),true).
clause1(hasAttributeValue(attribute11,'9.0'),true).
clause1(hasAttributeName(attribute11,'eClassVersion'),true).
clause1(type(attribute11,attribute),true).
clause1(hasCorrespondingAttributePath(refSemantic41,'ECLASS:0173-1#02-AAO677#001'),true).
clause1(type(refSemantic41,refSemantic),true).
clause1(refBaseClassPath(externalInterface11,'BaseInterfaceClassLib@AutomationMLInterfaceClassLib/AutomationMLBaseInterface/PortConnector'),true).
clause1(hasAttributeName(externalInterface11,'ConnectionPoint'),true).
clause1(identifier(externalInterface11,'51e272d6-0252-4ebd-b865-2ca7a202a68e'),true).
clause1(type(externalInterface11,externalInterface),true).
clause1(hasRefSemantic(attribute141,refSemantic81),true).
clause1(hasAttributeValue(attribute141,'1.5'),true).
clause1(hasAttributeName(attribute141,'Min. speed of the drive'),true).
clause1(type(attribute141,attribute),true).
clause1(hasRoleRequirements(internalElement51,roleRequirements41),true).
clause1(hasExternalInterface(internalElement51,externalInterface31),true).
clause1(hasAttribute(internalElement51,attribute141),true).
clause1(hasAttributeName(internalElement51,'Conveyor3'),true).
clause1(identifier(internalElement51,'23e7138b-f28f-4f45-8c0b-ee7e0de7c08f'),true).
clause1(type(internalElement51,internalElement),true).
clause1(refBaseRoleClassPath(roleRequirements51,'BaseInterfaceClassLib@AutomationMLBaseRoleClassLib/AutomationMLBaseRole/Port'),true).
clause1(type(roleRequirements51,roleRequirements),true).
clause1(hasAutomationMLVersion(additionalInformation11,'2.0'),true).
clause1(type(additionalInformation11,additionalInformation),true).
clause1(hasRefSemantic(attribute61,refSemantic31),true).
clause1(hasAttributeName(attribute61,'Power loss, static, current-independent [Pls]'),true).
clause1(type(attribute61,attribute),true).
clause1(hasCorrespondingAttributePath(refSemantic91,'ECLASS:0173-1#02-AAI721#002'),true).
clause1(type(refSemantic91,refSemantic),true).
clause1(hasInterfaceClass(interfaceClassLib11,interfaceClass11),true).
clause1(hasAttributeName(interfaceClassLib11,'DistributionTransformer'),true).
clause1(type(interfaceClassLib11,interfaceClassLib),true).
clause1(hasCorrespondingAttributePath(refSemantic31,'0173-1#02-BAA303#005'),true).
clause1(type(refSemantic31,refSemantic),true).
clause1(hasRefSemantic(attribute131,refSemantic71),true).
clause1(hasAttributeValue(attribute131,'2'),true).
clause1(hasAttributeName(attribute131,' Max.load capacity'),true).
clause1(type(attribute131,attribute),true).
clause1(hasRoleRequirements(internalElement41,roleRequirements61),true).
clause1(hasInternalElement(internalElement41,internalElement61),true).
clause1(hasInternalElement(internalElement41,internalElement51),true).
clause1(hasAttributeName(internalElement41,'Station'),true).
clause1(identifier(internalElement41,'acf9f51b-3fbd-4f30-891d-f8daca50ed17'),true).
clause1(type(internalElement41,internalElement),true).
clause1(refBaseRoleClassPath(roleRequirements41,'BaseInterfaceClassLib@AutomationMLBaseRoleClassLib/AutomationMLBaseRole/Port'),true).
clause1(type(roleRequirements41,roleRequirements),true).
clause1(hasRefSemantic(attribute51,refSemantic21),true).
clause1(hasAttributeName(attribute51,'GTIN'),true).
clause1(type(attribute51,attribute),true).
clause1(hasCorrespondingAttributePath(refSemantic81,'ECLASS:0173-1#02-BAH608#004'),true).
clause1(type(refSemantic81,refSemantic),true).
clause1(hasCorrespondingAttributePath(refSemantic21,'ECLASS:0173-1#02-AAO663#002'),true).
clause1(type(refSemantic21,refSemantic),true).
clause1(hasRefSemantic(attribute121,refSemantic61),true).
clause1(hasAttributeValue(attribute121,'1.5'),true).
clause1(hasAttributeName(attribute121,'maxConveyingSpeed'),true).
clause1(type(attribute121,attribute),true).
clause1(hasRoleRequirements(internalElement31,roleRequirements21),true).
clause1(hasExternalInterface(internalElement31,externalInterface21),true).
clause1(hasAttribute(internalElement31,attribute131),true).
clause1(hasAttributeName(internalElement31,'Conveyor2'),true).
clause1(identifier(internalElement31,'11b59bf6-44f6-4650-939f-d8e2551912a7'),true).
clause1(type(internalElement31,internalElement),true).
clause1(refBaseRoleClassPath(roleRequirements31,'BaseRoleClassLib@AutomationMLBaseRoleClassLib/AutomationMLBaseRole/Resource'),true).
clause1(type(roleRequirements31,roleRequirements),true).
clause1(hasRefSemantic(attribute41,refSemantic11),true).
clause1(hasAttributeName(attribute41,'additional link address'),true).
clause1(type(attribute41,attribute),true).
clause1(hasCorrespondingAttributePath(refSemantic71,'ECLASS:0173-1#02-BAF316#002'),true).
clause1(type(refSemantic71,refSemantic),true).
clause1(refBaseClassPath(externalInterface41,'BaseInterfaceClassLib@AutomationMLInterfaceClassLib/AutomationMLBaseInterface/PortConnector'),true).
clause1(hasAttributeName(externalInterface41,'ConnectionPoint'),true).
clause1(identifier(externalInterface41,'c45eca55-521a-492e-b094-472124d1ae65'),true).
clause1(type(externalInterface41,externalInterface),true).
clause1(hasAttribute(interfaceClass11,attribute61),true).
clause1(hasAttributeName(interfaceClass11,'BASIC_27-03-14-02 Single-phase distribution transformer (oil-cooled)'),true).
clause1(hasAttribute(interfaceClass11,attribute41),true).
clause1(hasAttribute(interfaceClass11,attribute11),true).
clause1(hasAttribute(interfaceClass11,attribute71),true).
clause1(type(interfaceClass11,interfaceClass),true).
clause1(hasAttribute(interfaceClass11,attribute21),true).
clause1(hasAttribute(interfaceClass11,attribute81),true).
clause1(hasAttribute(interfaceClass11,attribute51),true).
clause1(hasAttribute(interfaceClass11,attribute31),true).
clause1(hasCorrespondingAttributePath(refSemantic11,'ECLASS:0173-1#02-AAQ326#001'),true).
clause1(type(refSemantic11,refSemantic),true).
clause1(refBaseClassPath(externalReference11,'Libs/InterfaceClass Libraries/AutomationMLInterfaceClassLib.aml'),true).
clause1(externalReferenceAlias(externalReference11,'BaseInterfaceClassLib'),true).
clause1(type(externalReference11,externalReference),true).
clause1(hasAttributeValue(attribute111,'0173-1---BASIC_1_1#01-AKL503#010'),true).
clause1(hasAttributeName(attribute111,'eClassIRDI'),true).
clause1(type(attribute111,attribute),true).
clause1(hasAttributeValue(attribute91,'9.0'),true).
clause1(hasAttributeName(attribute91,'eClassVersion'),true).
clause1(type(attribute91,attribute),true).
clause1(hasRoleRequirements(internalElement21,roleRequirements11),true).
clause1(hasExternalInterface(internalElement21,externalInterface11),true).
clause1(hasAttribute(internalElement21,attribute121),true).
clause1(hasAttributeName(internalElement21,'Conveyor1'),true).
clause1(identifier(internalElement21,'45e20f8e-7351-4af9-bdfd-3c019674de55'),true).
clause1(type(internalElement21,internalElement),true).
clause1(refBaseRoleClassPath(roleRequirements21,'BaseInterfaceClassLib@AutomationMLBaseRoleClassLib/AutomationMLBaseRole/Port'),true).
clause1(type(roleRequirements21,roleRequirements),true).
clause1(hasAttributeValue(attribute31,'0173-1---BASIC_1_1#02-ACO096#009'),true).
clause1(hasAttributeName(attribute31,'eClassIRDI'),true).
clause1(type(attribute31,attribute),true).
clause1(hasCorrespondingAttributePath(refSemantic61,'ECLASS:0173-1#02-BAF685#003'),true).
clause1(type(refSemantic61,refSemantic),true).
clause1(refBaseClassPath(externalInterface31,'BaseInterfaceClassLib@AutomationMLInterfaceClassLib/AutomationMLBaseInterface/PortConnector'),true).
clause1(hasAttributeName(externalInterface31,'ConnectionPoint'),true).
clause1(identifier(externalInterface31,'b0e2d6a0-2d8b-44c8-921b-bf4b43de906e'),true).
clause1(type(externalInterface31,externalInterface),true).
clause1(hasSystemUnitClass(systemUnitClassLib12,systemUnitClass12),true).
clause1(hasVersion(systemUnitClassLib12,'1.0'),true).
clause1(hasAttributeName(systemUnitClassLib12,'Conveyors'),true).
clause1(type(systemUnitClassLib12,systemUnitClassLib),true).
clause1(hasSystemUnitClassLib(cAEXFile12,systemUnitClassLib12),true).
clause1(hasInterfaceClassLib(cAEXFile12,interfaceClassLib12),true).
clause1(hasExternalReference(cAEXFile12,externalReference12),true).
clause1(hasAdditionalInfomation(cAEXFile12,additionalInformation22),true).
clause1(hasAdditionalInfomation(cAEXFile12,additionalInformation12),true).
clause1(hasSchemaVersion(cAEXFile12,'2.15'),true).
clause1(hasFileName(cAEXFile12,'seed-Granularity-1.aml'),true).
clause1(type(cAEXFile12,cAEXFile),true).
clause1(hasRefSemantic(attribute42,refSemantic12),true).
clause1(hasAttributeName(attribute42,'GTIN'),true).
clause1(type(attribute42,attribute),true).
clause1(hasAttribute(interfaceClass12,attribute52),true).
clause1(hasAttribute(interfaceClass12,attribute42),true).
clause1(hasAttribute(interfaceClass12,attribute32),true).
clause1(hasAttribute(interfaceClass12,attribute22),true).
clause1(hasAttribute(interfaceClass12,attribute12),true).
clause1(hasAttributeName(interfaceClass12,'BASIC_27-03-14-02 Single-phase distribution transformer (oil-cooled)'),true).
clause1(type(interfaceClass12,interfaceClass),true).
clause1(hasRoleRequirements(internalElement22,roleRequirements22),true).
clause1(hasExternalInterface(internalElement22,externalInterface22),true).
clause1(hasAttribute(internalElement22,attribute102),true).
clause1(hasAttributeName(internalElement22,'Conveyor2'),true).
clause1(identifier(internalElement22,'11b59bf6-44f6-4650-939f-d8e2551912a7'),true).
clause1(type(internalElement22,internalElement),true).
clause1(refBaseClassPath(externalReference12,'Libs/InterfaceClass Libraries/AutomationMLInterfaceClassLib.aml'),true).
clause1(externalReferenceAlias(externalReference12,'BaseInterfaceClassLib'),true).
clause1(type(externalReference12,externalReference),true).
clause1(hasCorrespondingAttributePath(refSemantic32,'ECLASS:0173-1#02-BAF685#003'),true).
clause1(type(refSemantic32,refSemantic),true).
clause1(refBaseClassPath(externalInterface42,'BaseInterfaceClassLib@AutomationMLInterfaceClassLib/AutomationMLBaseInterface/PortConnector'),true).
clause1(hasAttributeName(externalInterface42,'ConnectionPoint'),true).
clause1(identifier(externalInterface42,'c45eca55-521a-492e-b094-472124d1ae65'),true).
clause1(type(externalInterface42,externalInterface),true).
clause1(hasAttributeValue(attribute32,'0173-1---BASIC_1_1#02-ACO096#009'),true).
clause1(hasAttributeName(attribute32,'eClassIRDI'),true).
clause1(type(attribute32,attribute),true).
clause1(hasRefSemantic(attribute92,refSemantic32),true).
clause1(hasAttributeValue(attribute92,'1.5'),true).
clause1(hasAttributeName(attribute92,'maxConveyingSpeed'),true).
clause1(type(attribute92,attribute),true).
clause1(hasRoleRequirements(internalElement12,roleRequirements12),true).
clause1(hasExternalInterface(internalElement12,externalInterface12),true).
clause1(hasAttribute(internalElement12,attribute92),true).
clause1(hasAttributeName(internalElement12,'Conveyor1'),true).
clause1(identifier(internalElement12,'45e20f8e-7351-4af9-bdfd-3c019674de55'),true).
clause1(type(internalElement12,internalElement),true).
clause1(hasCorrespondingAttributePath(refSemantic22,'ECLASS:0173-1#02-AAO677#001'),true).
clause1(type(refSemantic22,refSemantic),true).
clause1(refBaseClassPath(externalInterface32,'BaseInterfaceClassLib@AutomationMLInterfaceClassLib/AutomationMLBaseInterface/PortConnector'),true).
clause1(hasAttributeName(externalInterface32,'ConnectionPoint'),true).
clause1(identifier(externalInterface32,'b0e2d6a0-2d8b-44c8-921b-bf4b43de906e'),true).
clause1(type(externalInterface32,externalInterface),true).
clause1(hasInternalElement(systemUnitClass12,internalElement42),true).
clause1(hasInternalElement(systemUnitClass12,internalElement32),true).
clause1(hasInternalElement(systemUnitClass12,internalElement22),true).
clause1(hasInternalElement(systemUnitClass12,internalElement12),true).
clause1(hasAttribute(systemUnitClass12,attribute82),true).
clause1(hasAttribute(systemUnitClass12,attribute72),true).
clause1(hasAttribute(systemUnitClass12,attribute62),true).
clause1(hasAttributeName(systemUnitClass12,'BASIC_36-12-04-01 Conveyor'),true).
clause1(type(systemUnitClass12,systemUnitClass),true).
clause1(hasAttributeValue(attribute22,'27031402'),true).
clause1(hasAttributeName(attribute22,'eClassClassificationClass'),true).
clause1(type(attribute22,attribute),true).
clause1(hasAttributeValue(attribute82,'0173-1---BASIC_1_1#01-AKL503#010'),true).
clause1(hasAttributeName(attribute82,'eClassIRDI'),true).
clause1(type(attribute82,attribute),true).
clause1(hasRefSemantic(attribute122,refSemantic62),true).
clause1(hasAttributeValue(attribute122,'35.0'),true).
clause1(hasAttributeName(attribute122,'maxTransportationWeight'),true).
clause1(type(attribute122,attribute),true).
clause1(hasCorrespondingAttributePath(refSemantic12,'ECLASS:0173-1#02-AAO663#002'),true).
clause1(type(refSemantic12,refSemantic),true).
clause1(refBaseClassPath(externalInterface22,'BaseInterfaceClassLib@AutomationMLInterfaceClassLib/AutomationMLBaseInterface/PortConnector'),true).
clause1(hasAttributeName(externalInterface22,'ConnectionPoint'),true).
clause1(identifier(externalInterface22,'c50f79eb-6634-4c7e-a32f-54bdef05cace'),true).
clause1(type(externalInterface22,externalInterface),true).
clause1(refBaseRoleClassPath(roleRequirements42,'BaseInterfaceClassLib@AutomationMLBaseRoleClassLib/AutomationMLBaseRole/Port'),true).
clause1(type(roleRequirements42,roleRequirements),true).
clause1(hasAttributeValue(attribute12,'9.0'),true).
clause1(hasAttributeName(attribute12,'eClassVersion'),true).
clause1(type(attribute12,attribute),true).
clause1(hasAttributeValue(attribute72,'36120401'),true).
clause1(hasAttributeName(attribute72,'eClassClassificationClass'),true).
clause1(type(attribute72,attribute),true).
clause1(hasRefSemantic(attribute112,refSemantic52),true).
clause1(hasAttributeValue(attribute112,'1.5'),true).
clause1(hasAttributeName(attribute112,'Min. speed of the drive'),true).
clause1(type(attribute112,attribute),true).
clause1(hasCorrespondingAttributePath(refSemantic62,'ECLASS:0173-1#02-AAI721#002'),true).
clause1(type(refSemantic62,refSemantic),true).
clause1(refBaseClassPath(externalInterface12,'BaseInterfaceClassLib@AutomationMLInterfaceClassLib/AutomationMLBaseInterface/PortConnector'),true).
clause1(hasAttributeName(externalInterface12,'ConnectionPoint'),true).
clause1(identifier(externalInterface12,'51e272d6-0252-4ebd-b865-2ca7a202a68e'),true).
clause1(type(externalInterface12,externalInterface),true).
clause1(hasWriterProjectTitle(additionalInformation22,'AutomationML Tutorial Examples'),true).
clause1(hasWriterRelease(additionalInformation22,'1.0'),true).
clause1(hasWriterVendorURL(additionalInformation22,'www.AutomationML.org'),true).
clause1(hasWriterID(additionalInformation22,'AutomationML e.V.'),true).
clause1(type(additionalInformation22,additionalInformation),true).
clause1(refBaseRoleClassPath(roleRequirements32,'BaseInterfaceClassLib@AutomationMLBaseRoleClassLib/AutomationMLBaseRole/Port'),true).
clause1(type(roleRequirements32,roleRequirements),true).
clause1(hasAttributeValue(attribute62,'9.0'),true).
clause1(hasAttributeName(attribute62,'eClassVersion'),true).
clause1(type(attribute62,attribute),true).
clause1(hasRefSemantic(attribute102,refSemantic42),true).
clause1(hasAttributeValue(attribute102,'2'),true).
clause1(hasAttributeName(attribute102,' Max.load capacity'),true).
clause1(type(attribute102,attribute),true).
clause1(hasRoleRequirements(internalElement42,roleRequirements42),true).
clause1(hasExternalInterface(internalElement42,externalInterface42),true).
clause1(hasAttribute(internalElement42,attribute122),true).
clause1(hasAttributeName(internalElement42,'Conveyor4'),true).
clause1(identifier(internalElement42,'819f4954-892a-4a46-9091-b6f75ddd1332'),true).
clause1(type(internalElement42,internalElement),true).
clause1(hasCorrespondingAttributePath(refSemantic52,'ECLASS:0173-1#02-BAH608#004'),true).
clause1(type(refSemantic52,refSemantic),true).
clause1(hasInterfaceClass(interfaceClassLib12,interfaceClass12),true).
clause1(hasAttributeName(interfaceClassLib12,'DistributionTransformer'),true).
clause1(type(interfaceClassLib12,interfaceClassLib),true).
clause1(hasAutomationMLVersion(additionalInformation12,'2.0'),true).
clause1(type(additionalInformation12,additionalInformation),true).
clause1(refBaseRoleClassPath(roleRequirements22,'BaseInterfaceClassLib@AutomationMLBaseRoleClassLib/AutomationMLBaseRole/Port'),true).
clause1(type(roleRequirements22,roleRequirements),true).
clause1(hasRefSemantic(attribute52,refSemantic22),true).
clause1(hasAttributeName(attribute52,'Manufacturer name'),true).
clause1(type(attribute52,attribute),true).
clause1(hasRoleRequirements(internalElement32,roleRequirements32),true).
clause1(hasExternalInterface(internalElement32,externalInterface32),true).
clause1(hasAttribute(internalElement32,attribute112),true).
clause1(hasAttributeName(internalElement32,'Conveyor3'),true).
clause1(identifier(internalElement32,'23e7138b-f28f-4f45-8c0b-ee7e0de7c08f'),true).
clause1(type(internalElement32,internalElement),true).
clause1(hasCorrespondingAttributePath(refSemantic42,'ECLASS:0173-1#02-BAF316#002'),true).
clause1(type(refSemantic42,refSemantic),true).
clause1(refBaseRoleClassPath(roleRequirements12,'BaseInterfaceClassLib@AutomationMLBaseRoleClassLib/AutomationMLBaseRole/Port'),true).
clause1(type(roleRequirements12,roleRequirements),true).

