clause1(hasSystemUnitClass(systemUnitClassLib11,systemUnitClass11),true).
clause1(hasVersion(systemUnitClassLib11,'1.0'),true).
clause1(hasAttributeName(systemUnitClassLib11,'LibOfCommonTools'),true).
clause1(type(systemUnitClassLib11,systemUnitClassLib),true).
clause1(hasRoleClassLib(cAEXFile11,roleClassLib11),true).
clause1(hasExternalReference(cAEXFile11,externalReference11),true).
clause1(hasAdditionalInfomation(cAEXFile11,additionalInformation21),true).
clause1(hasInstanceHierarchy(cAEXFile11,instanceHierarchy11),true).
clause1(type(cAEXFile11,cAEXFile),true).
clause1(hasAdditionalInfomation(cAEXFile11,additionalInformation11),true).
clause1(hasSchemaVersion(cAEXFile11,'2.15'),true).
clause1(hasInterfaceClassLib(cAEXFile11,interfaceClassLib11),true).
clause1(hasSystemUnitClassLib(cAEXFile11,systemUnitClassLib11),true).
clause1(hasFileName(cAEXFile11,'Topology.aml'),true).
clause1(hasExternalReference(cAEXFile11,externalReference21),true).
clause1(refBaseClassPath(interfaceClass11,'BaseInterfaceClassLib@AutomationMLInterfaceClassLib/AutomationMLBaseInterface'),true).
clause1(hasAttributeName(interfaceClass11,'Energy'),true).
clause1(type(interfaceClass11,interfaceClass),true).
clause1(refBaseRoleClassPath(roleRequirements11,'ManufacturingRoleClasses/Tool'),true).
clause1(type(roleRequirements11,roleRequirements),true).
clause1(hasRoleRequirements(internalElement21,roleRequirements21),true).
clause1(hasSupportedRoleClass(internalElement21,supportedRoleClass21),true).
clause1(hasExternalInterface(internalElement21,externalInterface31),true).
clause1(hasExternalInterface(internalElement21,externalInterface21),true).
clause1(refBaseSystemUnitPath(internalElement21,'LibOfCommonTools/ElectricScrewdriver'),true).
clause1(hasAttributeName(internalElement21,'secondScrewdriver'),true).
clause1(identifier(internalElement21,'{19dcf818-4716-4fc1-a85f-28e1938c4c3a}'),true).
clause1(type(internalElement21,internalElement),true).
clause1(refBaseClassPath(externalReference11,'Libs/RoleClass Libraries/AutomationMLBaseRoleClassLib.aml'),true).
clause1(externalReferenceAlias(externalReference11,'BaseRoleClassLib'),true).
clause1(type(externalReference11,externalReference),true).
clause1(refBaseClassPath(externalInterface41,'MyInterfaces/Energy'),true).
clause1(hasAttributeName(externalInterface41,'EnergySupply'),true).
clause1(identifier(externalInterface41,'dd0e0dfe-10f8-4068-845b-9c29699ac79b'),true).
clause1(type(externalInterface41,externalInterface),true).
clause1(hasRoleRequirements(internalElement11,roleRequirements11),true).
clause1(hasSupportedRoleClass(internalElement11,supportedRoleClass11),true).
clause1(hasExternalInterface(internalElement11,externalInterface11),true).
clause1(hasAttribute(internalElement11,attribute11),true).
clause1(refBaseSystemUnitPath(internalElement11,'LibOfCommonTools/ElectricScrewdriver'),true).
clause1(hasAttributeName(internalElement11,'firstScrewdriver'),true).
clause1(identifier(internalElement11,'{788eb291-f103-4fdc-aba0-4893b599f556}'),true).
clause1(type(internalElement11,internalElement),true).
clause1(hasAttribute(externalInterface31,attribute21),true).
clause1(refBaseClassPath(externalInterface31,'BaseInterfaceClassLib@AutomationMLInterfaceClassLib/AutomationMLBaseInterface/ExternalDataConnector/PLCopenXMLInterface'),true).
clause1(hasAttributeName(externalInterface31,'PLCopenXMLInterface_instance_1'),true).
clause1(identifier(externalInterface31,'0e2014a2-fb61-44c8-8025-7e3161dfece4'),true).
clause1(type(externalInterface31,externalInterface),true).
clause1(hasSupportedRoleClass(systemUnitClass11,supportedRoleClass31),true).
clause1(hasExternalInterface(systemUnitClass11,externalInterface41),true).
clause1(hasAttributeName(systemUnitClass11,'ElectricScrewdriver'),true).
clause1(type(systemUnitClass11,systemUnitClass),true).
clause1(hasAttributeValue(attribute21,'file:///OPCopen.xml#ID1
'),true).
clause1(hasAttributeName(attribute21,'refURI'),true).
clause1(hasDataType(attribute21,'xs:anyURI'),true).
clause1(type(attribute21,attribute),true).
clause1(refBaseClassPath(externalInterface21,'MyInterfaces/Energy'),true).
clause1(hasAttributeName(externalInterface21,'EnergySupply'),true).
clause1(identifier(externalInterface21,'50e10905-ac18-413c-afab-ad8ed1569fff'),true).
clause1(type(externalInterface21,externalInterface),true).
clause1(hasInternalElement(instanceHierarchy11,internalElement21),true).
clause1(hasInternalElement(instanceHierarchy11,internalElement11),true).
clause1(hasAttributeName(instanceHierarchy11,'ManufacturingSystem'),true).
clause1(type(instanceHierarchy11,instanceHierarchy),true).
clause1(hasAttributeName(attribute11,'New Attribute'),true).
clause1(type(attribute11,attribute),true).
clause1(refRoleClassPath(supportedRoleClass31,'ManufacturingRoleClasses/Tool'),true).
clause1(type(supportedRoleClass31,supportedRoleClass),true).
clause1(refBaseClassPath(externalInterface11,'MyInterfaces/Energy'),true).
clause1(hasAttributeName(externalInterface11,'EnergySupply'),true).
clause1(identifier(externalInterface11,'{5f535d4c-dd46-4c1c-898c-4e58419048b6}'),true).
clause1(type(externalInterface11,externalInterface),true).
clause1(hasWriterID(additionalInformation21,'AutomationML e.V.'),true).
clause1(hasWriterRelease(additionalInformation21,'1.0'),true).
clause1(hasWriterProjectID(additionalInformation21,'AutomationML Tutorial Examples
			'),true).
clause1(hasWriterVendorURL(additionalInformation21,'www.AutomationML.org'),true).
clause1(hasLastWritingDateTime(additionalInformation21,'2012-02-20
			'),true).
clause1(hasWriterName(additionalInformation21,'AutomationML e.V.'),true).
clause1(type(additionalInformation21,additionalInformation),true).
clause1(hasWriterProjectTitle(additionalInformation21,'AutomationML Tutorial Examples'),true).
clause1(hasWriterVersion(additionalInformation21,'1.0'),true).
clause1(hasWriterVendor(additionalInformation21,'AutomationML e.V.'),true).
clause1(refBaseClassPath(roleClass11,'BaseRoleClassLib@AutomationMLBaseRoleClassLib/AutomationMLBaseRole'),true).
clause1(hasAttributeName(roleClass11,'Tool'),true).
clause1(type(roleClass11,roleClass),true).
clause1(refRoleClassPath(supportedRoleClass21,'ManufacturingRoleClasses/Tool'),true).
clause1(type(supportedRoleClass21,supportedRoleClass),true).
clause1(hasInterfaceClass(interfaceClassLib11,interfaceClass11),true).
clause1(hasAttributeName(interfaceClassLib11,'MyInterfaces'),true).
clause1(type(interfaceClassLib11,interfaceClassLib),true).
clause1(hasAutomationMLVersion(additionalInformation11,'2.0'),true).
clause1(type(additionalInformation11,additionalInformation),true).
clause1(refBaseRoleClassPath(roleRequirements21,'ManufacturingRoleClasses/Tool'),true).
clause1(type(roleRequirements21,roleRequirements),true).
clause1(refRoleClassPath(supportedRoleClass11,'ManufacturingRoleClasses/Tool'),true).
clause1(type(supportedRoleClass11,supportedRoleClass),true).
clause1(refBaseClassPath(externalReference21,'Libs/InterfaceClass Libraries/AutomationMLInterfaceClassLib.aml'),true).
clause1(externalReferenceAlias(externalReference21,'BaseInterfaceClassLib'),true).
clause1(type(externalReference21,externalReference),true).
clause1(hasRoleClass(roleClassLib11,roleClass11),true).
clause1(hasVersion(roleClassLib11,'1.0'),true).
clause1(hasAttributeName(roleClassLib11,'ManufacturingRoleClasses'),true).
clause1(type(roleClassLib11,roleClassLib),true).
clause1(type(localizedText642,localizedText),true).
clause1(reference(listOfReferences302,reference962),true).
clause1(type(listOfReferences302,listOfReferences),true).
clause1(reference(listOfReferences22,reference72),true).
clause1(reference(listOfReferences22,reference82),true).
clause1(reference(listOfReferences22,reference92),true).
clause1(reference(listOfReferences22,reference102),true).
clause1(reference(listOfReferences22,reference112),true).
clause1(reference(listOfReferences22,reference122),true).
clause1(type(listOfReferences22,listOfReferences),true).
clause1(hasParentNodeId(uAObject122,'ns=2;i=40'),true).
clause1(hasNodeId(uAObject122,'ns=2;i=45'),true).
clause1(hasBrowseName(uAObject122,'InstanceHierarchies'),true).
clause1(references(uAObject122,listOfReferences122),true).
clause1(displayName(uAObject122,localizedText232),true).
clause1(type(uAObject122,uAObject),true).
clause1(type(anon_1192,anon_1),true).
clause1(hasTextContent(localizedText342,'ID'),true).
clause1(type(localizedText342,localizedText),true).
clause1(hasTextContent(reference732,'ns=2;i=9'),true).
clause1(hasReferenceType(reference732,'HasComponent'),true).
clause1(type(reference732,reference),true).
clause1(hasTextContent(reference1112,'PropertyType'),true).
clause1(hasReferenceType(reference1112,'HasTypeDefinition'),true).
clause1(type(reference1112,reference),true).
clause1(hasTextContent(nodeIdAlias352,'i=48'),true).
clause1(hasAlias(nodeIdAlias352,'HasNotifier'),true).
clause1(type(nodeIdAlias352,nodeIdAlias),true).
clause1(type(anon_172,anon_1),true).
clause1(hasParentNodeId(uAVariable162,'ns=2;i=23'),true).
clause1(hasNodeId(uAVariable162,'ns=2;i=24'),true).
clause1(hasDataType(uAVariable162,'String'),true).
clause1(hasBrowseName(uAVariable162,'ID'),true).
clause1(value(uAVariable162,anon_1162),true).
clause1(references(uAVariable162,listOfReferences312),true).
clause1(displayName(uAVariable162,localizedText432),true).
clause1(type(uAVariable162,uAVariable),true).
clause1(hasTextContent(reference432,'ns=2;i=12'),true).
clause1(hasReferenceType(reference432,'HasComponent'),true).
clause1(hasIsForward(reference432,'false'),true).
clause1(type(reference432,reference),true).
clause1(type(anon_1202,anon_1),true).
clause1(hasTextContent(reference132,'ns=2;i=7'),true).
clause1(hasReferenceType(reference132,'HasProperty'),true).
clause1(type(reference132,reference),true).
clause1(reference(listOfReferences422,reference1102),true).
clause1(type(listOfReferences422,listOfReferences),true).
clause1(hasParentNodeId(uAObject92,'ns=2;i=15'),true).
clause1(hasNodeId(uAObject92,'ns=2;i=26'),true).
clause1(hasBrowseName(uAObject92,'PLCopenXMLInterface_instance_1'),true).
clause1(references(uAObject92,listOfReferences92),true).
clause1(displayName(uAObject92,localizedText172),true).
clause1(description(uAObject92,localizedText182),true).
clause1(type(uAObject92,uAObject),true).
clause1(reference(listOfReferences122,reference682),true).
clause1(reference(listOfReferences122,reference692),true).
clause1(reference(listOfReferences122,reference702),true).
clause1(type(listOfReferences122,listOfReferences),true).
clause1(hasTextContent(localizedText462,'AdditionalInformation'),true).
clause1(type(localizedText462,localizedText),true).
clause1(hasTextContent(localizedText12,'ManufacturingSystem'),true).
clause1(type(localizedText12,localizedText),true).
clause1(hasTextContent(reference852,'PropertyType'),true).
clause1(hasReferenceType(reference852,'HasTypeDefinition'),true).
clause1(type(reference852,reference),true).
clause1(hasTextContent(reference1232,'ns=2;i=33'),true).
clause1(hasReferenceType(reference1232,'ns=1;i=4001'),true).
clause1(type(reference1232,reference),true).
clause1(hasTextContent(nodeIdAlias22,'i=2'),true).
clause1(hasAlias(nodeIdAlias22,'SByte'),true).
clause1(type(nodeIdAlias22,nodeIdAlias),true).
clause1(type(localizedText162,localizedText),true).
clause1(hasParentNodeId(uAVariable282,'ns=2;i=40'),true).
clause1(hasNodeId(uAVariable282,'ns=2;i=42'),true).
clause1(hasDataType(uAVariable282,'String'),true).
clause1(hasBrowseName(uAVariable282,'SchemaVersion'),true).
clause1(value(uAVariable282,anon_1282),true).
clause1(references(uAVariable282,listOfReferences432),true).
clause1(displayName(uAVariable282,localizedText562),true).
clause1(type(uAVariable282,uAVariable),true).
clause1(hasTextContent(reference552,'ns=2;i=39'),true).
clause1(hasReferenceType(reference552,'HasProperty'),true).
clause1(type(reference552,reference),true).
clause1(hasTextContent(nodeIdAlias172,'i=17'),true).
clause1(hasAlias(nodeIdAlias172,'NodeId'),true).
clause1(type(nodeIdAlias172,nodeIdAlias),true).
clause1(hasTextContent(reference252,'ns=2;i=13'),true).
clause1(hasReferenceType(reference252,'HasProperty'),true).
clause1(type(reference252,reference),true).
clause1(hasTextContent(localizedText582,'BaseInterfaceClassLib'),true).
clause1(type(localizedText582,localizedText),true).
clause1(reference(listOfReferences242,reference882),true).
clause1(type(listOfReferences242,listOfReferences),true).
clause1(hasTextContent(reference972,'PropertyType'),true).
clause1(hasReferenceType(reference972,'HasTypeDefinition'),true).
clause1(type(reference972,reference),true).
clause1(hasTextContent(localizedText282,'Version'),true).
clause1(type(localizedText282,localizedText),true).
clause1(hasNodeId(uAObjectType32,'ns=2;i=35'),true).
clause1(hasBrowseName(uAObjectType32,'ElectricScrewdriver'),true).
clause1(references(uAObjectType32,listOfReferences482),true).
clause1(displayName(uAObjectType32,localizedText632),true).
clause1(description(uAObjectType32,localizedText642),true).
clause1(type(uAObjectType32,uAObjectType),true).
clause1(hasTextContent(reference672,'ns=1;i=5001'),true).
clause1(hasReferenceType(reference672,'Organizes'),true).
clause1(hasIsForward(reference672,'false'),true).
clause1(type(reference672,reference),true).
clause1(hasTextContent(reference1052,'PropertyType'),true).
clause1(hasReferenceType(reference1052,'HasTypeDefinition'),true).
clause1(type(reference1052,reference),true).
clause1(hasTextContent(nodeIdAlias292,'i=38'),true).
clause1(hasAlias(nodeIdAlias292,'HasEncoding'),true).
clause1(type(nodeIdAlias292,nodeIdAlias),true).
clause1(hasTextContent(reference372,'ns=2;i=33'),true).
clause1(hasReferenceType(reference372,'ns=1;i=4001'),true).
clause1(type(reference372,reference),true).
clause1(type(anon_1142,anon_1),true).
clause1(reference(listOfReferences362,reference1042),true).
clause1(type(listOfReferences362,listOfReferences),true).
clause1(reference(listOfReferences82,reference452),true).
clause1(reference(listOfReferences82,reference462),true).
clause1(reference(listOfReferences82,reference472),true).
clause1(reference(listOfReferences82,reference482),true).
clause1(type(listOfReferences82,listOfReferences),true).
clause1(hasTextContent(nodeIdAlias302,'i=39'),true).
clause1(hasAlias(nodeIdAlias302,'HasDescription'),true).
clause1(type(nodeIdAlias302,nodeIdAlias),true).
clause1(type(anon_122,anon_1),true).
clause1(hasParentNodeId(uAVariable112,'ns=2;i=15'),true).
clause1(hasNodeId(uAVariable112,'ns=2;i=17'),true).
clause1(hasDataType(uAVariable112,'String'),true).
clause1(hasBrowseName(uAVariable112,'AdditionalInformation'),true).
clause1(value(uAVariable112,anon_1112),true).
clause1(references(uAVariable112,listOfReferences262),true).
clause1(displayName(uAVariable112,localizedText372),true).
clause1(type(uAVariable112,uAVariable),true).
clause1(hasTextContent(reference792,'ns=2;i=3'),true).
clause1(hasReferenceType(reference792,'HasComponent'),true).
clause1(type(reference792,reference),true).
clause1(hasTextContent(reference1172,'ns=2;i=34'),true).
clause1(hasReferenceType(reference1172,'HasProperty'),true).
clause1(type(reference1172,reference),true).
clause1(hasNodeId(uAObject42,'ns=2;i=9'),true).
clause1(hasBrowseName(uAObject42,'LibOfCommonTools'),true).
clause1(references(uAObject42,listOfReferences42),true).
clause1(displayName(uAObject42,localizedText72),true).
clause1(description(uAObject42,localizedText82),true).
clause1(type(uAObject42,uAObject),true).
clause1(hasTextContent(reference492,'ns=2;i=27'),true).
clause1(hasReferenceType(reference492,'HasProperty'),true).
clause1(type(reference492,reference),true).
clause1(type(anon_1262,anon_1),true).
clause1(hasTextContent(reference192,'ns=2;i=10'),true).
clause1(hasReferenceType(reference192,'HasProperty'),true).
clause1(type(reference192,reference),true).
clause1(hasTextContent(localizedText412,'ID'),true).
clause1(type(localizedText412,localizedText),true).
clause1(reference(listOfReferences482,reference1202),true).
clause1(reference(listOfReferences482,reference1212),true).
clause1(reference(listOfReferences482,reference1222),true).
clause1(reference(listOfReferences482,reference1232),true).
clause1(reference(listOfReferences482,reference1242),true).
clause1(type(listOfReferences482,listOfReferences),true).
clause1(hasTextContent(reference802,'PropertyType'),true).
clause1(hasReferenceType(reference802,'HasTypeDefinition'),true).
clause1(type(reference802,reference),true).
clause1(hasParentNodeId(uAVariable62,'ns=2;i=9'),true).
clause1(hasNodeId(uAVariable62,'ns=2;i=10'),true).
clause1(hasDataType(uAVariable62,'String'),true).
clause1(hasBrowseName(uAVariable62,'Version'),true).
clause1(value(uAVariable62,anon_162),true).
clause1(references(uAVariable62,listOfReferences212),true).
clause1(displayName(uAVariable62,localizedText322),true).
clause1(type(uAVariable62,uAVariable),true).
clause1(alias(aliasTable12,nodeIdAlias122),true).
clause1(alias(aliasTable12,nodeIdAlias202),true).
clause1(alias(aliasTable12,nodeIdAlias302),true).
clause1(alias(aliasTable12,nodeIdAlias392),true).
clause1(alias(aliasTable12,nodeIdAlias262),true).
clause1(alias(aliasTable12,nodeIdAlias12),true).
clause1(alias(aliasTable12,nodeIdAlias362),true).
clause1(alias(aliasTable12,nodeIdAlias72),true).
clause1(alias(aliasTable12,nodeIdAlias412),true).
clause1(alias(aliasTable12,nodeIdAlias162),true).
clause1(alias(aliasTable12,nodeIdAlias232),true).
clause1(alias(aliasTable12,nodeIdAlias332),true).
clause1(alias(aliasTable12,nodeIdAlias182),true).
clause1(alias(aliasTable12,nodeIdAlias42),true).
clause1(alias(aliasTable12,nodeIdAlias312),true).
clause1(alias(aliasTable12,nodeIdAlias132),true).
clause1(alias(aliasTable12,nodeIdAlias102),true).
clause1(alias(aliasTable12,nodeIdAlias22),true).
clause1(alias(aliasTable12,nodeIdAlias272),true).
clause1(alias(aliasTable12,nodeIdAlias372),true).
clause1(alias(aliasTable12,nodeIdAlias242),true).
clause1(alias(aliasTable12,nodeIdAlias342),true).
clause1(alias(aliasTable12,nodeIdAlias82),true).
clause1(alias(aliasTable12,nodeIdAlias52),true).
clause1(alias(aliasTable12,nodeIdAlias172),true).
clause1(alias(aliasTable12,nodeIdAlias192),true).
clause1(alias(aliasTable12,nodeIdAlias142),true).
clause1(alias(aliasTable12,nodeIdAlias212),true).
clause1(alias(aliasTable12,nodeIdAlias282),true).
clause1(alias(aliasTable12,nodeIdAlias382),true).
clause1(alias(aliasTable12,nodeIdAlias112),true).
clause1(alias(aliasTable12,nodeIdAlias92),true).
clause1(type(aliasTable12,aliasTable),true).
clause1(alias(aliasTable12,nodeIdAlias292),true).
clause1(alias(aliasTable12,nodeIdAlias252),true).
clause1(alias(aliasTable12,nodeIdAlias352),true).
clause1(alias(aliasTable12,nodeIdAlias222),true).
clause1(alias(aliasTable12,nodeIdAlias322),true).
clause1(alias(aliasTable12,nodeIdAlias62),true).
clause1(alias(aliasTable12,nodeIdAlias402),true).
clause1(alias(aliasTable12,nodeIdAlias32),true).
clause1(alias(aliasTable12,nodeIdAlias152),true).
clause1(hasTextContent(localizedText112,'secondScrewdriver'),true).
clause1(type(localizedText112,localizedText),true).
clause1(hasTextContent(localizedText72,'LibOfCommonTools'),true).
clause1(type(localizedText72,localizedText),true).
clause1(reference(listOfReferences182,reference822),true).
clause1(type(listOfReferences182,listOfReferences),true).
clause1(hasParentNodeId(uAVariable232,'ns=2;i=33'),true).
clause1(hasNodeId(uAVariable232,'ns=2;i=34'),true).
clause1(hasDataType(uAVariable232,'String'),true).
clause1(hasBrowseName(uAVariable232,'AdditionalInformation'),true).
clause1(value(uAVariable232,anon_1232),true).
clause1(references(uAVariable232,listOfReferences382),true).
clause1(displayName(uAVariable232,localizedText512),true).
clause1(type(uAVariable232,uAVariable),true).
clause1(hasTextContent(reference502,'ns=2;i=28'),true).
clause1(hasReferenceType(reference502,'HasProperty'),true).
clause1(type(reference502,reference),true).
clause1(hasTextContent(nodeIdAlias122,'i=13'),true).
clause1(hasAlias(nodeIdAlias122,'DateTime'),true).
clause1(type(nodeIdAlias122,nodeIdAlias),true).
clause1(hasTextContent(nodeIdAlias82,'i=8'),true).
clause1(hasAlias(nodeIdAlias82,'Int64'),true).
clause1(type(nodeIdAlias82,nodeIdAlias),true).
clause1(hasTextContent(reference202,'ns=2;i=11'),true).
clause1(hasReferenceType(reference202,'HasProperty'),true).
clause1(type(reference202,reference),true).
clause1(hasTextContent(localizedText532,'ID'),true).
clause1(type(localizedText532,localizedText),true).
clause1(hasTextContent(reference922,'ns=1;i=3007'),true).
clause1(hasReferenceType(reference922,'HasTypeDefinition'),true).
clause1(type(reference922,reference),true).
clause1(hasTextContent(localizedText232,'InstanceHierarchies'),true).
clause1(type(localizedText232,localizedText),true).
clause1(hasTextContent(reference62,'ns=2;i=15'),true).
clause1(hasReferenceType(reference62,'HasComponent'),true).
clause1(type(reference62,reference),true).
clause1(hasTextContent(reference622,'ns=2;i=44'),true).
clause1(hasReferenceType(reference622,'HasProperty'),true).
clause1(type(reference622,reference),true).
clause1(hasTextContent(reference1002,'PropertyType'),true).
clause1(hasReferenceType(reference1002,'HasTypeDefinition'),true).
clause1(type(reference1002,reference),true).
clause1(hasTextContent(nodeIdAlias242,'i=27'),true).
clause1(hasAlias(nodeIdAlias242,'Integer'),true).
clause1(type(nodeIdAlias242,nodeIdAlias),true).
clause1(hasTextContent(reference322,'ns=2;i=20'),true).
clause1(hasReferenceType(reference322,'HasComponent'),true).
clause1(type(reference322,reference),true).
clause1(reference(listOfReferences312,reference972),true).
clause1(type(listOfReferences312,listOfReferences),true).
clause1(reference(listOfReferences32,reference132),true).
clause1(reference(listOfReferences32,reference142),true).
clause1(reference(listOfReferences32,reference152),true).
clause1(reference(listOfReferences32,reference162),true).
clause1(reference(listOfReferences32,reference172),true).
clause1(reference(listOfReferences32,reference182),true).
clause1(type(listOfReferences32,listOfReferences),true).
clause1(hasParentNodeId(uAObject132,'ns=2;i=40'),true).
clause1(hasNodeId(uAObject132,'ns=2;i=46'),true).
clause1(hasBrowseName(uAObject132,'SystemUnitClassLibs'),true).
clause1(references(uAObject132,listOfReferences132),true).
clause1(displayName(uAObject132,localizedText242),true).
clause1(type(uAObject132,uAObject),true).
clause1(hasTextContent(localizedText352,'AdditionalInformation'),true).
clause1(type(localizedText352,localizedText),true).
clause1(hasTextContent(reference742,'ns=2;i=40'),true).
clause1(hasReferenceType(reference742,'HasComponent'),true).
clause1(hasIsForward(reference742,'false'),true).
clause1(type(reference742,reference),true).
clause1(hasTextContent(reference1122,'PropertyType'),true).
clause1(hasReferenceType(reference1122,'HasTypeDefinition'),true).
clause1(type(reference1122,reference),true).
clause1(hasTextContent(nodeIdAlias362,'i=61'),true).
clause1(hasAlias(nodeIdAlias362,'FolderType'),true).
clause1(type(nodeIdAlias362,nodeIdAlias),true).
clause1(type(anon_182,anon_1),true).
clause1(hasParentNodeId(uAVariable172,'ns=2;i=23'),true).
clause1(hasNodeId(uAVariable172,'ns=2;i=25'),true).
clause1(hasDataType(uAVariable172,'String'),true).
clause1(hasBrowseName(uAVariable172,'AdditionalInformation'),true).
clause1(value(uAVariable172,anon_1172),true).
clause1(references(uAVariable172,listOfReferences322),true).
clause1(displayName(uAVariable172,localizedText442),true).
clause1(type(uAVariable172,uAVariable),true).
clause1(hasTextContent(reference442,'ns=2;i=31'),true).
clause1(hasReferenceType(reference442,'HasTypeDefinition'),true).
clause1(type(reference442,reference),true).
clause1(type(anon_1212,anon_1),true).
clause1(reference(listOfReferences432,reference1112),true).
clause1(type(listOfReferences432,listOfReferences),true).
clause1(hasTextContent(reference142,'ns=2;i=8'),true).
clause1(hasReferenceType(reference142,'HasProperty'),true).
clause1(type(reference142,reference),true).
clause1(hasParentNodeId(uAVariable12,'ns=2;i=1'),true).
clause1(hasNodeId(uAVariable12,'ns=2;i=2'),true).
clause1(hasDataType(uAVariable12,'String'),true).
clause1(hasBrowseName(uAVariable12,'AdditionalInformation'),true).
clause1(value(uAVariable12,anon_112),true).
clause1(references(uAVariable12,listOfReferences162),true).
clause1(displayName(uAVariable12,localizedText272),true).
clause1(type(uAVariable12,uAVariable),true).
clause1(hasTextContent(localizedText472,'refURI'),true).
clause1(type(localizedText472,localizedText),true).
clause1(type(localizedText22,localizedText),true).
clause1(reference(listOfReferences132,reference712),true).
clause1(reference(listOfReferences132,reference722),true).
clause1(reference(listOfReferences132,reference732),true).
clause1(type(listOfReferences132,listOfReferences),true).
clause1(hasTextContent(reference862,'PropertyType'),true).
clause1(hasReferenceType(reference862,'HasTypeDefinition'),true).
clause1(type(reference862,reference),true).
clause1(hasTextContent(reference1242,'ns=2;i=37'),true).
clause1(hasReferenceType(reference1242,'HasComponent'),true).
clause1(type(reference1242,reference),true).
clause1(hasTextContent(nodeIdAlias32,'i=3'),true).
clause1(hasAlias(nodeIdAlias32,'Byte'),true).
clause1(type(nodeIdAlias32,nodeIdAlias),true).
clause1(hasTextContent(localizedText172,'PLCopenXMLInterface_instance_1'),true).
clause1(type(localizedText172,localizedText),true).
clause1(hasParentNodeId(uAVariable292,'ns=2;i=40'),true).
clause1(hasNodeId(uAVariable292,'ns=2;i=43'),true).
clause1(hasDataType(uAVariable292,'String'),true).
clause1(hasBrowseName(uAVariable292,'BaseRoleClassLib'),true).
clause1(value(uAVariable292,anon_1292),true).
clause1(references(uAVariable292,listOfReferences442),true).
clause1(displayName(uAVariable292,localizedText572),true).
clause1(type(uAVariable292,uAVariable),true).
clause1(hasTextContent(reference562,'ns=2;i=35'),true).
clause1(hasReferenceType(reference562,'HasComponent'),true).
clause1(hasIsForward(reference562,'false'),true).
clause1(type(reference562,reference),true).
clause1(hasTextContent(nodeIdAlias182,'i=18'),true).
clause1(hasAlias(nodeIdAlias182,'ExpandedNodeId'),true).
clause1(type(nodeIdAlias182,nodeIdAlias),true).
clause1(hasTextContent(reference262,'ns=2;i=14'),true).
clause1(hasReferenceType(reference262,'HasProperty'),true).
clause1(type(reference262,reference),true).
clause1(reference(listOfReferences252,reference892),true).
clause1(type(listOfReferences252,listOfReferences),true).
clause1(hasTextContent(reference12,'ns=2;i=2'),true).
clause1(hasReferenceType(reference12,'HasProperty'),true).
clause1(type(reference12,reference),true).
clause1(hasTextContent(localizedText592,'Energy'),true).
clause1(type(localizedText592,localizedText),true).
clause1(hasParentNodeId(uAVariable302,'ns=2;i=40'),true).
clause1(hasNodeId(uAVariable302,'ns=2;i=44'),true).
clause1(hasDataType(uAVariable302,'String'),true).
clause1(hasBrowseName(uAVariable302,'BaseInterfaceClassLib'),true).
clause1(value(uAVariable302,anon_1302),true).
clause1(references(uAVariable302,listOfReferences452),true).
clause1(displayName(uAVariable302,localizedText582),true).
clause1(type(uAVariable302,uAVariable),true).
clause1(hasTextContent(reference982,'PropertyType'),true).
clause1(hasReferenceType(reference982,'HasTypeDefinition'),true).
clause1(type(reference982,reference),true).
clause1(hasTextContent(localizedText292,'AdditionalInformation'),true).
clause1(type(localizedText292,localizedText),true).
clause1(hasTextContent(reference682,'ns=2;i=40'),true).
clause1(hasReferenceType(reference682,'HasComponent'),true).
clause1(hasIsForward(reference682,'false'),true).
clause1(type(reference682,reference),true).
clause1(hasTextContent(reference1062,'PropertyType'),true).
clause1(hasReferenceType(reference1062,'HasTypeDefinition'),true).
clause1(type(reference1062,reference),true).
clause1(type(localizedText602,localizedText),true).
clause1(hasTextContent(reference382,'ns=2;i=33'),true).
clause1(hasReferenceType(reference382,'ns=1;i=4002'),true).
clause1(type(reference382,reference),true).
clause1(type(anon_1152,anon_1),true).
clause1(hasTextContent(localizedText302,'Version'),true).
clause1(type(localizedText302,localizedText),true).
clause1(reference(listOfReferences372,reference1052),true).
clause1(type(listOfReferences372,listOfReferences),true).
clause1(reference(listOfReferences92,reference492),true).
clause1(reference(listOfReferences92,reference502),true).
clause1(reference(listOfReferences92,reference512),true).
clause1(reference(listOfReferences92,reference522),true).
clause1(reference(listOfReferences92,reference532),true).
clause1(type(listOfReferences92,listOfReferences),true).
clause1(hasTextContent(nodeIdAlias312,'i=40'),true).
clause1(hasAlias(nodeIdAlias312,'HasTypeDefinition'),true).
clause1(type(nodeIdAlias312,nodeIdAlias),true).
clause1(type(anon_132,anon_1),true).
clause1(hasBrowseName(uAVariable122,'New Attribute'),true).
clause1(value(uAVariable122,anon_1122),true).
clause1(references(uAVariable122,listOfReferences272),true).
clause1(type(uAVariable122,uAVariable),true).
clause1(hasNodeId(uAVariable122,'ns=2;i=18'),true).
clause1(hasParentNodeId(uAVariable122,'ns=2;i=12'),true).
clause1(hasAccessLevel(uAVariable122,'15'),true).
clause1(displayName(uAVariable122,localizedText382),true).
clause1(hasDataType(uAVariable122,'String'),true).
clause1(description(uAVariable122,localizedText392),true).
clause1(hasUserAccessLevel(uAVariable122,'15'),true).
clause1(hasTextContent(reference1182,'ns=2;i=6'),true).
clause1(hasReferenceType(reference1182,'HasComponent'),true).
clause1(hasIsForward(reference1182,'false'),true).
clause1(type(reference1182,reference),true).
clause1(hasNodeId(uAObject52,'ns=2;i=12'),true).
clause1(hasBrowseName(uAObject52,'firstScrewdriver'),true).
clause1(references(uAObject52,listOfReferences52),true).
clause1(displayName(uAObject52,localizedText92),true).
clause1(description(uAObject52,localizedText102),true).
clause1(type(uAObject52,uAObject),true).
clause1(type(anon_1272,anon_1),true).
clause1(hasTextContent(localizedText422,'AdditionalInformation'),true).
clause1(type(localizedText422,localizedText),true).
clause1(hasTextContent(reference812,'PropertyType'),true).
clause1(hasReferenceType(reference812,'HasTypeDefinition'),true).
clause1(type(reference812,reference),true).
clause1(hasParentNodeId(uAVariable72,'ns=2;i=9'),true).
clause1(hasNodeId(uAVariable72,'ns=2;i=11'),true).
clause1(hasDataType(uAVariable72,'String'),true).
clause1(hasBrowseName(uAVariable72,'AdditionalInformation'),true).
clause1(value(uAVariable72,anon_172),true).
clause1(references(uAVariable72,listOfReferences222),true).
clause1(displayName(uAVariable72,localizedText332),true).
clause1(type(uAVariable72,uAVariable),true).
clause1(type(localizedText82,localizedText),true).
clause1(type(localizedText122,localizedText),true).
clause1(reference(listOfReferences192,reference832),true).
clause1(type(listOfReferences192,listOfReferences),true).
clause1(hasParentNodeId(uAVariable242,'ns=2;i=35'),true).
clause1(hasNodeId(uAVariable242,'ns=2;i=36'),true).
clause1(hasDataType(uAVariable242,'String'),true).
clause1(hasBrowseName(uAVariable242,'AdditionalInformation'),true).
clause1(value(uAVariable242,anon_1242),true).
clause1(references(uAVariable242,listOfReferences392),true).
clause1(displayName(uAVariable242,localizedText522),true).
clause1(type(uAVariable242,uAVariable),true).
clause1(hasTextContent(reference512,'ns=2;i=15'),true).
clause1(hasReferenceType(reference512,'HasComponent'),true).
clause1(hasIsForward(reference512,'false'),true).
clause1(type(reference512,reference),true).
clause1(hasTextContent(nodeIdAlias132,'i=12'),true).
clause1(hasAlias(nodeIdAlias132,'String'),true).
clause1(type(nodeIdAlias132,nodeIdAlias),true).
clause1(hasTextContent(nodeIdAlias92,'i=9'),true).
clause1(hasAlias(nodeIdAlias92,'UInt64'),true).
clause1(type(nodeIdAlias92,nodeIdAlias),true).
clause1(hasTextContent(reference212,'FolderType'),true).
clause1(hasReferenceType(reference212,'HasTypeDefinition'),true).
clause1(type(reference212,reference),true).
clause1(reference(listOfReferences202,reference842),true).
clause1(type(listOfReferences202,listOfReferences),true).
clause1(hasTextContent(localizedText542,'AdditionalInformation'),true).
clause1(type(localizedText542,localizedText),true).
clause1(hasTextContent(reference932,'ns=2;i=12'),true).
clause1(hasReferenceType(reference932,'HasComponent'),true).
clause1(hasIsForward(reference932,'false'),true).
clause1(type(reference932,reference),true).
clause1(hasTextContent(localizedText242,'SystemUnitClassLibs'),true).
clause1(type(localizedText242,localizedText),true).
clause1(hasTextContent(reference72,'ns=2;i=4'),true).
clause1(hasReferenceType(reference72,'HasProperty'),true).
clause1(type(reference72,reference),true).
clause1(hasTextContent(reference632,'ns=2;i=45'),true).
clause1(hasReferenceType(reference632,'HasComponent'),true).
clause1(type(reference632,reference),true).
clause1(hasTextContent(reference1012,'ns=2;i=30'),true).
clause1(hasReferenceType(reference1012,'HasProperty'),true).
clause1(type(reference1012,reference),true).
clause1(hasTextContent(nodeIdAlias252,'i=28'),true).
clause1(hasAlias(nodeIdAlias252,'UInteger'),true).
clause1(type(nodeIdAlias252,nodeIdAlias),true).
clause1(hasTextContent(reference332,'ns=2;i=16'),true).
clause1(hasReferenceType(reference332,'HasProperty'),true).
clause1(type(reference332,reference),true).
clause1(type(anon_1102,anon_1),true).
clause1(reference(listOfReferences322,reference982),true).
clause1(type(listOfReferences322,listOfReferences),true).
clause1(reference(listOfReferences42,reference192),true).
clause1(reference(listOfReferences42,reference202),true).
clause1(reference(listOfReferences42,reference212),true).
clause1(reference(listOfReferences42,reference222),true).
clause1(reference(listOfReferences42,reference232),true).
clause1(reference(listOfReferences42,reference242),true).
clause1(type(listOfReferences42,listOfReferences),true).
clause1(hasParentNodeId(uAObject142,'ns=2;i=40'),true).
clause1(hasNodeId(uAObject142,'ns=2;i=47'),true).
clause1(hasBrowseName(uAObject142,'RoleClassLibs'),true).
clause1(references(uAObject142,listOfReferences142),true).
clause1(displayName(uAObject142,localizedText252),true).
clause1(type(uAObject142,uAObject),true).
clause1(hasTextContent(localizedText362,'ID'),true).
clause1(type(localizedText362,localizedText),true).
clause1(hasTextContent(reference752,'FolderType'),true).
clause1(hasReferenceType(reference752,'HasTypeDefinition'),true).
clause1(type(reference752,reference),true).
clause1(hasTextContent(reference1132,'PropertyType'),true).
clause1(hasReferenceType(reference1132,'HasTypeDefinition'),true).
clause1(type(reference1132,reference),true).
clause1(hasTextContent(nodeIdAlias372,'i=68'),true).
clause1(hasAlias(nodeIdAlias372,'PropertyType'),true).
clause1(type(nodeIdAlias372,nodeIdAlias),true).
clause1(type(anon_192,anon_1),true).
clause1(hasParentNodeId(uAVariable182,'ns=2;i=26'),true).
clause1(hasNodeId(uAVariable182,'ns=2;i=27'),true).
clause1(hasDataType(uAVariable182,'String'),true).
clause1(hasBrowseName(uAVariable182,'ID'),true).
clause1(value(uAVariable182,anon_1182),true).
clause1(references(uAVariable182,listOfReferences332),true).
clause1(displayName(uAVariable182,localizedText452),true).
clause1(type(uAVariable182,uAVariable),true).
clause1(hasTextContent(reference452,'ns=2;i=24'),true).
clause1(hasReferenceType(reference452,'HasProperty'),true).
clause1(type(reference452,reference),true).
clause1(type(anon_1222,anon_1),true).
clause1(hasTextContent(reference152,'FolderType'),true).
clause1(hasReferenceType(reference152,'HasTypeDefinition'),true).
clause1(type(reference152,reference),true).
clause1(reference(listOfReferences442,reference1122),true).
clause1(type(listOfReferences442,listOfReferences),true).
clause1(hasParentNodeId(uAVariable22,'ns=2;i=3'),true).
clause1(hasNodeId(uAVariable22,'ns=2;i=4'),true).
clause1(hasDataType(uAVariable22,'String'),true).
clause1(hasBrowseName(uAVariable22,'Version'),true).
clause1(value(uAVariable22,anon_122),true).
clause1(references(uAVariable22,listOfReferences172),true).
clause1(displayName(uAVariable22,localizedText282),true).
clause1(type(uAVariable22,uAVariable),true).
clause1(type(localizedText482,localizedText),true).
clause1(hasTextContent(localizedText32,'MyInterfaces'),true).
clause1(type(localizedText32,localizedText),true).
clause1(reference(listOfReferences142,reference742),true).
clause1(reference(listOfReferences142,reference752),true).
clause1(reference(listOfReferences142,reference762),true).
clause1(type(listOfReferences142,listOfReferences),true).
clause1(hasTextContent(reference872,'PropertyType'),true).
clause1(hasReferenceType(reference872,'HasTypeDefinition'),true).
clause1(type(reference872,reference),true).
clause1(hasTextContent(nodeIdAlias42,'i=4'),true).
clause1(hasAlias(nodeIdAlias42,'Int16'),true).
clause1(type(nodeIdAlias42,nodeIdAlias),true).
clause1(type(localizedText182,localizedText),true).
clause1(hasTextContent(reference572,'ns=2;i=31'),true).
clause1(hasReferenceType(reference572,'HasTypeDefinition'),true).
clause1(type(reference572,reference),true).
clause1(hasTextContent(nodeIdAlias192,'i=19'),true).
clause1(hasAlias(nodeIdAlias192,'StatusCode'),true).
clause1(type(nodeIdAlias192,nodeIdAlias),true).
clause1(hasTextContent(reference272,'ns=2;i=1'),true).
clause1(hasReferenceType(reference272,'HasComponent'),true).
clause1(hasIsForward(reference272,'false'),true).
clause1(type(reference272,reference),true).
clause1(hasTextContent(reference22,'FolderType'),true).
clause1(hasReferenceType(reference22,'HasTypeDefinition'),true).
clause1(type(reference22,reference),true).
clause1(reference(listOfReferences262,reference902),true).
clause1(type(listOfReferences262,listOfReferences),true).
clause1(hasTextContent(reference992,'PropertyType'),true).
clause1(hasReferenceType(reference992,'HasTypeDefinition'),true).
clause1(type(reference992,reference),true).
clause1(hasTextContent(nodeIdAlias202,'i=20'),true).
clause1(hasAlias(nodeIdAlias202,'QualifiedName'),true).
clause1(type(nodeIdAlias202,nodeIdAlias),true).
clause1(hasTextContent(reference692,'FolderType'),true).
clause1(hasReferenceType(reference692,'HasTypeDefinition'),true).
clause1(type(reference692,reference),true).
clause1(hasTextContent(reference1072,'PropertyType'),true).
clause1(hasReferenceType(reference1072,'HasTypeDefinition'),true).
clause1(type(reference1072,reference),true).
clause1(hasTextContent(localizedText612,'Tool'),true).
clause1(type(localizedText612,localizedText),true).
clause1(hasTextContent(reference392,'ns=2;i=23'),true).
clause1(hasReferenceType(reference392,'HasComponent'),true).
clause1(type(reference392,reference),true).
clause1(type(anon_1162,anon_1),true).
clause1(hasTextContent(localizedText312,'AdditionalInformation'),true).
clause1(type(localizedText312,localizedText),true).
clause1(reference(listOfReferences382,reference1062),true).
clause1(type(listOfReferences382,listOfReferences),true).
clause1(hasTextContent(reference702,'ns=2;i=1'),true).
clause1(hasReferenceType(reference702,'HasComponent'),true).
clause1(type(reference702,reference),true).
clause1(hasTextContent(nodeIdAlias322,'i=45'),true).
clause1(hasAlias(nodeIdAlias322,'HasSubtype'),true).
clause1(type(nodeIdAlias322,nodeIdAlias),true).
clause1(type(anon_142,anon_1),true).
clause1(hasParentNodeId(uAVariable132,'ns=2;i=18'),true).
clause1(hasNodeId(uAVariable132,'ns=2;i=19'),true).
clause1(hasDataType(uAVariable132,'String'),true).
clause1(hasBrowseName(uAVariable132,'AdditionalInformation'),true).
clause1(value(uAVariable132,anon_1132),true).
clause1(references(uAVariable132,listOfReferences282),true).
clause1(displayName(uAVariable132,localizedText402),true).
clause1(type(uAVariable132,uAVariable),true).
clause1(hasTextContent(reference402,'ns=2;i=26'),true).
clause1(hasReferenceType(reference402,'HasComponent'),true).
clause1(type(reference402,reference),true).
clause1(hasTextContent(reference1192,'ns=1;i=1003'),true).
clause1(hasReferenceType(reference1192,'HasSubtype'),true).
clause1(hasIsForward(reference1192,'false'),true).
clause1(type(reference1192,reference),true).
clause1(hasTextContent(reference102,'ns=1;i=5004'),true).
clause1(hasReferenceType(reference102,'Organizes'),true).
clause1(hasIsForward(reference102,'false'),true).
clause1(type(reference102,reference),true).
clause1(hasNodeId(uAObject62,'ns=2;i=15'),true).
clause1(hasBrowseName(uAObject62,'secondScrewdriver'),true).
clause1(references(uAObject62,listOfReferences62),true).
clause1(displayName(uAObject62,localizedText112),true).
clause1(description(uAObject62,localizedText122),true).
clause1(type(uAObject62,uAObject),true).
clause1(type(anon_1282,anon_1),true).
clause1(hasTextContent(localizedText432,'ID'),true).
clause1(type(localizedText432,localizedText),true).
clause1(hasTextContent(reference822,'PropertyType'),true).
clause1(hasReferenceType(reference822,'HasTypeDefinition'),true).
clause1(type(reference822,reference),true).
clause1(hasParentNodeId(uAVariable82,'ns=2;i=12'),true).
clause1(hasNodeId(uAVariable82,'ns=2;i=13'),true).
clause1(hasDataType(uAVariable82,'String'),true).
clause1(hasBrowseName(uAVariable82,'ID'),true).
clause1(value(uAVariable82,anon_182),true).
clause1(references(uAVariable82,listOfReferences232),true).
clause1(displayName(uAVariable82,localizedText342),true).
clause1(type(uAVariable82,uAVariable),true).
clause1(hasTextContent(reference1202,'ns=2;i=36'),true).
clause1(hasReferenceType(reference1202,'HasProperty'),true).
clause1(type(reference1202,reference),true).
clause1(hasTextContent(localizedText132,'EnergySupply'),true).
clause1(type(localizedText132,localizedText),true).
clause1(hasTextContent(localizedText92,'firstScrewdriver'),true).
clause1(type(localizedText92,localizedText),true).
clause1(hasParentNodeId(uAVariable252,'ns=2;i=37'),true).
clause1(hasNodeId(uAVariable252,'ns=2;i=38'),true).
clause1(hasDataType(uAVariable252,'String'),true).
clause1(hasBrowseName(uAVariable252,'ID'),true).
clause1(value(uAVariable252,anon_1252),true).
clause1(references(uAVariable252,listOfReferences402),true).
clause1(displayName(uAVariable252,localizedText532),true).
clause1(type(uAVariable252,uAVariable),true).
clause1(hasTextContent(reference522,'i='),true).
clause1(hasReferenceType(reference522,'HasTypeDefinition'),true).
clause1(type(reference522,reference),true).
clause1(hasTextContent(nodeIdAlias142,'i=15'),true).
clause1(hasAlias(nodeIdAlias142,'ByteString'),true).
clause1(type(nodeIdAlias142,nodeIdAlias),true).
clause1(hasTextContent(reference222,'ns=1;i=5006'),true).
clause1(hasReferenceType(reference222,'Organizes'),true).
clause1(hasIsForward(reference222,'false'),true).
clause1(type(reference222,reference),true).
clause1(hasTextContent(localizedText552,'AdditionalInformation'),true).
clause1(type(localizedText552,localizedText),true).
clause1(reference(listOfReferences212,reference852),true).
clause1(type(listOfReferences212,listOfReferences),true).
clause1(hasTextContent(reference942,'PropertyType'),true).
clause1(hasReferenceType(reference942,'HasTypeDefinition'),true).
clause1(type(reference942,reference),true).
clause1(hasTextContent(reference82,'ns=2;i=5'),true).
clause1(hasReferenceType(reference82,'HasProperty'),true).
clause1(type(reference82,reference),true).
clause1(hasTextContent(localizedText252,'RoleClassLibs'),true).
clause1(type(localizedText252,localizedText),true).
clause1(hasTextContent(reference642,'ns=2;i=46'),true).
clause1(hasReferenceType(reference642,'HasComponent'),true).
clause1(type(reference642,reference),true).
clause1(hasTextContent(reference1022,'ns=1;i=3007'),true).
clause1(hasReferenceType(reference1022,'HasTypeDefinition'),true).
clause1(type(reference1022,reference),true).
clause1(hasTextContent(nodeIdAlias262,'i=35'),true).
clause1(hasAlias(nodeIdAlias262,'Organizes'),true).
clause1(type(nodeIdAlias262,nodeIdAlias),true).
clause1(hasTextContent(reference342,'ns=2;i=17'),true).
clause1(hasReferenceType(reference342,'HasProperty'),true).
clause1(type(reference342,reference),true).
clause1(type(anon_1112,anon_1),true).
clause1(reference(listOfReferences332,reference992),true).
clause1(type(listOfReferences332,listOfReferences),true).
clause1(reference(listOfReferences52,reference252),true).
clause1(reference(listOfReferences52,reference262),true).
clause1(reference(listOfReferences52,reference272),true).
clause1(reference(listOfReferences52,reference282),true).
clause1(reference(listOfReferences52,reference292),true).
clause1(reference(listOfReferences52,reference302),true).
clause1(reference(listOfReferences52,reference312),true).
clause1(reference(listOfReferences52,reference322),true).
clause1(type(listOfReferences52,listOfReferences),true).
clause1(hasParentNodeId(uAObject152,'ns=2;i=40'),true).
clause1(hasNodeId(uAObject152,'ns=2;i=48'),true).
clause1(hasBrowseName(uAObject152,'InterfaceClassLibs'),true).
clause1(references(uAObject152,listOfReferences152),true).
clause1(displayName(uAObject152,localizedText262),true).
clause1(type(uAObject152,uAObject),true).
clause1(hasTextContent(localizedText372,'AdditionalInformation'),true).
clause1(type(localizedText372,localizedText),true).
clause1(hasTextContent(reference762,'ns=2;i=6'),true).
clause1(hasReferenceType(reference762,'HasComponent'),true).
clause1(type(reference762,reference),true).
clause1(hasTextContent(reference1142,'ns=2;i=32'),true).
clause1(hasReferenceType(reference1142,'HasProperty'),true).
clause1(type(reference1142,reference),true).
clause1(hasTextContent(nodeIdAlias382,'i=78'),true).
clause1(hasAlias(nodeIdAlias382,'Mandatory'),true).
clause1(type(nodeIdAlias382,nodeIdAlias),true).
clause1(hasParentNodeId(uAVariable192,'ns=2;i=26'),true).
clause1(hasNodeId(uAVariable192,'ns=2;i=28'),true).
clause1(hasDataType(uAVariable192,'String'),true).
clause1(hasBrowseName(uAVariable192,'AdditionalInformation'),true).
clause1(value(uAVariable192,anon_1192),true).
clause1(references(uAVariable192,listOfReferences342),true).
clause1(displayName(uAVariable192,localizedText462),true).
clause1(type(uAVariable192,uAVariable),true).
clause1(hasNodeId(uAObject12,'ns=2;i=1'),true).
clause1(hasBrowseName(uAObject12,'ManufacturingSystem'),true).
clause1(references(uAObject12,listOfReferences12),true).
clause1(displayName(uAObject12,localizedText12),true).
clause1(description(uAObject12,localizedText22),true).
clause1(type(uAObject12,uAObject),true).
clause1(hasTextContent(reference462,'ns=2;i=25'),true).
clause1(hasReferenceType(reference462,'HasProperty'),true).
clause1(type(reference462,reference),true).
clause1(type(anon_1232,anon_1),true).
clause1(hasTextContent(reference162,'ns=1;i=5005'),true).
clause1(hasReferenceType(reference162,'Organizes'),true).
clause1(hasIsForward(reference162,'false'),true).
clause1(type(reference162,reference),true).
clause1(reference(listOfReferences452,reference1132),true).
clause1(type(listOfReferences452,listOfReferences),true).
clause1(hasParentNodeId(uAVariable32,'ns=2;i=3'),true).
clause1(hasNodeId(uAVariable32,'ns=2;i=5'),true).
clause1(hasDataType(uAVariable32,'String'),true).
clause1(hasBrowseName(uAVariable32,'AdditionalInformation'),true).
clause1(value(uAVariable32,anon_132),true).
clause1(references(uAVariable32,listOfReferences182),true).
clause1(displayName(uAVariable32,localizedText292),true).
clause1(type(uAVariable32,uAVariable),true).
clause1(hasTextContent(localizedText492,'AdditionalInformation'),true).
clause1(type(localizedText492,localizedText),true).
clause1(type(localizedText42,localizedText),true).
clause1(reference(listOfReferences152,reference772),true).
clause1(reference(listOfReferences152,reference782),true).
clause1(reference(listOfReferences152,reference792),true).
clause1(type(listOfReferences152,listOfReferences),true).
clause1(hasNodeId(uAVariable202,'ns=2;i=29'),true).
clause1(value(uAVariable202,anon_1202),true).
clause1(hasBrowseName(uAVariable202,'refURI'),true).
clause1(references(uAVariable202,listOfReferences352),true).
clause1(type(uAVariable202,uAVariable),true).
clause1(hasDataType(uAVariable202,'String'),true).
clause1(hasUserAccessLevel(uAVariable202,'15'),true).
clause1(hasAccessLevel(uAVariable202,'15'),true).
clause1(displayName(uAVariable202,localizedText472),true).
clause1(description(uAVariable202,localizedText482),true).
clause1(hasParentNodeId(uAVariable202,'ns=2;i=26'),true).
clause1(hasTextContent(reference882,'PropertyType'),true).
clause1(hasReferenceType(reference882,'HasTypeDefinition'),true).
clause1(type(reference882,reference),true).
clause1(hasTextContent(nodeIdAlias52,'i=5'),true).
clause1(hasAlias(nodeIdAlias52,'UInt16'),true).
clause1(type(nodeIdAlias52,nodeIdAlias),true).
clause1(hasTextContent(localizedText192,'EnergySupply'),true).
clause1(type(localizedText192,localizedText),true).
clause1(hasTextContent(reference582,'ns=2;i=41'),true).
clause1(hasReferenceType(reference582,'HasProperty'),true).
clause1(type(reference582,reference),true).
clause1(hasTextContent(localizedText502,'AdditionalInformation'),true).
clause1(type(localizedText502,localizedText),true).
clause1(hasTextContent(reference282,'ns=2;i=35'),true).
clause1(hasReferenceType(reference282,'HasTypeDefinition'),true).
clause1(type(reference282,reference),true).
clause1(hasTextContent(reference32,'ns=1;i=5002'),true).
clause1(hasReferenceType(reference32,'Organizes'),true).
clause1(hasIsForward(reference32,'false'),true).
clause1(type(reference32,reference),true).
clause1(type(localizedText202,localizedText),true).
clause1(reference(listOfReferences272,reference912),true).
clause1(reference(listOfReferences272,reference922),true).
clause1(reference(listOfReferences272,reference932),true).
clause1(type(listOfReferences272,listOfReferences),true).
clause1(uAVariable(uANodeSet12,uAVariable112),true).
clause1(uAObject(uANodeSet12,uAObject12),true).
clause1(uAVariable(uANodeSet12,uAVariable132),true).
clause1(uAVariable(uANodeSet12,uAVariable12),true).
clause1(uAObject(uANodeSet12,uAObject132),true).
clause1(uAObject(uANodeSet12,uAObject142),true).
clause1(uAVariable(uANodeSet12,uAVariable72),true).
clause1(uAVariable(uANodeSet12,uAVariable92),true).
clause1(uAVariable(uANodeSet12,uAVariable262),true).
clause1(uAVariable(uANodeSet12,uAVariable162),true).
clause1(uAVariable(uANodeSet12,uAVariable212),true).
clause1(uAVariable(uANodeSet12,uAVariable292),true).
clause1(uAObject(uANodeSet12,uAObject42),true).
clause1(uAObject(uANodeSet12,uAObject52),true).
clause1(uAObject(uANodeSet12,uAObject112),true).
clause1(uAVariable(uANodeSet12,uAVariable142),true).
clause1(uAVariable(uANodeSet12,uAVariable22),true).
clause1(uAObject(uANodeSet12,uAObject122),true).
clause1(uAVariable(uANodeSet12,uAVariable82),true).
clause1(uAVariable(uANodeSet12,uAVariable272),true).
clause1(uAObjectType(uANodeSet12,uAObjectType12),true).
clause1(uAVariable(uANodeSet12,uAVariable52),true).
clause1(uAObject(uANodeSet12,uAObject82),true).
clause1(uAObject(uANodeSet12,uAObject92),true).
clause1(uAVariable(uANodeSet12,uAVariable172),true).
clause1(uAVariable(uANodeSet12,uAVariable222),true).
clause1(uAVariable(uANodeSet12,uAVariable242),true).
clause1(uAObject(uANodeSet12,uAObject32),true).
clause1(aliases(uANodeSet12,aliasTable12),true).
clause1(uAObject(uANodeSet12,uAObject152),true).
clause1(uAVariable(uANodeSet12,uAVariable192),true).
clause1(uAVariable(uANodeSet12,uAVariable32),true).
clause1(uAVariable(uANodeSet12,uAVariable152),true).
clause1(uAVariable(uANodeSet12,uAVariable302),true).
clause1(uAVariable(uANodeSet12,uAVariable102),true).
clause1(uAObject(uANodeSet12,uAObject22),true).
clause1(type(uANodeSet12,uANodeSet),true).
clause1(uAVariable(uANodeSet12,uAVariable122),true).
clause1(uAObject(uANodeSet12,uAObject72),true).
clause1(uAVariable(uANodeSet12,uAVariable62),true).
clause1(uAVariable(uANodeSet12,uAVariable182),true).
clause1(uAVariable(uANodeSet12,uAVariable232),true).
clause1(uAObjectType(uANodeSet12,uAObjectType22),true).
clause1(uAVariable(uANodeSet12,uAVariable252),true).
clause1(uAObjectType(uANodeSet12,uAObjectType32),true).
clause1(uAObject(uANodeSet12,uAObject102),true).
clause1(uAVariable(uANodeSet12,uAVariable202),true).
clause1(uAVariable(uANodeSet12,uAVariable282),true).
clause1(namespaceUris(uANodeSet12,uriTable12),true).
clause1(uAObject(uANodeSet12,uAObject62),true).
clause1(uAVariable(uANodeSet12,uAVariable42),true).
clause1(hasTextContent(nodeIdAlias212,'i=21'),true).
clause1(hasAlias(nodeIdAlias212,'LocalizedText'),true).
clause1(type(nodeIdAlias212,nodeIdAlias),true).
clause1(hasTextContent(reference1082,'PropertyType'),true).
clause1(hasReferenceType(reference1082,'HasTypeDefinition'),true).
clause1(type(reference1082,reference),true).
clause1(type(localizedText622,localizedText),true).
clause1(hasParentNodeId(uAObject102,'ns=2;i=35'),true).
clause1(hasNodeId(uAObject102,'ns=2;i=37'),true).
clause1(hasBrowseName(uAObject102,'EnergySupply'),true).
clause1(references(uAObject102,listOfReferences102),true).
clause1(displayName(uAObject102,localizedText192),true).
clause1(description(uAObject102,localizedText202),true).
clause1(type(uAObject102,uAObject),true).
clause1(type(anon_1172,anon_1),true).
clause1(hasTextContent(localizedText322,'Version'),true).
clause1(type(localizedText322,localizedText),true).
clause1(reference(listOfReferences392,reference1072),true).
clause1(type(listOfReferences392,listOfReferences),true).
clause1(hasTextContent(reference712,'ns=2;i=40'),true).
clause1(hasReferenceType(reference712,'HasComponent'),true).
clause1(hasIsForward(reference712,'false'),true).
clause1(type(reference712,reference),true).
clause1(hasTextContent(nodeIdAlias332,'i=46'),true).
clause1(hasAlias(nodeIdAlias332,'HasProperty'),true).
clause1(type(nodeIdAlias332,nodeIdAlias),true).
clause1(type(anon_152,anon_1),true).
clause1(hasParentNodeId(uAVariable142,'ns=2;i=20'),true).
clause1(hasNodeId(uAVariable142,'ns=2;i=21'),true).
clause1(hasDataType(uAVariable142,'String'),true).
clause1(hasBrowseName(uAVariable142,'ID'),true).
clause1(value(uAVariable142,anon_1142),true).
clause1(references(uAVariable142,listOfReferences292),true).
clause1(displayName(uAVariable142,localizedText412),true).
clause1(type(uAVariable142,uAVariable),true).
clause1(hasTextContent(reference412,'ns=2;i=21'),true).
clause1(hasReferenceType(reference412,'HasProperty'),true).
clause1(type(reference412,reference),true).
clause1(hasTextContent(reference112,'ns=2;i=48'),true).
clause1(hasReferenceType(reference112,'HasComponent'),true).
clause1(hasIsForward(reference112,'false'),true).
clause1(type(reference112,reference),true).
clause1(reference(listOfReferences402,reference1082),true).
clause1(type(listOfReferences402,listOfReferences),true).
clause1(hasParentNodeId(uAObject72,'ns=2;i=12'),true).
clause1(hasNodeId(uAObject72,'ns=2;i=20'),true).
clause1(hasBrowseName(uAObject72,'EnergySupply'),true).
clause1(references(uAObject72,listOfReferences72),true).
clause1(displayName(uAObject72,localizedText132),true).
clause1(description(uAObject72,localizedText142),true).
clause1(type(uAObject72,uAObject),true).
clause1(type(anon_1292,anon_1),true).
clause1(hasTextContent(localizedText442,'AdditionalInformation'),true).
clause1(type(localizedText442,localizedText),true).
clause1(reference(listOfReferences102,reference542),true).
clause1(reference(listOfReferences102,reference552),true).
clause1(reference(listOfReferences102,reference562),true).
clause1(reference(listOfReferences102,reference572),true).
clause1(type(listOfReferences102,listOfReferences),true).
clause1(hasTextContent(reference832,'PropertyType'),true).
clause1(hasReferenceType(reference832,'HasTypeDefinition'),true).
clause1(type(reference832,reference),true).
clause1(hasParentNodeId(uAVariable92,'ns=2;i=12'),true).
clause1(hasNodeId(uAVariable92,'ns=2;i=14'),true).
clause1(hasDataType(uAVariable92,'String'),true).
clause1(hasBrowseName(uAVariable92,'AdditionalInformation'),true).
clause1(value(uAVariable92,anon_192),true).
clause1(references(uAVariable92,listOfReferences242),true).
clause1(displayName(uAVariable92,localizedText352),true).
clause1(type(uAVariable92,uAVariable),true).
clause1(hasTextContent(reference1212,'ns=2;i=9'),true).
clause1(hasReferenceType(reference1212,'HasComponent'),true).
clause1(hasIsForward(reference1212,'false'),true).
clause1(type(reference1212,reference),true).
clause1(type(localizedText142,localizedText),true).
clause1(hasParentNodeId(uAVariable262,'ns=2;i=37'),true).
clause1(hasNodeId(uAVariable262,'ns=2;i=39'),true).
clause1(hasDataType(uAVariable262,'String'),true).
clause1(hasBrowseName(uAVariable262,'AdditionalInformation'),true).
clause1(value(uAVariable262,anon_1262),true).
clause1(references(uAVariable262,listOfReferences412),true).
clause1(displayName(uAVariable262,localizedText542),true).
clause1(type(uAVariable262,uAVariable),true).
clause1(hasTextContent(reference532,'ns=2;i=29'),true).
clause1(hasReferenceType(reference532,'HasComponent'),true).
clause1(type(reference532,reference),true).
clause1(hasTextContent(nodeIdAlias152,'i=14'),true).
clause1(hasAlias(nodeIdAlias152,'Guid'),true).
clause1(type(nodeIdAlias152,nodeIdAlias),true).
clause1(type(anon_1302,anon_1),true).
clause1(hasTextContent(reference232,'ns=2;i=46'),true).
clause1(hasReferenceType(reference232,'HasComponent'),true).
clause1(hasIsForward(reference232,'false'),true).
clause1(type(reference232,reference),true).
clause1(hasTextContent(localizedText562,'SchemaVersion'),true).
clause1(type(localizedText562,localizedText),true).
clause1(reference(listOfReferences222,reference862),true).
clause1(type(listOfReferences222,listOfReferences),true).
clause1(hasTextContent(reference952,'PropertyType'),true).
clause1(hasReferenceType(reference952,'HasTypeDefinition'),true).
clause1(type(reference952,reference),true).
clause1(hasTextContent(localizedText262,'InterfaceClassLibs'),true).
clause1(type(localizedText262,localizedText),true).
clause1(hasTextContent(reference92,'FolderType'),true).
clause1(hasReferenceType(reference92,'HasTypeDefinition'),true).
clause1(type(reference92,reference),true).
clause1(hasNodeId(uAObjectType12,'ns=2;i=31'),true).
clause1(hasBrowseName(uAObjectType12,'Energy'),true).
clause1(references(uAObjectType12,listOfReferences462),true).
clause1(displayName(uAObjectType12,localizedText592),true).
clause1(description(uAObjectType12,localizedText602),true).
clause1(type(uAObjectType12,uAObjectType),true).
clause1(hasTextContent(reference652,'ns=2;i=47'),true).
clause1(hasReferenceType(reference652,'HasComponent'),true).
clause1(type(reference652,reference),true).
clause1(hasTextContent(reference1032,'ns=2;i=26'),true).
clause1(hasReferenceType(reference1032,'HasComponent'),true).
clause1(hasIsForward(reference1032,'false'),true).
clause1(type(reference1032,reference),true).
clause1(hasTextContent(nodeIdAlias272,'i=36'),true).
clause1(hasAlias(nodeIdAlias272,'HasEventSource'),true).
clause1(type(nodeIdAlias272,nodeIdAlias),true).
clause1(hasTextContent(reference352,'ns=2;i=1'),true).
clause1(hasReferenceType(reference352,'HasComponent'),true).
clause1(hasIsForward(reference352,'false'),true).
clause1(type(reference352,reference),true).
clause1(type(anon_1122,anon_1),true).
clause1(reference(listOfReferences342,reference1002),true).
clause1(type(listOfReferences342,listOfReferences),true).
clause1(reference(listOfReferences62,reference332),true).
clause1(reference(listOfReferences62,reference342),true).
clause1(reference(listOfReferences62,reference352),true).
clause1(reference(listOfReferences62,reference362),true).
clause1(reference(listOfReferences62,reference372),true).
clause1(reference(listOfReferences62,reference382),true).
clause1(reference(listOfReferences62,reference392),true).
clause1(reference(listOfReferences62,reference402),true).
clause1(type(listOfReferences62,listOfReferences),true).
clause1(hasTextContent(localizedText382,'New Attribute'),true).
clause1(type(localizedText382,localizedText),true).
clause1(hasTextContent(reference772,'ns=2;i=40'),true).
clause1(hasReferenceType(reference772,'HasComponent'),true).
clause1(hasIsForward(reference772,'false'),true).
clause1(type(reference772,reference),true).
clause1(hasTextContent(reference1152,'ns=2;i=3'),true).
clause1(hasReferenceType(reference1152,'HasComponent'),true).
clause1(hasIsForward(reference1152,'false'),true).
clause1(type(reference1152,reference),true).
clause1(hasTextContent(nodeIdAlias392,'i=80'),true).
clause1(hasAlias(nodeIdAlias392,'Optional'),true).
clause1(type(nodeIdAlias392,nodeIdAlias),true).
clause1(hasTextContent(reference472,'ns=2;i=15'),true).
clause1(hasReferenceType(reference472,'HasComponent'),true).
clause1(hasIsForward(reference472,'false'),true).
clause1(type(reference472,reference),true).
clause1(hasNodeId(uAObject22,'ns=2;i=3'),true).
clause1(hasBrowseName(uAObject22,'MyInterfaces'),true).
clause1(references(uAObject22,listOfReferences22),true).
clause1(displayName(uAObject22,localizedText32),true).
clause1(description(uAObject22,localizedText42),true).
clause1(type(uAObject22,uAObject),true).
clause1(type(anon_1242,anon_1),true).
clause1(reference(listOfReferences462,reference1142),true).
clause1(reference(listOfReferences462,reference1152),true).
clause1(reference(listOfReferences462,reference1162),true).
clause1(type(listOfReferences462,listOfReferences),true).
clause1(hasTextContent(reference172,'ns=2;i=47'),true).
clause1(hasReferenceType(reference172,'HasComponent'),true).
clause1(hasIsForward(reference172,'false'),true).
clause1(type(reference172,reference),true).
clause1(hasParentNodeId(uAVariable42,'ns=2;i=6'),true).
clause1(hasNodeId(uAVariable42,'ns=2;i=7'),true).
clause1(hasDataType(uAVariable42,'String'),true).
clause1(hasBrowseName(uAVariable42,'Version'),true).
clause1(value(uAVariable42,anon_142),true).
clause1(references(uAVariable42,listOfReferences192),true).
clause1(displayName(uAVariable42,localizedText302),true).
clause1(type(uAVariable42,uAVariable),true).
clause1(hasTextContent(nodeIdAlias402,'i=85'),true).
clause1(hasAlias(nodeIdAlias402,'Objects'),true).
clause1(type(nodeIdAlias402,nodeIdAlias),true).
clause1(hasTextContent(localizedText52,'ManufacturingRoleClasses'),true).
clause1(type(localizedText52,localizedText),true).
clause1(reference(listOfReferences162,reference802),true).
clause1(type(listOfReferences162,listOfReferences),true).
clause1(hasUri(uriTable12,'http://opcfoundation.org/UA/AML/'),true).
clause1(hasUri(uriTable12,'http://www.iosb.fraunhofer.de/Topology.aml'),true).
clause1(type(uriTable12,uriTable),true).
clause1(hasParentNodeId(uAVariable212,'ns=2;i=29'),true).
clause1(hasNodeId(uAVariable212,'ns=2;i=30'),true).
clause1(hasDataType(uAVariable212,'String'),true).
clause1(hasBrowseName(uAVariable212,'AdditionalInformation'),true).
clause1(value(uAVariable212,anon_1212),true).
clause1(references(uAVariable212,listOfReferences362),true).
clause1(displayName(uAVariable212,localizedText492),true).
clause1(type(uAVariable212,uAVariable),true).
clause1(hasTextContent(reference892,'PropertyType'),true).
clause1(hasReferenceType(reference892,'HasTypeDefinition'),true).
clause1(type(reference892,reference),true).
clause1(hasTextContent(nodeIdAlias102,'i=10'),true).
clause1(hasAlias(nodeIdAlias102,'Float'),true).
clause1(type(nodeIdAlias102,nodeIdAlias),true).
clause1(hasTextContent(nodeIdAlias62,'i=6'),true).
clause1(hasAlias(nodeIdAlias62,'Int32'),true).
clause1(type(nodeIdAlias62,nodeIdAlias),true).
clause1(hasTextContent(reference592,'ns=1;i=1002'),true).
clause1(hasReferenceType(reference592,'HasTypeDefinition'),true).
clause1(type(reference592,reference),true).
clause1(hasTextContent(localizedText512,'AdditionalInformation'),true).
clause1(type(localizedText512,localizedText),true).
clause1(hasTextContent(reference292,'ns=2;i=33'),true).
clause1(hasReferenceType(reference292,'ns=1;i=4001'),true).
clause1(type(reference292,reference),true).
clause1(hasTextContent(reference902,'PropertyType'),true).
clause1(hasReferenceType(reference902,'HasTypeDefinition'),true).
clause1(type(reference902,reference),true).
clause1(hasTextContent(localizedText212,'Topology.aml'),true).
clause1(type(localizedText212,localizedText),true).
clause1(hasTextContent(reference42,'ns=2;i=45'),true).
clause1(hasReferenceType(reference42,'HasComponent'),true).
clause1(hasIsForward(reference42,'false'),true).
clause1(type(reference42,reference),true).
clause1(reference(listOfReferences282,reference942),true).
clause1(type(listOfReferences282,listOfReferences),true).
clause1(hasTextContent(reference602,'ns=2;i=42'),true).
clause1(hasReferenceType(reference602,'HasProperty'),true).
clause1(type(reference602,reference),true).
clause1(hasTextContent(nodeIdAlias222,'i=22'),true).
clause1(hasAlias(nodeIdAlias222,'Structure'),true).
clause1(type(nodeIdAlias222,nodeIdAlias),true).
clause1(hasTextContent(reference302,'ns=2;i=33'),true).
clause1(hasReferenceType(reference302,'ns=1;i=4002'),true).
clause1(type(reference302,reference),true).
clause1(hasTextContent(reference1092,'PropertyType'),true).
clause1(hasReferenceType(reference1092,'HasTypeDefinition'),true).
clause1(type(reference1092,reference),true).
clause1(hasTextContent(localizedText632,'ElectricScrewdriver'),true).
clause1(type(localizedText632,localizedText),true).
clause1(reference(listOfReferences12,reference12),true).
clause1(reference(listOfReferences12,reference22),true).
clause1(reference(listOfReferences12,reference32),true).
clause1(reference(listOfReferences12,reference42),true).
clause1(reference(listOfReferences12,reference52),true).
clause1(reference(listOfReferences12,reference62),true).
clause1(type(listOfReferences12,listOfReferences),true).
clause1(hasNodeId(uAObject112,'ns=2;i=40'),true).
clause1(hasBrowseName(uAObject112,'Topology.aml'),true).
clause1(references(uAObject112,listOfReferences112),true).
clause1(displayName(uAObject112,localizedText212),true).
clause1(description(uAObject112,localizedText222),true).
clause1(type(uAObject112,uAObject),true).
clause1(type(anon_1182,anon_1),true).
clause1(hasTextContent(localizedText332,'AdditionalInformation'),true).
clause1(type(localizedText332,localizedText),true).
clause1(hasTextContent(reference722,'FolderType'),true).
clause1(hasReferenceType(reference722,'HasTypeDefinition'),true).
clause1(type(reference722,reference),true).
clause1(hasTextContent(reference1102,'PropertyType'),true).
clause1(hasReferenceType(reference1102,'HasTypeDefinition'),true).
clause1(type(reference1102,reference),true).
clause1(hasTextContent(nodeIdAlias342,'i=47'),true).
clause1(hasAlias(nodeIdAlias342,'HasComponent'),true).
clause1(type(nodeIdAlias342,nodeIdAlias),true).
clause1(type(anon_162,anon_1),true).
clause1(hasParentNodeId(uAVariable152,'ns=2;i=20'),true).
clause1(hasNodeId(uAVariable152,'ns=2;i=22'),true).
clause1(hasDataType(uAVariable152,'String'),true).
clause1(hasBrowseName(uAVariable152,'AdditionalInformation'),true).
clause1(value(uAVariable152,anon_1152),true).
clause1(references(uAVariable152,listOfReferences302),true).
clause1(displayName(uAVariable152,localizedText422),true).
clause1(type(uAVariable152,uAVariable),true).
clause1(hasTextContent(reference422,'ns=2;i=22'),true).
clause1(hasReferenceType(reference422,'HasProperty'),true).
clause1(type(reference422,reference),true).
clause1(reference(listOfReferences412,reference1092),true).
clause1(type(listOfReferences412,listOfReferences),true).
clause1(hasTextContent(reference122,'ns=2;i=31'),true).
clause1(hasReferenceType(reference122,'HasComponent'),true).
clause1(type(reference122,reference),true).
clause1(hasParentNodeId(uAObject82,'ns=2;i=15'),true).
clause1(hasNodeId(uAObject82,'ns=2;i=23'),true).
clause1(hasBrowseName(uAObject82,'EnergySupply'),true).
clause1(references(uAObject82,listOfReferences82),true).
clause1(displayName(uAObject82,localizedText152),true).
clause1(description(uAObject82,localizedText162),true).
clause1(type(uAObject82,uAObject),true).
clause1(reference(listOfReferences112,reference582),true).
clause1(reference(listOfReferences112,reference672),true).
clause1(reference(listOfReferences112,reference662),true).
clause1(reference(listOfReferences112,reference612),true).
clause1(reference(listOfReferences112,reference602),true).
clause1(reference(listOfReferences112,reference632),true).
clause1(type(listOfReferences112,listOfReferences),true).
clause1(reference(listOfReferences112,reference622),true).
clause1(reference(listOfReferences112,reference642),true).
clause1(reference(listOfReferences112,reference652),true).
clause1(reference(listOfReferences112,reference592),true).
clause1(hasTextContent(localizedText452,'ID'),true).
clause1(type(localizedText452,localizedText),true).
clause1(hasTextContent(reference842,'PropertyType'),true).
clause1(hasReferenceType(reference842,'HasTypeDefinition'),true).
clause1(type(reference842,reference),true).
clause1(hasTextContent(reference1222,'ns=1;i=1003'),true).
clause1(hasReferenceType(reference1222,'HasSubtype'),true).
clause1(hasIsForward(reference1222,'false'),true).
clause1(type(reference1222,reference),true).
clause1(hasTextContent(nodeIdAlias12,'i=1'),true).
clause1(hasAlias(nodeIdAlias12,'Boolean'),true).
clause1(type(nodeIdAlias12,nodeIdAlias),true).
clause1(hasTextContent(localizedText152,'EnergySupply'),true).
clause1(type(localizedText152,localizedText),true).
clause1(hasParentNodeId(uAVariable272,'ns=2;i=40'),true).
clause1(hasNodeId(uAVariable272,'ns=2;i=41'),true).
clause1(hasDataType(uAVariable272,'String'),true).
clause1(hasBrowseName(uAVariable272,'AdditionalInformation'),true).
clause1(value(uAVariable272,anon_1272),true).
clause1(references(uAVariable272,listOfReferences422),true).
clause1(displayName(uAVariable272,localizedText552),true).
clause1(type(uAVariable272,uAVariable),true).
clause1(hasTextContent(reference542,'ns=2;i=38'),true).
clause1(hasReferenceType(reference542,'HasProperty'),true).
clause1(type(reference542,reference),true).
clause1(hasTextContent(nodeIdAlias162,'i=16'),true).
clause1(hasAlias(nodeIdAlias162,'XmlElement'),true).
clause1(type(nodeIdAlias162,nodeIdAlias),true).
clause1(hasTextContent(reference242,'ns=2;i=35'),true).
clause1(hasReferenceType(reference242,'HasComponent'),true).
clause1(type(reference242,reference),true).
clause1(reference(listOfReferences232,reference872),true).
clause1(type(listOfReferences232,listOfReferences),true).
clause1(hasTextContent(localizedText572,'BaseRoleClassLib'),true).
clause1(type(localizedText572,localizedText),true).
clause1(hasTextContent(reference962,'PropertyType'),true).
clause1(hasReferenceType(reference962,'HasTypeDefinition'),true).
clause1(type(reference962,reference),true).
clause1(hasTextContent(localizedText272,'AdditionalInformation'),true).
clause1(type(localizedText272,localizedText),true).
clause1(hasNodeId(uAObjectType22,'ns=2;i=33'),true).
clause1(hasBrowseName(uAObjectType22,'Tool'),true).
clause1(references(uAObjectType22,listOfReferences472),true).
clause1(displayName(uAObjectType22,localizedText612),true).
clause1(description(uAObjectType22,localizedText622),true).
clause1(type(uAObjectType22,uAObjectType),true).
clause1(hasTextContent(reference662,'ns=2;i=48'),true).
clause1(hasReferenceType(reference662,'HasComponent'),true).
clause1(type(reference662,reference),true).
clause1(hasTextContent(reference1042,'PropertyType'),true).
clause1(hasReferenceType(reference1042,'HasTypeDefinition'),true).
clause1(type(reference1042,reference),true).
clause1(hasTextContent(nodeIdAlias282,'i=37'),true).
clause1(hasAlias(nodeIdAlias282,'HasModellingRule'),true).
clause1(type(nodeIdAlias282,nodeIdAlias),true).
clause1(hasTextContent(reference362,'ns=2;i=35'),true).
clause1(hasReferenceType(reference362,'HasTypeDefinition'),true).
clause1(type(reference362,reference),true).
clause1(type(anon_1132,anon_1),true).
clause1(reference(listOfReferences352,reference1012),true).
clause1(reference(listOfReferences352,reference1022),true).
clause1(reference(listOfReferences352,reference1032),true).
clause1(type(listOfReferences352,listOfReferences),true).
clause1(reference(listOfReferences72,reference412),true).
clause1(reference(listOfReferences72,reference422),true).
clause1(reference(listOfReferences72,reference432),true).
clause1(reference(listOfReferences72,reference442),true).
clause1(type(listOfReferences72,listOfReferences),true).
clause1(type(anon_112,anon_1),true).
clause1(type(localizedText392,localizedText),true).
clause1(hasParentNodeId(uAVariable102,'ns=2;i=15'),true).
clause1(hasNodeId(uAVariable102,'ns=2;i=16'),true).
clause1(hasDataType(uAVariable102,'String'),true).
clause1(hasBrowseName(uAVariable102,'ID'),true).
clause1(value(uAVariable102,anon_1102),true).
clause1(references(uAVariable102,listOfReferences252),true).
clause1(displayName(uAVariable102,localizedText362),true).
clause1(type(uAVariable102,uAVariable),true).
clause1(hasTextContent(reference782,'FolderType'),true).
clause1(hasReferenceType(reference782,'HasTypeDefinition'),true).
clause1(type(reference782,reference),true).
clause1(hasTextContent(reference1162,'ns=1;i=1003'),true).
clause1(hasReferenceType(reference1162,'HasSubtype'),true).
clause1(hasIsForward(reference1162,'false'),true).
clause1(type(reference1162,reference),true).
clause1(hasNodeId(uAObject32,'ns=2;i=6'),true).
clause1(hasBrowseName(uAObject32,'ManufacturingRoleClasses'),true).
clause1(references(uAObject32,listOfReferences32),true).
clause1(displayName(uAObject32,localizedText52),true).
clause1(description(uAObject32,localizedText62),true).
clause1(type(uAObject32,uAObject),true).
clause1(hasTextContent(reference482,'ns=2;i=31'),true).
clause1(hasReferenceType(reference482,'HasTypeDefinition'),true).
clause1(type(reference482,reference),true).
clause1(type(anon_1252,anon_1),true).
clause1(hasTextContent(reference182,'ns=2;i=33'),true).
clause1(hasReferenceType(reference182,'HasComponent'),true).
clause1(type(reference182,reference),true).
clause1(hasTextContent(localizedText402,'AdditionalInformation'),true).
clause1(type(localizedText402,localizedText),true).
clause1(reference(listOfReferences472,reference1172),true).
clause1(reference(listOfReferences472,reference1182),true).
clause1(reference(listOfReferences472,reference1192),true).
clause1(type(listOfReferences472,listOfReferences),true).
clause1(hasParentNodeId(uAVariable52,'ns=2;i=6'),true).
clause1(hasNodeId(uAVariable52,'ns=2;i=8'),true).
clause1(hasDataType(uAVariable52,'String'),true).
clause1(hasBrowseName(uAVariable52,'AdditionalInformation'),true).
clause1(value(uAVariable52,anon_152),true).
clause1(references(uAVariable52,listOfReferences202),true).
clause1(displayName(uAVariable52,localizedText312),true).
clause1(type(uAVariable52,uAVariable),true).
clause1(hasTextContent(nodeIdAlias412,'i=290'),true).
clause1(hasAlias(nodeIdAlias412,'Duration'),true).
clause1(type(nodeIdAlias412,nodeIdAlias),true).
clause1(reference(listOfReferences172,reference812),true).
clause1(type(listOfReferences172,listOfReferences),true).
clause1(type(localizedText102,localizedText),true).
clause1(type(localizedText62,localizedText),true).
clause1(hasParentNodeId(uAVariable222,'ns=2;i=31'),true).
clause1(hasNodeId(uAVariable222,'ns=2;i=32'),true).
clause1(hasDataType(uAVariable222,'String'),true).
clause1(hasBrowseName(uAVariable222,'AdditionalInformation'),true).
clause1(value(uAVariable222,anon_1222),true).
clause1(references(uAVariable222,listOfReferences372),true).
clause1(displayName(uAVariable222,localizedText502),true).
clause1(type(uAVariable222,uAVariable),true).
clause1(hasTextContent(nodeIdAlias112,'i=11'),true).
clause1(hasAlias(nodeIdAlias112,'Double'),true).
clause1(type(nodeIdAlias112,nodeIdAlias),true).
clause1(hasTextContent(nodeIdAlias72,'i=7'),true).
clause1(hasAlias(nodeIdAlias72,'UInt32'),true).
clause1(type(nodeIdAlias72,nodeIdAlias),true).
clause1(hasTextContent(localizedText522,'AdditionalInformation'),true).
clause1(type(localizedText522,localizedText),true).
clause1(hasTextContent(reference912,'ns=2;i=19'),true).
clause1(hasReferenceType(reference912,'HasProperty'),true).
clause1(type(reference912,reference),true).
clause1(hasTextContent(reference52,'ns=2;i=12'),true).
clause1(hasReferenceType(reference52,'HasComponent'),true).
clause1(type(reference52,reference),true).
clause1(type(localizedText222,localizedText),true).
clause1(reference(listOfReferences292,reference952),true).
clause1(type(listOfReferences292,listOfReferences),true).
clause1(hasTextContent(reference612,'ns=2;i=43'),true).
clause1(hasReferenceType(reference612,'HasProperty'),true).
clause1(type(reference612,reference),true).
clause1(hasTextContent(nodeIdAlias232,'i=26'),true).
clause1(hasAlias(nodeIdAlias232,'Number'),true).
clause1(type(nodeIdAlias232,nodeIdAlias),true).
clause1(hasTextContent(reference312,'ns=2;i=18'),true).
clause1(hasReferenceType(reference312,'HasComponent'),true).
clause1(type(reference312,reference),true).

