clause1(hasTextContent(nodeIdAlias121,'i=13'),true).
clause1(hasAlias(nodeIdAlias121,'DateTime'),true).
clause1(type(nodeIdAlias121,nodeIdAlias),true).
clause1(hasTextContent(nodeIdAlias251,'i=28'),true).
clause1(hasAlias(nodeIdAlias251,'UInteger'),true).
clause1(type(nodeIdAlias251,nodeIdAlias),true).
clause1(hasTextContent(nodeIdAlias41,'i=4'),true).
clause1(hasAlias(nodeIdAlias41,'Int16'),true).
clause1(type(nodeIdAlias41,nodeIdAlias),true).
clause1(hasTextContent(nodeIdAlias321,'i=40'),true).
clause1(hasAlias(nodeIdAlias321,'HasTypeDefinition'),true).
clause1(type(nodeIdAlias321,nodeIdAlias),true).
clause1(hasTextContent(nodeIdAlias171,'i=17'),true).
clause1(hasAlias(nodeIdAlias171,'NodeId'),true).
clause1(type(nodeIdAlias171,nodeIdAlias),true).
clause1(hasTextContent(nodeIdAlias111,'i=11'),true).
clause1(hasAlias(nodeIdAlias111,'Double'),true).
clause1(type(nodeIdAlias111,nodeIdAlias),true).
clause1(hasTextContent(nodeIdAlias91,'i=9'),true).
clause1(hasAlias(nodeIdAlias91,'UInt64'),true).
clause1(type(nodeIdAlias91,nodeIdAlias),true).
clause1(hasTextContent(nodeIdAlias241,'i=27'),true).
clause1(hasAlias(nodeIdAlias241,'Integer'),true).
clause1(type(nodeIdAlias241,nodeIdAlias),true).
clause1(hasTextContent(nodeIdAlias31,'i=3'),true).
clause1(hasAlias(nodeIdAlias31,'Byte'),true).
clause1(type(nodeIdAlias31,nodeIdAlias),true).
clause1(hasTextContent(nodeIdAlias311,'i=45'),true).
clause1(hasAlias(nodeIdAlias311,'HasSubtype'),true).
clause1(type(nodeIdAlias311,nodeIdAlias),true).
clause1(hasTextContent(nodeIdAlias161,'i=16'),true).
clause1(hasAlias(nodeIdAlias161,'XmlElement'),true).
clause1(type(nodeIdAlias161,nodeIdAlias),true).
clause1(hasTextContent(nodeIdAlias291,'i=36'),true).
clause1(hasAlias(nodeIdAlias291,'HasEventSource'),true).
clause1(type(nodeIdAlias291,nodeIdAlias),true).
clause1(hasTextContent(nodeIdAlias101,'i=10'),true).
clause1(hasAlias(nodeIdAlias101,'Float'),true).
clause1(type(nodeIdAlias101,nodeIdAlias),true).
clause1(hasTextContent(nodeIdAlias81,'i=8'),true).
clause1(hasAlias(nodeIdAlias81,'Int64'),true).
clause1(type(nodeIdAlias81,nodeIdAlias),true).
clause1(hasTextContent(nodeIdAlias231,'i=26'),true).
clause1(hasAlias(nodeIdAlias231,'Number'),true).
clause1(type(nodeIdAlias231,nodeIdAlias),true).
clause1(hasUri(uriTable11,'http://opcfoundation.org/UA/AML/'),true).
clause1(hasUri(uriTable11,'http://www.iosb.fraunhofer.de/Topology.aml'),true).
clause1(type(uriTable11,uriTable),true).
clause1(hasTextContent(nodeIdAlias361,'i=290'),true).
clause1(hasAlias(nodeIdAlias361,'Duration'),true).
clause1(type(nodeIdAlias361,nodeIdAlias),true).
clause1(hasTextContent(nodeIdAlias21,'i=2'),true).
clause1(hasAlias(nodeIdAlias21,'SByte'),true).
clause1(type(nodeIdAlias21,nodeIdAlias),true).
clause1(hasTextContent(nodeIdAlias301,'i=48'),true).
clause1(hasAlias(nodeIdAlias301,'HasNotifier'),true).
clause1(type(nodeIdAlias301,nodeIdAlias),true).
clause1(hasTextContent(nodeIdAlias151,'i=14'),true).
clause1(hasAlias(nodeIdAlias151,'Guid'),true).
clause1(type(nodeIdAlias151,nodeIdAlias),true).
clause1(hasTextContent(nodeIdAlias281,'i=35'),true).
clause1(hasAlias(nodeIdAlias281,'Organizes'),true).
clause1(type(nodeIdAlias281,nodeIdAlias),true).
clause1(hasTextContent(nodeIdAlias71,'i=7'),true).
clause1(hasAlias(nodeIdAlias71,'UInt32'),true).
clause1(type(nodeIdAlias71,nodeIdAlias),true).
clause1(hasTextContent(nodeIdAlias221,'i=22'),true).
clause1(hasAlias(nodeIdAlias221,'Structure'),true).
clause1(type(nodeIdAlias221,nodeIdAlias),true).
clause1(hasTextContent(nodeIdAlias351,'i=39'),true).
clause1(hasAlias(nodeIdAlias351,'HasDescription'),true).
clause1(type(nodeIdAlias351,nodeIdAlias),true).
clause1(hasTextContent(nodeIdAlias11,'i=1'),true).
clause1(hasAlias(nodeIdAlias11,'Boolean'),true).
clause1(type(nodeIdAlias11,nodeIdAlias),true).
clause1(namespaceUris(uANodeSet11,uriTable11),true).
clause1(aliases(uANodeSet11,aliasTable11),true).
clause1(type(uANodeSet11,uANodeSet),true).
clause1(alias(aliasTable11,nodeIdAlias101),true).
clause1(alias(aliasTable11,nodeIdAlias51),true).
clause1(alias(aliasTable11,nodeIdAlias271),true).
clause1(type(aliasTable11,aliasTable),true).
clause1(alias(aliasTable11,nodeIdAlias41),true).
clause1(alias(aliasTable11,nodeIdAlias341),true).
clause1(alias(aliasTable11,nodeIdAlias11),true).
clause1(alias(aliasTable11,nodeIdAlias311),true).
clause1(alias(aliasTable11,nodeIdAlias71),true).
clause1(alias(aliasTable11,nodeIdAlias121),true).
clause1(alias(aliasTable11,nodeIdAlias331),true).
clause1(alias(aliasTable11,nodeIdAlias221),true).
clause1(alias(aliasTable11,nodeIdAlias301),true).
clause1(alias(aliasTable11,nodeIdAlias61),true).
clause1(alias(aliasTable11,nodeIdAlias111),true).
clause1(alias(aliasTable11,nodeIdAlias361),true).
clause1(alias(aliasTable11,nodeIdAlias91),true).
clause1(alias(aliasTable11,nodeIdAlias141),true).
clause1(alias(aliasTable11,nodeIdAlias211),true).
clause1(alias(aliasTable11,nodeIdAlias181),true).
clause1(alias(aliasTable11,nodeIdAlias21),true).
clause1(alias(aliasTable11,nodeIdAlias351),true).
clause1(alias(aliasTable11,nodeIdAlias241),true).
clause1(alias(aliasTable11,nodeIdAlias81),true).
clause1(alias(aliasTable11,nodeIdAlias131),true).
clause1(alias(aliasTable11,nodeIdAlias161),true).
clause1(alias(aliasTable11,nodeIdAlias231),true).
clause1(alias(aliasTable11,nodeIdAlias201),true).
clause1(alias(aliasTable11,nodeIdAlias261),true).
clause1(alias(aliasTable11,nodeIdAlias151),true).
clause1(alias(aliasTable11,nodeIdAlias191),true).
clause1(alias(aliasTable11,nodeIdAlias291),true).
clause1(alias(aliasTable11,nodeIdAlias31),true).
clause1(alias(aliasTable11,nodeIdAlias251),true).
clause1(alias(aliasTable11,nodeIdAlias281),true).
clause1(alias(aliasTable11,nodeIdAlias171),true).
clause1(alias(aliasTable11,nodeIdAlias321),true).
clause1(hasTextContent(nodeIdAlias141,'i=15'),true).
clause1(hasAlias(nodeIdAlias141,'ByteString'),true).
clause1(type(nodeIdAlias141,nodeIdAlias),true).
clause1(hasTextContent(nodeIdAlias271,'i=46'),true).
clause1(hasAlias(nodeIdAlias271,'HasProperty'),true).
clause1(type(nodeIdAlias271,nodeIdAlias),true).
clause1(hasTextContent(nodeIdAlias61,'i=6'),true).
clause1(hasAlias(nodeIdAlias61,'Int32'),true).
clause1(type(nodeIdAlias61,nodeIdAlias),true).
clause1(hasTextContent(nodeIdAlias211,'i=19'),true).
clause1(hasAlias(nodeIdAlias211,'StatusCode'),true).
clause1(type(nodeIdAlias211,nodeIdAlias),true).
clause1(hasTextContent(nodeIdAlias341,'i=38'),true).
clause1(hasAlias(nodeIdAlias341,'HasEncoding'),true).
clause1(type(nodeIdAlias341,nodeIdAlias),true).
clause1(hasTextContent(nodeIdAlias191,'i=20'),true).
clause1(hasAlias(nodeIdAlias191,'QualifiedName'),true).
clause1(type(nodeIdAlias191,nodeIdAlias),true).
clause1(hasTextContent(nodeIdAlias131,'i=12'),true).
clause1(hasAlias(nodeIdAlias131,'String'),true).
clause1(type(nodeIdAlias131,nodeIdAlias),true).
clause1(hasTextContent(nodeIdAlias261,'i=47'),true).
clause1(hasAlias(nodeIdAlias261,'HasComponent'),true).
clause1(type(nodeIdAlias261,nodeIdAlias),true).
clause1(hasTextContent(nodeIdAlias51,'i=5'),true).
clause1(hasAlias(nodeIdAlias51,'UInt16'),true).
clause1(type(nodeIdAlias51,nodeIdAlias),true).
clause1(hasTextContent(nodeIdAlias201,'i=21'),true).
clause1(hasAlias(nodeIdAlias201,'LocalizedText'),true).
clause1(type(nodeIdAlias201,nodeIdAlias),true).
clause1(hasTextContent(nodeIdAlias331,'i=37'),true).
clause1(hasAlias(nodeIdAlias331,'HasModellingRule'),true).
clause1(type(nodeIdAlias331,nodeIdAlias),true).
clause1(hasTextContent(nodeIdAlias181,'i=18'),true).
clause1(hasAlias(nodeIdAlias181,'ExpandedNodeId'),true).
clause1(type(nodeIdAlias181,nodeIdAlias),true).
clause1(hasTextContent(reference562,'ns=2;i=6'),true).
clause1(hasReferenceType(reference562,'HasComponent'),true).
clause1(type(reference562,reference),true).
clause1(hasTextContent(reference352,'ns=2;i=8'),true).
clause1(hasReferenceType(reference352,'HasComponent'),true).
clause1(hasIsForward(reference352,'false'),true).
clause1(type(reference352,reference),true).
clause1(hasTextContent(reference142,'ns=2;i=27'),true).
clause1(hasReferenceType(reference142,'HasComponent'),true).
clause1(hasIsForward(reference142,'false'),true).
clause1(type(reference142,reference),true).
clause1(hasTextContent(nodeIdAlias292,'i=36'),true).
clause1(hasAlias(nodeIdAlias292,'HasEventSource'),true).
clause1(type(nodeIdAlias292,nodeIdAlias),true).
clause1(hasTextContent(nodeIdAlias62,'i=6'),true).
clause1(hasAlias(nodeIdAlias62,'Int32'),true).
clause1(type(nodeIdAlias62,nodeIdAlias),true).
clause1(hasTextContent(reference62,'ns=2;i=3'),true).
clause1(hasReferenceType(reference62,'HasProperty'),true).
clause1(type(reference62,reference),true).
clause1(hasTextContent(localizedText12,'ManufacturingSystem'),true).
clause1(type(localizedText12,localizedText),true).
clause1(hasTextContent(localizedText172,'EnergySupply'),true).
clause1(type(localizedText172,localizedText),true).
clause1(hasParentNodeId(uAObject72,'ns=2;i=8'),true).
clause1(hasNodeId(uAObject72,'ns=2;i=13'),true).
clause1(hasBrowseName(uAObject72,'EnergySupply'),true).
clause1(references(uAObject72,listOfReferences72),true).
clause1(displayName(uAObject72,localizedText132),true).
clause1(description(uAObject72,localizedText142),true).
clause1(type(uAObject72,uAObject),true).
clause1(hasTextContent(reference432,'ns=1;i=1005'),true).
clause1(hasReferenceType(reference432,'HasTypeDefinition'),true).
clause1(type(reference432,reference),true).
clause1(hasTextContent(reference222,'ns=2;i=1'),true).
clause1(hasReferenceType(reference222,'HasComponent'),true).
clause1(hasIsForward(reference222,'false'),true).
clause1(type(reference222,reference),true).
clause1(hasTextContent(nodeIdAlias162,'i=16'),true).
clause1(hasAlias(nodeIdAlias162,'XmlElement'),true).
clause1(type(nodeIdAlias162,nodeIdAlias),true).
clause1(hasTextContent(localizedText92,'firstScrewdriver'),true).
clause1(type(localizedText92,localizedText),true).
clause1(hasTextContent(reference512,'ns=2;i=22'),true).
clause1(hasReferenceType(reference512,'HasComponent'),true).
clause1(hasIsForward(reference512,'false'),true).
clause1(type(reference512,reference),true).
clause1(hasTextContent(reference302,'ns=2;i=19'),true).
clause1(hasReferenceType(reference302,'HasTypeDefinition'),true).
clause1(type(reference302,reference),true).
clause1(alias(aliasTable12,nodeIdAlias102),true).
clause1(alias(aliasTable12,nodeIdAlias52),true).
clause1(alias(aliasTable12,nodeIdAlias272),true).
clause1(type(aliasTable12,aliasTable),true).
clause1(alias(aliasTable12,nodeIdAlias42),true).
clause1(alias(aliasTable12,nodeIdAlias342),true).
clause1(alias(aliasTable12,nodeIdAlias12),true).
clause1(alias(aliasTable12,nodeIdAlias312),true).
clause1(alias(aliasTable12,nodeIdAlias72),true).
clause1(alias(aliasTable12,nodeIdAlias122),true).
clause1(alias(aliasTable12,nodeIdAlias332),true).
clause1(alias(aliasTable12,nodeIdAlias222),true).
clause1(alias(aliasTable12,nodeIdAlias302),true).
clause1(alias(aliasTable12,nodeIdAlias62),true).
clause1(alias(aliasTable12,nodeIdAlias112),true).
clause1(alias(aliasTable12,nodeIdAlias362),true).
clause1(alias(aliasTable12,nodeIdAlias92),true).
clause1(alias(aliasTable12,nodeIdAlias142),true).
clause1(alias(aliasTable12,nodeIdAlias212),true).
clause1(alias(aliasTable12,nodeIdAlias182),true).
clause1(alias(aliasTable12,nodeIdAlias22),true).
clause1(alias(aliasTable12,nodeIdAlias352),true).
clause1(alias(aliasTable12,nodeIdAlias242),true).
clause1(alias(aliasTable12,nodeIdAlias82),true).
clause1(alias(aliasTable12,nodeIdAlias132),true).
clause1(alias(aliasTable12,nodeIdAlias162),true).
clause1(alias(aliasTable12,nodeIdAlias232),true).
clause1(alias(aliasTable12,nodeIdAlias202),true).
clause1(alias(aliasTable12,nodeIdAlias262),true).
clause1(alias(aliasTable12,nodeIdAlias152),true).
clause1(alias(aliasTable12,nodeIdAlias192),true).
clause1(alias(aliasTable12,nodeIdAlias292),true).
clause1(alias(aliasTable12,nodeIdAlias32),true).
clause1(alias(aliasTable12,nodeIdAlias252),true).
clause1(alias(aliasTable12,nodeIdAlias282),true).
clause1(alias(aliasTable12,nodeIdAlias172),true).
clause1(alias(aliasTable12,nodeIdAlias322),true).
clause1(hasTextContent(nodeIdAlias242,'i=27'),true).
clause1(hasAlias(nodeIdAlias242,'Integer'),true).
clause1(type(nodeIdAlias242,nodeIdAlias),true).
clause1(reference(listOfReferences82,reference372),true).
clause1(reference(listOfReferences82,reference382),true).
clause1(reference(listOfReferences82,reference392),true).
clause1(type(listOfReferences82,listOfReferences),true).
clause1(hasTextContent(nodeIdAlias12,'i=1'),true).
clause1(hasAlias(nodeIdAlias12,'Boolean'),true).
clause1(type(nodeIdAlias12,nodeIdAlias),true).
clause1(hasTextContent(reference12,'i=61'),true).
clause1(hasReferenceType(reference12,'HasTypeDefinition'),true).
clause1(type(reference12,reference),true).
clause1(reference(listOfReferences102,reference432),true).
clause1(reference(listOfReferences102,reference442),true).
clause1(reference(listOfReferences102,reference452),true).
clause1(reference(listOfReferences102,reference462),true).
clause1(reference(listOfReferences102,reference472),true).
clause1(reference(listOfReferences102,reference482),true).
clause1(reference(listOfReferences102,reference492),true).
clause1(reference(listOfReferences102,reference502),true).
clause1(type(listOfReferences102,listOfReferences),true).
clause1(hasParentNodeId(uAObject132,'ns=2;i=22'),true).
clause1(hasNodeId(uAObject132,'ns=2;i=27'),true).
clause1(hasBrowseName(uAObject132,'RoleClassLibs'),true).
clause1(references(uAObject132,listOfReferences132),true).
clause1(displayName(uAObject132,localizedText232),true).
clause1(type(uAObject132,uAObject),true).
clause1(hasTextContent(reference592,'ns=2;i=4'),true).
clause1(hasReferenceType(reference592,'HasComponent'),true).
clause1(type(reference592,reference),true).
clause1(type(localizedText122,localizedText),true).
clause1(hasNodeId(uAObject22,'ns=2;i=2'),true).
clause1(hasBrowseName(uAObject22,'MyInterfaces'),true).
clause1(references(uAObject22,listOfReferences22),true).
clause1(displayName(uAObject22,localizedText32),true).
clause1(description(uAObject22,localizedText42),true).
clause1(type(uAObject22,uAObject),true).
clause1(hasTextContent(reference382,'ns=2;i=10'),true).
clause1(hasReferenceType(reference382,'HasComponent'),true).
clause1(hasIsForward(reference382,'false'),true).
clause1(type(reference382,reference),true).
clause1(hasTextContent(reference172,'i=61'),true).
clause1(hasReferenceType(reference172,'HasTypeDefinition'),true).
clause1(type(reference172,reference),true).
clause1(hasTextContent(nodeIdAlias322,'i=40'),true).
clause1(hasAlias(nodeIdAlias322,'HasTypeDefinition'),true).
clause1(type(nodeIdAlias322,nodeIdAlias),true).
clause1(hasTextContent(nodeIdAlias92,'i=9'),true).
clause1(hasAlias(nodeIdAlias92,'UInt64'),true).
clause1(type(nodeIdAlias92,nodeIdAlias),true).
clause1(hasTextContent(nodeIdAlias112,'i=11'),true).
clause1(hasAlias(nodeIdAlias112,'Double'),true).
clause1(type(nodeIdAlias112,nodeIdAlias),true).
clause1(hasTextContent(reference92,'ns=2;i=28'),true).
clause1(hasReferenceType(reference92,'HasComponent'),true).
clause1(hasIsForward(reference92,'false'),true).
clause1(type(reference92,reference),true).
clause1(type(localizedText202,localizedText),true).
clause1(type(localizedText42,localizedText),true).
clause1(hasTextContent(reference462,'ns=2;i=25'),true).
clause1(hasReferenceType(reference462,'HasComponent'),true).
clause1(type(reference462,reference),true).
clause1(hasTextContent(reference252,'ns=2;i=18'),true).
clause1(hasReferenceType(reference252,'ns=1;i=4001'),true).
clause1(type(reference252,reference),true).
clause1(reference(listOfReferences32,reference112),true).
clause1(reference(listOfReferences32,reference122),true).
clause1(reference(listOfReferences32,reference132),true).
clause1(reference(listOfReferences32,reference142),true).
clause1(reference(listOfReferences32,reference152),true).
clause1(type(listOfReferences32,listOfReferences),true).
clause1(hasTextContent(nodeIdAlias192,'i=20'),true).
clause1(hasAlias(nodeIdAlias192,'QualifiedName'),true).
clause1(type(nodeIdAlias192,nodeIdAlias),true).
clause1(hasTextContent(reference542,'ns=2;i=22'),true).
clause1(hasReferenceType(reference542,'HasComponent'),true).
clause1(hasIsForward(reference542,'false'),true).
clause1(type(reference542,reference),true).
clause1(hasTextContent(reference332,'ns=2;i=15'),true).
clause1(hasReferenceType(reference332,'HasComponent'),true).
clause1(type(reference332,reference),true).
clause1(hasTextContent(reference122,'i=61'),true).
clause1(hasReferenceType(reference122,'HasTypeDefinition'),true).
clause1(type(reference122,reference),true).
clause1(hasTextContent(nodeIdAlias272,'i=46'),true).
clause1(hasAlias(nodeIdAlias272,'HasProperty'),true).
clause1(type(nodeIdAlias272,nodeIdAlias),true).
clause1(hasTextContent(nodeIdAlias42,'i=4'),true).
clause1(hasAlias(nodeIdAlias42,'Int16'),true).
clause1(type(nodeIdAlias42,nodeIdAlias),true).
clause1(hasTextContent(reference42,'ns=2;i=8'),true).
clause1(hasReferenceType(reference42,'HasComponent'),true).
clause1(type(reference42,reference),true).
clause1(reference(listOfReferences132,reference572),true).
clause1(reference(listOfReferences132,reference582),true).
clause1(reference(listOfReferences132,reference592),true).
clause1(type(listOfReferences132,listOfReferences),true).
clause1(hasTextContent(localizedText152,'EnergySupply'),true).
clause1(type(localizedText152,localizedText),true).
clause1(hasTextContent(reference622,'ns=2;i=2'),true).
clause1(hasReferenceType(reference622,'HasComponent'),true).
clause1(type(reference622,reference),true).
clause1(hasNodeId(uAObject52,'ns=2;i=8'),true).
clause1(hasBrowseName(uAObject52,'firstScrewdriver'),true).
clause1(references(uAObject52,listOfReferences52),true).
clause1(displayName(uAObject52,localizedText92),true).
clause1(description(uAObject52,localizedText102),true).
clause1(type(uAObject52,uAObject),true).
clause1(hasTextContent(reference412,'ns=2;i=19'),true).
clause1(hasReferenceType(reference412,'HasComponent'),true).
clause1(hasIsForward(reference412,'false'),true).
clause1(type(reference412,reference),true).
clause1(hasTextContent(reference202,'ns=2;i=19'),true).
clause1(hasReferenceType(reference202,'ns=1;i=4002'),true).
clause1(type(reference202,reference),true).
clause1(hasTextContent(nodeIdAlias352,'i=39'),true).
clause1(hasAlias(nodeIdAlias352,'HasDescription'),true).
clause1(type(nodeIdAlias352,nodeIdAlias),true).
clause1(hasTextContent(nodeIdAlias142,'i=15'),true).
clause1(hasAlias(nodeIdAlias142,'ByteString'),true).
clause1(type(nodeIdAlias142,nodeIdAlias),true).
clause1(hasUri(uriTable12,'http://opcfoundation.org/UA/AML/'),true).
clause1(hasUri(uriTable12,'http://www.iosb.fraunhofer.de/Topology.aml'),true).
clause1(type(uriTable12,uriTable),true).
clause1(hasTextContent(localizedText232,'RoleClassLibs'),true).
clause1(type(localizedText232,localizedText),true).
clause1(hasTextContent(localizedText72,'LibOfCommonTools'),true).
clause1(type(localizedText72,localizedText),true).
clause1(hasTextContent(reference492,'ns=2;i=28'),true).
clause1(hasReferenceType(reference492,'HasComponent'),true).
clause1(type(reference492,reference),true).
clause1(hasTextContent(reference282,'ns=2;i=11'),true).
clause1(hasReferenceType(reference282,'HasProperty'),true).
clause1(type(reference282,reference),true).
clause1(hasTextContent(nodeIdAlias222,'i=22'),true).
clause1(hasAlias(nodeIdAlias222,'Structure'),true).
clause1(type(nodeIdAlias222,nodeIdAlias),true).
clause1(reference(listOfReferences62,reference282),true).
clause1(reference(listOfReferences62,reference292),true).
clause1(reference(listOfReferences62,reference302),true).
clause1(reference(listOfReferences62,reference312),true).
clause1(reference(listOfReferences62,reference322),true).
clause1(reference(listOfReferences62,reference332),true).
clause1(type(listOfReferences62,listOfReferences),true).
clause1(hasParentNodeId(uAObject112,'ns=2;i=22'),true).
clause1(hasNodeId(uAObject112,'ns=2;i=25'),true).
clause1(hasBrowseName(uAObject112,'InstanceHierarchies'),true).
clause1(references(uAObject112,listOfReferences112),true).
clause1(displayName(uAObject112,localizedText212),true).
clause1(type(uAObject112,uAObject),true).
clause1(type(localizedText102,localizedText),true).
clause1(hasTextContent(reference572,'ns=2;i=22'),true).
clause1(hasReferenceType(reference572,'HasComponent'),true).
clause1(hasIsForward(reference572,'false'),true).
clause1(type(reference572,reference),true).
clause1(hasTextContent(reference362,'ns=2;i=17'),true).
clause1(hasReferenceType(reference362,'HasTypeDefinition'),true).
clause1(type(reference362,reference),true).
clause1(hasTextContent(reference152,'ns=2;i=18'),true).
clause1(hasReferenceType(reference152,'ns=1;i=4002'),true).
clause1(type(reference152,reference),true).
clause1(hasTextContent(nodeIdAlias302,'i=48'),true).
clause1(hasAlias(nodeIdAlias302,'HasNotifier'),true).
clause1(type(nodeIdAlias302,nodeIdAlias),true).
clause1(hasTextContent(nodeIdAlias72,'i=7'),true).
clause1(hasAlias(nodeIdAlias72,'UInt32'),true).
clause1(type(nodeIdAlias72,nodeIdAlias),true).
clause1(hasTextContent(reference72,'i=61'),true).
clause1(hasReferenceType(reference72,'HasTypeDefinition'),true).
clause1(type(reference72,reference),true).
clause1(hasParentNodeId(uAObject82,'ns=2;i=10'),true).
clause1(hasNodeId(uAObject82,'ns=2;i=15'),true).
clause1(hasBrowseName(uAObject82,'EnergySupply'),true).
clause1(references(uAObject82,listOfReferences82),true).
clause1(displayName(uAObject82,localizedText152),true).
clause1(description(uAObject82,localizedText162),true).
clause1(type(uAObject82,uAObject),true).
clause1(type(localizedText182,localizedText),true).
clause1(type(localizedText22,localizedText),true).
clause1(hasTextContent(reference442,'ns=2;i=23'),true).
clause1(hasReferenceType(reference442,'HasProperty'),true).
clause1(type(reference442,reference),true).
clause1(hasTextContent(reference232,'ns=2;i=19'),true).
clause1(hasReferenceType(reference232,'HasTypeDefinition'),true).
clause1(type(reference232,reference),true).
clause1(reference(listOfReferences12,reference12),true).
clause1(reference(listOfReferences12,reference22),true).
clause1(reference(listOfReferences12,reference32),true).
clause1(reference(listOfReferences12,reference42),true).
clause1(reference(listOfReferences12,reference52),true).
clause1(type(listOfReferences12,listOfReferences),true).
clause1(hasTextContent(nodeIdAlias172,'i=17'),true).
clause1(hasAlias(nodeIdAlias172,'NodeId'),true).
clause1(type(nodeIdAlias172,nodeIdAlias),true).
clause1(hasTextContent(reference522,'i=61'),true).
clause1(hasReferenceType(reference522,'HasTypeDefinition'),true).
clause1(type(reference522,reference),true).
clause1(hasTextContent(reference312,'ns=2;i=18'),true).
clause1(hasReferenceType(reference312,'ns=1;i=4001'),true).
clause1(type(reference312,reference),true).
clause1(hasTextContent(reference102,'ns=2;i=17'),true).
clause1(hasReferenceType(reference102,'ns=1;i=4002'),true).
clause1(type(reference102,reference),true).
clause1(reference(listOfReferences92,reference402),true).
clause1(reference(listOfReferences92,reference412),true).
clause1(reference(listOfReferences92,reference422),true).
clause1(type(listOfReferences92,listOfReferences),true).
clause1(hasTextContent(nodeIdAlias252,'i=28'),true).
clause1(hasAlias(nodeIdAlias252,'UInteger'),true).
clause1(type(nodeIdAlias252,nodeIdAlias),true).
clause1(hasTextContent(nodeIdAlias22,'i=2'),true).
clause1(hasAlias(nodeIdAlias22,'SByte'),true).
clause1(type(nodeIdAlias22,nodeIdAlias),true).
clause1(hasTextContent(reference22,'ns=1;i=5005'),true).
clause1(hasReferenceType(reference22,'Organizes'),true).
clause1(hasIsForward(reference22,'false'),true).
clause1(type(reference22,reference),true).
clause1(reference(listOfReferences112,reference512),true).
clause1(reference(listOfReferences112,reference522),true).
clause1(reference(listOfReferences112,reference532),true).
clause1(type(listOfReferences112,listOfReferences),true).
clause1(hasParentNodeId(uAObject142,'ns=2;i=22'),true).
clause1(hasNodeId(uAObject142,'ns=2;i=28'),true).
clause1(hasBrowseName(uAObject142,'InterfaceClassLibs'),true).
clause1(references(uAObject142,listOfReferences142),true).
clause1(displayName(uAObject142,localizedText242),true).
clause1(type(uAObject142,uAObject),true).
clause1(hasTextContent(localizedText132,'EnergySupply'),true).
clause1(type(localizedText132,localizedText),true).
clause1(hasTextContent(reference602,'ns=2;i=22'),true).
clause1(hasReferenceType(reference602,'HasComponent'),true).
clause1(hasIsForward(reference602,'false'),true).
clause1(type(reference602,reference),true).
clause1(hasNodeId(uAObject32,'ns=2;i=4'),true).
clause1(hasBrowseName(uAObject32,'ManufacturingRoleClasses'),true).
clause1(references(uAObject32,listOfReferences32),true).
clause1(displayName(uAObject32,localizedText52),true).
clause1(description(uAObject32,localizedText62),true).
clause1(type(uAObject32,uAObject),true).
clause1(hasTextContent(reference392,'ns=2;i=17'),true).
clause1(hasReferenceType(reference392,'HasTypeDefinition'),true).
clause1(type(reference392,reference),true).
clause1(hasTextContent(reference182,'ns=1;i=5010'),true).
clause1(hasReferenceType(reference182,'Organizes'),true).
clause1(hasIsForward(reference182,'false'),true).
clause1(type(reference182,reference),true).
clause1(hasTextContent(nodeIdAlias332,'i=37'),true).
clause1(hasAlias(nodeIdAlias332,'HasModellingRule'),true).
clause1(type(nodeIdAlias332,nodeIdAlias),true).
clause1(hasTextContent(nodeIdAlias122,'i=13'),true).
clause1(hasAlias(nodeIdAlias122,'DateTime'),true).
clause1(type(nodeIdAlias122,nodeIdAlias),true).
clause1(hasTextContent(localizedText212,'InstanceHierarchies'),true).
clause1(type(localizedText212,localizedText),true).
clause1(hasTextContent(localizedText52,'ManufacturingRoleClasses'),true).
clause1(type(localizedText52,localizedText),true).
clause1(hasTextContent(reference472,'ns=2;i=26'),true).
clause1(hasReferenceType(reference472,'HasComponent'),true).
clause1(type(reference472,reference),true).
clause1(hasTextContent(reference262,'ns=2;i=12'),true).
clause1(hasReferenceType(reference262,'HasComponent'),true).
clause1(type(reference262,reference),true).
clause1(hasTextContent(nodeIdAlias202,'i=21'),true).
clause1(hasAlias(nodeIdAlias202,'LocalizedText'),true).
clause1(type(nodeIdAlias202,nodeIdAlias),true).
clause1(reference(listOfReferences42,reference162),true).
clause1(reference(listOfReferences42,reference172),true).
clause1(reference(listOfReferences42,reference182),true).
clause1(reference(listOfReferences42,reference192),true).
clause1(reference(listOfReferences42,reference202),true).
clause1(type(listOfReferences42,listOfReferences),true).
clause1(hasTextContent(reference552,'i=61'),true).
clause1(hasReferenceType(reference552,'HasTypeDefinition'),true).
clause1(type(reference552,reference),true).
clause1(hasTextContent(reference342,'ns=2;i=14'),true).
clause1(hasReferenceType(reference342,'HasProperty'),true).
clause1(type(reference342,reference),true).
clause1(hasTextContent(reference132,'ns=1;i=5009'),true).
clause1(hasReferenceType(reference132,'Organizes'),true).
clause1(hasIsForward(reference132,'false'),true).
clause1(type(reference132,reference),true).
clause1(hasTextContent(nodeIdAlias282,'i=35'),true).
clause1(hasAlias(nodeIdAlias282,'Organizes'),true).
clause1(type(nodeIdAlias282,nodeIdAlias),true).
clause1(hasTextContent(nodeIdAlias52,'i=5'),true).
clause1(hasAlias(nodeIdAlias52,'UInt16'),true).
clause1(type(nodeIdAlias52,nodeIdAlias),true).
clause1(hasTextContent(reference52,'ns=2;i=10'),true).
clause1(hasReferenceType(reference52,'HasComponent'),true).
clause1(type(reference52,reference),true).
clause1(reference(listOfReferences142,reference602),true).
clause1(reference(listOfReferences142,reference612),true).
clause1(reference(listOfReferences142,reference622),true).
clause1(type(listOfReferences142,listOfReferences),true).
clause1(type(localizedText162,localizedText),true).
clause1(hasNodeId(uAObject62,'ns=2;i=10'),true).
clause1(hasBrowseName(uAObject62,'secondScrewdriver'),true).
clause1(references(uAObject62,listOfReferences62),true).
clause1(displayName(uAObject62,localizedText112),true).
clause1(description(uAObject62,localizedText122),true).
clause1(type(uAObject62,uAObject),true).
clause1(hasTextContent(reference422,'ns=2;i=17'),true).
clause1(hasReferenceType(reference422,'HasTypeDefinition'),true).
clause1(type(reference422,reference),true).
clause1(hasTextContent(reference212,'ns=2;i=9'),true).
clause1(hasReferenceType(reference212,'HasProperty'),true).
clause1(type(reference212,reference),true).
clause1(hasTextContent(nodeIdAlias362,'i=290'),true).
clause1(hasAlias(nodeIdAlias362,'Duration'),true).
clause1(type(nodeIdAlias362,nodeIdAlias),true).
clause1(hasTextContent(nodeIdAlias152,'i=14'),true).
clause1(hasAlias(nodeIdAlias152,'Guid'),true).
clause1(type(nodeIdAlias152,nodeIdAlias),true).
clause1(hasTextContent(localizedText242,'InterfaceClassLibs'),true).
clause1(type(localizedText242,localizedText),true).
clause1(type(localizedText82,localizedText),true).
clause1(hasTextContent(reference502,'ns=1;i=5006'),true).
clause1(hasReferenceType(reference502,'Organizes'),true).
clause1(hasIsForward(reference502,'false'),true).
clause1(type(reference502,reference),true).
clause1(hasTextContent(reference292,'ns=2;i=1'),true).
clause1(hasReferenceType(reference292,'HasComponent'),true).
clause1(hasIsForward(reference292,'false'),true).
clause1(type(reference292,reference),true).
clause1(hasTextContent(nodeIdAlias232,'i=26'),true).
clause1(hasAlias(nodeIdAlias232,'Number'),true).
clause1(type(nodeIdAlias232,nodeIdAlias),true).
clause1(reference(listOfReferences72,reference342),true).
clause1(reference(listOfReferences72,reference352),true).
clause1(reference(listOfReferences72,reference362),true).
clause1(type(listOfReferences72,listOfReferences),true).
clause1(hasParentNodeId(uAObject122,'ns=2;i=22'),true).
clause1(hasNodeId(uAObject122,'ns=2;i=26'),true).
clause1(hasBrowseName(uAObject122,'SystemUnitClassLibs'),true).
clause1(references(uAObject122,listOfReferences122),true).
clause1(displayName(uAObject122,localizedText222),true).
clause1(type(uAObject122,uAObject),true).
clause1(hasTextContent(reference582,'i=61'),true).
clause1(hasReferenceType(reference582,'HasTypeDefinition'),true).
clause1(type(reference582,reference),true).
clause1(hasTextContent(localizedText112,'secondScrewdriver'),true).
clause1(type(localizedText112,localizedText),true).
clause1(hasNodeId(uAObject12,'ns=2;i=1'),true).
clause1(hasBrowseName(uAObject12,'ManufacturingSystem'),true).
clause1(references(uAObject12,listOfReferences12),true).
clause1(displayName(uAObject12,localizedText12),true).
clause1(description(uAObject12,localizedText22),true).
clause1(type(uAObject12,uAObject),true).
clause1(hasTextContent(reference372,'ns=2;i=16'),true).
clause1(hasReferenceType(reference372,'HasProperty'),true).
clause1(type(reference372,reference),true).
clause1(hasTextContent(reference162,'ns=2;i=7'),true).
clause1(hasReferenceType(reference162,'HasProperty'),true).
clause1(type(reference162,reference),true).
clause1(hasTextContent(nodeIdAlias312,'i=45'),true).
clause1(hasAlias(nodeIdAlias312,'HasSubtype'),true).
clause1(type(nodeIdAlias312,nodeIdAlias),true).
clause1(hasTextContent(nodeIdAlias82,'i=8'),true).
clause1(hasAlias(nodeIdAlias82,'Int64'),true).
clause1(type(nodeIdAlias82,nodeIdAlias),true).
clause1(hasTextContent(nodeIdAlias102,'i=10'),true).
clause1(hasAlias(nodeIdAlias102,'Float'),true).
clause1(type(nodeIdAlias102,nodeIdAlias),true).
clause1(hasTextContent(reference82,'ns=1;i=5008'),true).
clause1(hasReferenceType(reference82,'Organizes'),true).
clause1(hasIsForward(reference82,'false'),true).
clause1(type(reference82,reference),true).
clause1(hasTextContent(localizedText192,'Topology.aml'),true).
clause1(type(localizedText192,localizedText),true).
clause1(hasParentNodeId(uAObject92,'ns=2;i=19'),true).
clause1(hasNodeId(uAObject92,'ns=2;i=20'),true).
clause1(hasBrowseName(uAObject92,'EnergySupply'),true).
clause1(references(uAObject92,listOfReferences92),true).
clause1(displayName(uAObject92,localizedText172),true).
clause1(description(uAObject92,localizedText182),true).
clause1(type(uAObject92,uAObject),true).
clause1(hasTextContent(localizedText32,'MyInterfaces'),true).
clause1(type(localizedText32,localizedText),true).
clause1(hasTextContent(reference452,'ns=2;i=24'),true).
clause1(hasReferenceType(reference452,'HasProperty'),true).
clause1(type(reference452,reference),true).
clause1(hasTextContent(reference242,'ns=2;i=18'),true).
clause1(hasReferenceType(reference242,'ns=1;i=4001'),true).
clause1(type(reference242,reference),true).
clause1(reference(listOfReferences22,reference62),true).
clause1(reference(listOfReferences22,reference72),true).
clause1(reference(listOfReferences22,reference82),true).
clause1(reference(listOfReferences22,reference92),true).
clause1(reference(listOfReferences22,reference102),true).
clause1(type(listOfReferences22,listOfReferences),true).
clause1(hasTextContent(nodeIdAlias182,'i=18'),true).
clause1(hasAlias(nodeIdAlias182,'ExpandedNodeId'),true).
clause1(type(nodeIdAlias182,nodeIdAlias),true).
clause1(hasTextContent(reference532,'ns=2;i=1'),true).
clause1(hasReferenceType(reference532,'HasComponent'),true).
clause1(type(reference532,reference),true).
clause1(hasTextContent(reference322,'ns=2;i=18'),true).
clause1(hasReferenceType(reference322,'ns=1;i=4001'),true).
clause1(type(reference322,reference),true).
clause1(hasTextContent(reference112,'ns=2;i=5'),true).
clause1(hasReferenceType(reference112,'HasProperty'),true).
clause1(type(reference112,reference),true).
clause1(hasTextContent(nodeIdAlias262,'i=47'),true).
clause1(hasAlias(nodeIdAlias262,'HasComponent'),true).
clause1(type(nodeIdAlias262,nodeIdAlias),true).
clause1(hasTextContent(nodeIdAlias32,'i=3'),true).
clause1(hasAlias(nodeIdAlias32,'Byte'),true).
clause1(type(nodeIdAlias32,nodeIdAlias),true).
clause1(hasTextContent(reference32,'ns=2;i=25'),true).
clause1(hasReferenceType(reference32,'HasComponent'),true).
clause1(hasIsForward(reference32,'false'),true).
clause1(type(reference32,reference),true).
clause1(reference(listOfReferences122,reference542),true).
clause1(reference(listOfReferences122,reference552),true).
clause1(reference(listOfReferences122,reference562),true).
clause1(type(listOfReferences122,listOfReferences),true).
clause1(type(localizedText142,localizedText),true).
clause1(hasTextContent(reference612,'i=61'),true).
clause1(hasReferenceType(reference612,'HasTypeDefinition'),true).
clause1(type(reference612,reference),true).
clause1(hasNodeId(uAObject42,'ns=2;i=6'),true).
clause1(hasBrowseName(uAObject42,'LibOfCommonTools'),true).
clause1(references(uAObject42,listOfReferences42),true).
clause1(displayName(uAObject42,localizedText72),true).
clause1(description(uAObject42,localizedText82),true).
clause1(type(uAObject42,uAObject),true).
clause1(hasTextContent(reference402,'ns=2;i=21'),true).
clause1(hasReferenceType(reference402,'HasProperty'),true).
clause1(type(reference402,reference),true).
clause1(hasTextContent(reference192,'ns=2;i=26'),true).
clause1(hasReferenceType(reference192,'HasComponent'),true).
clause1(hasIsForward(reference192,'false'),true).
clause1(type(reference192,reference),true).
clause1(hasTextContent(nodeIdAlias342,'i=38'),true).
clause1(hasAlias(nodeIdAlias342,'HasEncoding'),true).
clause1(type(nodeIdAlias342,nodeIdAlias),true).
clause1(hasTextContent(nodeIdAlias132,'i=12'),true).
clause1(hasAlias(nodeIdAlias132,'String'),true).
clause1(type(nodeIdAlias132,nodeIdAlias),true).
clause1(uAObject(uANodeSet12,uAObject32),true).
clause1(uAObject(uANodeSet12,uAObject92),true).
clause1(type(uANodeSet12,uANodeSet),true).
clause1(uAObject(uANodeSet12,uAObject22),true).
clause1(uAObject(uANodeSet12,uAObject142),true).
clause1(uAObject(uANodeSet12,uAObject12),true).
clause1(uAObject(uANodeSet12,uAObject82),true).
clause1(uAObject(uANodeSet12,uAObject72),true).
clause1(uAObject(uANodeSet12,uAObject132),true).
clause1(uAObject(uANodeSet12,uAObject122),true).
clause1(uAObject(uANodeSet12,uAObject62),true).
clause1(uAObject(uANodeSet12,uAObject52),true).
clause1(aliases(uANodeSet12,aliasTable12),true).
clause1(uAObject(uANodeSet12,uAObject112),true).
clause1(uAObject(uANodeSet12,uAObject102),true).
clause1(uAObject(uANodeSet12,uAObject42),true).
clause1(namespaceUris(uANodeSet12,uriTable12),true).
clause1(hasTextContent(localizedText222,'SystemUnitClassLibs'),true).
clause1(type(localizedText222,localizedText),true).
clause1(type(localizedText62,localizedText),true).
clause1(hasTextContent(reference482,'ns=2;i=27'),true).
clause1(hasReferenceType(reference482,'HasComponent'),true).
clause1(type(reference482,reference),true).
clause1(hasTextContent(reference272,'ns=2;i=13'),true).
clause1(hasReferenceType(reference272,'HasComponent'),true).
clause1(type(reference272,reference),true).
clause1(hasTextContent(nodeIdAlias212,'i=19'),true).
clause1(hasAlias(nodeIdAlias212,'StatusCode'),true).
clause1(type(nodeIdAlias212,nodeIdAlias),true).
clause1(reference(listOfReferences52,reference212),true).
clause1(reference(listOfReferences52,reference222),true).
clause1(reference(listOfReferences52,reference232),true).
clause1(reference(listOfReferences52,reference242),true).
clause1(reference(listOfReferences52,reference252),true).
clause1(reference(listOfReferences52,reference262),true).
clause1(reference(listOfReferences52,reference272),true).
clause1(type(listOfReferences52,listOfReferences),true).
clause1(hasNodeId(uAObject102,'ns=2;i=22'),true).
clause1(hasBrowseName(uAObject102,'Topology.aml'),true).
clause1(references(uAObject102,listOfReferences102),true).
clause1(displayName(uAObject102,localizedText192),true).
clause1(description(uAObject102,localizedText202),true).
clause1(type(uAObject102,uAObject),true).

