clause1(refBaseClassPath(externalReference11,'Libs/RoleClass Libraries/AutomationMLBaseRoleClassLib.aml'),true).
clause1(externalReferenceAlias(externalReference11,'BaseRoleClassLib'),true).
clause1(type(externalReference11,externalReference),true).
clause1(hasInternalElement(instanceHierarchy11,internalElement11),true).
clause1(hasAttributeName(instanceHierarchy11,'MechatronicEngineering'),true).
clause1(type(instanceHierarchy11,instanceHierarchy),true).
clause1(hasRefSemantic(attribute11,refSemantic11),true).
clause1(hasAttributeValue(attribute11,'35.00'),true).
clause1(hasAttributeName(attribute11,'length'),true).
clause1(hasDataType(attribute11,'xs:integer'),true).
clause1(type(attribute11,attribute),true).
clause1(hasInstanceHierarchy(cAEXFile11,instanceHierarchy11),true).
clause1(hasExternalReference(cAEXFile11,externalReference21),true).
clause1(hasExternalReference(cAEXFile11,externalReference11),true).
clause1(hasAdditionalInfomation(cAEXFile11,additionalInformation21),true).
clause1(hasAdditionalInfomation(cAEXFile11,additionalInformation11),true).
clause1(hasSchemaVersion(cAEXFile11,'2.15'),true).
clause1(hasFileName(cAEXFile11,'seed-Datatype-0.aml'),true).
clause1(type(cAEXFile11,cAEXFile),true).
clause1(hasWriterID(additionalInformation21,'AutomationML e.V.'),true).
clause1(hasWriterRelease(additionalInformation21,'1.0'),true).
clause1(hasWriterProjectID(additionalInformation21,'AutomationML Tutorial Examples
			'),true).
clause1(hasWriterVendorURL(additionalInformation21,'www.AutomationML.org'),true).
clause1(hasLastWritingDateTime(additionalInformation21,'2012-02-20
			'),true).
clause1(hasWriterName(additionalInformation21,'AutomationML e.V.'),true).
clause1(type(additionalInformation21,additionalInformation),true).
clause1(hasWriterProjectTitle(additionalInformation21,'AutomationML Tutorial Examples'),true).
clause1(hasWriterVersion(additionalInformation21,'1.0'),true).
clause1(hasWriterVendor(additionalInformation21,'AutomationML e.V.'),true).
clause1(refBaseClassPath(externalReference21,'Libs/InterfaceClass Libraries/AutomationMLInterfaceClassLib.aml'),true).
clause1(externalReferenceAlias(externalReference21,'BaseInterfaceClassLib'),true).
clause1(type(externalReference21,externalReference),true).
clause1(hasAttribute(internalElement11,attribute11),true).
clause1(refBaseSystemUnitPath(internalElement11,''),true).
clause1(hasAttributeName(internalElement11,'AMLObject'),true).
clause1(identifier(internalElement11,'74d0c8ef-ab53-462a-8225-306ed22dc0f3'),true).
clause1(type(internalElement11,internalElement),true).
clause1(hasCorrespondingAttributePath(refSemantic11,'NE 150 v1.0 Annex 1.1.5'),true).
clause1(type(refSemantic11,refSemantic),true).
clause1(hasAutomationMLVersion(additionalInformation11,'2.0'),true).
clause1(type(additionalInformation11,additionalInformation),true).
clause1(type(value72,value),true).
clause1(hasValue(uAVariable32,value32),true).
clause1(hasReferences(uAVariable32,references72),true).
clause1(hasDisplayName(uAVariable32,'AdditionalInformation'),true).
clause1(parentNodeId(uAVariable32,'ns=2;i=12'),true).
clause1(hasNodeId(uAVariable32,'ns=2;i=14'),true).
clause1(hasDataType(uAVariable32,'String'),true).
clause1(hasBrowseName(uAVariable32,'AdditionalInformation'),true).
clause1(type(uAVariable32,uAVariable),true).
clause1(hasValue(references142,'PropertyType'),true).
clause1(type(references142,references),true).
clause1(type(value12,value),true).
clause1(hasValue(references82,'ns=2;i=6012'),true).
clause1(hasValue(references82,'ns=2;i=12'),true).
clause1(hasValue(references82,'ns=1;i=3007'),true).
clause1(hasValue(references82,'ns=2;i=19'),true).
clause1(type(references82,references),true).
clause1(hasValue(references22,'ns=2;i=18'),true).
clause1(hasValue(references22,'ns=2;i=14'),true).
clause1(hasValue(references22,'ns=2;i=13'),true).
clause1(type(references22,references),true).
clause1(hasValue(uAVariable82,value82),true).
clause1(hasReferences(uAVariable82,references122),true).
clause1(hasDisplayName(uAVariable82,'SchemaVersion'),true).
clause1(parentNodeId(uAVariable82,'ns=2;i=40'),true).
clause1(hasNodeId(uAVariable82,'ns=2;i=42'),true).
clause1(hasDataType(uAVariable82,'String'),true).
clause1(hasBrowseName(uAVariable82,'SchemaVersion'),true).
clause1(type(uAVariable82,uAVariable),true).
clause1(hasString(value102,'Libs/InterfaceClass Libraries/AutomationMLInterfaceClassLib.aml'),true).
clause1(type(value102,value),true).
clause1(type(value62,value),true).
clause1(hasValue(uAVariable22,value22),true).
clause1(hasReferences(uAVariable22,references62),true).
clause1(hasDisplayName(uAVariable22,'ID'),true).
clause1(parentNodeId(uAVariable22,'ns=2;i=12'),true).
clause1(hasNodeId(uAVariable22,'ns=2;i=13'),true).
clause1(hasDataType(uAVariable22,'String'),true).
clause1(hasBrowseName(uAVariable22,'ID'),true).
clause1(type(uAVariable22,uAVariable),true).
clause1(hasValue(references132,'PropertyType'),true).
clause1(type(references132,references),true).
clause1(hasValue(references72,'PropertyType'),true).
clause1(type(references72,references),true).
clause1(hasReferences(uAObject42,references42),true).
clause1(hasNodeId(uAObject42,'ns=2;i=45'),true).
clause1(hasBrowseName(uAObject42,'InstanceHierarchies'),true).
clause1(type(uAObject42,uAObject),true).
clause1(hasValue(references12,'ns=2;i=12'),true).
clause1(hasValue(references12,'ns=2;i=45'),true).
clause1(hasValue(references12,'ns=1;i=5002'),true).
clause1(hasValue(references12,'FolderType'),true).
clause1(hasValue(references12,'ns=2;i=2'),true).
clause1(type(references12,references),true).
clause1(hasValue(uAVariable72,value72),true).
clause1(hasReferences(uAVariable72,references112),true).
clause1(hasDisplayName(uAVariable72,'AdditionalInformation'),true).
clause1(parentNodeId(uAVariable72,'ns=2;i=40'),true).
clause1(hasNodeId(uAVariable72,'ns=2;i=41'),true).
clause1(hasDataType(uAVariable72,'String'),true).
clause1(hasBrowseName(uAVariable72,'AdditionalInformation'),true).
clause1(type(uAVariable72,uAVariable),true).
clause1(hasString(value52,'NE 150 v1.0 Annex 1.1.5'),true).
clause1(type(value52,value),true).
clause1(hasValue(uAVariable12,value12),true).
clause1(hasReferences(uAVariable12,references52),true).
clause1(hasDisplayName(uAVariable12,'AdditionalInformation'),true).
clause1(parentNodeId(uAVariable12,'ns=2;i=1'),true).
clause1(hasNodeId(uAVariable12,'ns=2;i=2'),true).
clause1(hasDataType(uAVariable12,'String'),true).
clause1(hasBrowseName(uAVariable12,'AdditionalInformation'),true).
clause1(type(uAVariable12,uAVariable),true).
clause1(hasValue(references122,'PropertyType'),true).
clause1(type(references122,references),true).
clause1(hasValue(references62,'PropertyType'),true).
clause1(type(references62,references),true).
clause1(hasReferences(uAObject32,references32),true).
clause1(hasNodeId(uAObject32,'ns=2;i=40'),true).
clause1(hasBrowseName(uAObject32,'seed-Datatype-0.aml'),true).
clause1(type(uAObject32,uAObject),true).
clause1(hasValue(uAVariable62,value62),true).
clause1(hasReferences(uAVariable62,references102),true).
clause1(hasDisplayName(uAVariable62,'AdditionalInformation'),true).
clause1(parentNodeId(uAVariable62,'ns=2;i=18'),true).
clause1(hasNodeId(uAVariable62,'ns=2;i=19'),true).
clause1(hasDataType(uAVariable62,'String'),true).
clause1(hasBrowseName(uAVariable62,'AdditionalInformation'),true).
clause1(type(uAVariable62,uAVariable),true).
clause1(hasString(value42,'35.0'),true).
clause1(type(value42,value),true).
clause1(hasValue(uAVariable102,value102),true).
clause1(hasReferences(uAVariable102,references142),true).
clause1(hasDisplayName(uAVariable102,'BaseInterfaceClassLib'),true).
clause1(parentNodeId(uAVariable102,'ns=2;i=40'),true).
clause1(hasNodeId(uAVariable102,'ns=2;i=44'),true).
clause1(hasDataType(uAVariable102,'String'),true).
clause1(hasBrowseName(uAVariable102,'BaseInterfaceClassLib'),true).
clause1(type(uAVariable102,uAVariable),true).
clause1(hasValue(references112,'PropertyType'),true).
clause1(type(references112,references),true).
clause1(hasValue(references52,'PropertyType'),true).
clause1(type(references52,references),true).
clause1(hasReferences(uAObject22,references22),true).
clause1(hasNodeId(uAObject22,'ns=2;i=12'),true).
clause1(hasBrowseName(uAObject22,'AMLObject'),true).
clause1(type(uAObject22,uAObject),true).
clause1(type(aliases12,aliases),true).
clause1(hasString(value92,'Libs/RoleClass Libraries/AutomationMLBaseRoleClassLib.aml'),true).
clause1(type(value92,value),true).
clause1(hasValue(uAVariable52,value52),true).
clause1(hasReferences(uAVariable52,references92),true).
clause1(hasDisplayName(uAVariable52,'RefSemantic'),true).
clause1(parentNodeId(uAVariable52,'ns=2;i=18'),true).
clause1(hasNodeId(uAVariable52,'ns=2;i=6012'),true).
clause1(hasDataType(uAVariable52,'String'),true).
clause1(hasBrowseName(uAVariable52,'RefSemantic'),true).
clause1(type(uAVariable52,uAVariable),true).
clause1(hasUAVariable(uANodeSet12,uAVariable92),true).
clause1(hasAliases(uANodeSet12,aliases12),true).
clause1(hasUAVariable(uANodeSet12,uAVariable52),true).
clause1(hasUAObject(uANodeSet12,uAObject42),true).
clause1(type(uANodeSet12,uANodeSet),true).
clause1(hasUAVariable(uANodeSet12,uAVariable102),true).
clause1(hasUAObject(uANodeSet12,uAObject22),true).
clause1(hasUAObject(uANodeSet12,uAObject12),true).
clause1(hasUAVariable(uANodeSet12,uAVariable22),true).
clause1(hasUAVariable(uANodeSet12,uAVariable82),true).
clause1(hasUAObject(uANodeSet12,uAObject32),true).
clause1(hasUAVariable(uANodeSet12,uAVariable72),true).
clause1(hasUAVariable(uANodeSet12,uAVariable42),true).
clause1(hasUAVariable(uANodeSet12,uAVariable12),true).
clause1(hasNamespaceUris(uANodeSet12,namespaceUris12),true).
clause1(hasUAVariable(uANodeSet12,uAVariable62),true).
clause1(hasUAVariable(uANodeSet12,uAVariable32),true).
clause1(type(value32,value),true).
clause1(hasValue(references102,'PropertyType'),true).
clause1(type(references102,references),true).
clause1(hasValue(references42,'ns=2;i=1'),true).
clause1(hasValue(references42,'FolderType'),true).
clause1(hasValue(references42,'ns=2;i=40'),true).
clause1(type(references42,references),true).
clause1(hasReferences(uAObject12,references12),true).
clause1(hasNodeId(uAObject12,'ns=2;i=1'),true).
clause1(hasBrowseName(uAObject12,'MechatronicEngineering'),true).
clause1(type(uAObject12,uAObject),true).
clause1(hasString(value82,'2.15'),true).
clause1(type(value82,value),true).
clause1(hasValue(uAVariable42,value42),true).
clause1(hasReferences(uAVariable42,references82),true).
clause1(hasDisplayName(uAVariable42,'length'),true).
clause1(parentNodeId(uAVariable42,'ns=2;i=12'),true).
clause1(hasNodeId(uAVariable42,'ns=2;i=18'),true).
clause1(hasDataType(uAVariable42,'String'),true).
clause1(hasBrowseName(uAVariable42,'length'),true).
clause1(type(uAVariable42,uAVariable),true).
clause1(hasString(value22,'{74d0c8ef-ab53-462a-8225-306ed22dc0f3}'),true).
clause1(type(value22,value),true).
clause1(hasValue(references92,'Optional'),true).
clause1(hasValue(references92,'ns=2;i=18'),true).
clause1(hasValue(references92,'PropertyType'),true).
clause1(type(references92,references),true).
clause1(type(namespaceUris12,namespaceUris),true).
clause1(hasValue(references32,'ns=1;i=5001'),true).
clause1(hasValue(references32,'ns=2;i=45'),true).
clause1(hasValue(references32,'ns=2;i=44'),true).
clause1(hasValue(references32,'ns=2;i=43'),true).
clause1(hasValue(references32,'ns=2;i=42'),true).
clause1(hasValue(references32,'ns=1;i=1002'),true).
clause1(hasValue(references32,'ns=2;i=41'),true).
clause1(type(references32,references),true).
clause1(hasValue(uAVariable92,value92),true).
clause1(hasReferences(uAVariable92,references132),true).
clause1(hasDisplayName(uAVariable92,'BaseRoleClassLib'),true).
clause1(parentNodeId(uAVariable92,'ns=2;i=40'),true).
clause1(hasNodeId(uAVariable92,'ns=2;i=43'),true).
clause1(hasDataType(uAVariable92,'String'),true).
clause1(hasBrowseName(uAVariable92,'BaseRoleClassLib'),true).
clause1(type(uAVariable92,uAVariable),true).

