clause1(hasRoleRequirements(internalElement71,roleRequirements61),true).
clause1(hasExternalInterface(internalElement71,externalInterface61),true).
clause1(hasAttribute(internalElement71,attribute61),true).
clause1(hasAttributeName(internalElement71,'Conveyor6'),true).
clause1(identifier(internalElement71,'6ace6117-c5ac-46c1-9536-d43d9c2a3191'),true).
clause1(type(internalElement71,internalElement),true).
clause1(refBaseRoleClassPath(roleRequirements71,'BaseRoleClassLib@AutomationMLBaseRoleClassLib/AutomationMLBaseRole/Resource'),true).
clause1(type(roleRequirements71,roleRequirements),true).
clause1(hasAttributeValue(attribute81,'19200611'),true).
clause1(hasAttributeName(attribute81,'eClassClassificationClass'),true).
clause1(type(attribute81,attribute),true).
clause1(hasInternalElement(internalElement11,internalElement71),true).
clause1(identifier(internalElement11,'acf9f51b-3fbd-4f30-891d-f8daca50ed17'),true).
clause1(type(internalElement11,internalElement),true).
clause1(hasAttributeName(internalElement11,'Connection'),true).
clause1(hasInternalElement(internalElement11,internalElement21),true).
clause1(hasInternalElement(internalElement11,internalElement41),true).
clause1(hasInternalElement(internalElement11,internalElement51),true).
clause1(hasInternalElement(internalElement11,internalElement31),true).
clause1(hasRoleRequirements(internalElement11,roleRequirements71),true).
clause1(hasInternalElement(internalElement11,internalElement61),true).
clause1(hasInternalElement(instanceHierarchy11,internalElement11),true).
clause1(hasAttributeName(instanceHierarchy11,'ConveyorSystem'),true).
clause1(type(instanceHierarchy11,instanceHierarchy),true).
clause1(refBaseRoleClassPath(roleRequirements11,'BaseInterfaceClassLib@AutomationMLBaseRoleClassLib/AutomationMLBaseRole/Port'),true).
clause1(type(roleRequirements11,roleRequirements),true).
clause1(hasRoleClass(roleClassLib11,roleClass11),true).
clause1(hasVersion(roleClassLib11,'1.0'),true).
clause1(hasAttributeName(roleClassLib11,'IndustryMicroComputer'),true).
clause1(type(roleClassLib11,roleClassLib),true).
clause1(hasRoleClassLib(cAEXFile11,roleClassLib11),true).
clause1(hasInstanceHierarchy(cAEXFile11,instanceHierarchy11),true).
clause1(hasAdditionalInfomation(cAEXFile11,additionalInformation21),true).
clause1(hasAdditionalInfomation(cAEXFile11,additionalInformation11),true).
clause1(hasSchemaVersion(cAEXFile11,'2.15'),true).
clause1(hasFileName(cAEXFile11,'seed.aml'),true).
clause1(type(cAEXFile11,cAEXFile),true).
clause1(hasRefSemantic(attribute21,refSemantic21),true).
clause1(hasAttributeValue(attribute21,'2'),true).
clause1(hasAttributeName(attribute21,' Max.load capacity'),true).
clause1(hasDataType(attribute21,'xs:double'),true).
clause1(type(attribute21,attribute),true).
clause1(hasCorrespondingAttributePath(refSemantic51,'ECLASS:0173-1#07-CAA016#001'),true).
clause1(type(refSemantic51,refSemantic),true).
clause1(refBaseClassPath(externalInterface21,'BaseInterfaceClassLib@AutomationMLInterfaceClassLib/AutomationMLBaseInterface/PortConnector'),true).
clause1(hasAttributeName(externalInterface21,'ConnectionPoint'),true).
clause1(identifier(externalInterface21,'c50f79eb-6634-4c7e-a32f-54bdef05cace'),true).
clause1(type(externalInterface21,externalInterface),true).
clause1(hasRoleRequirements(internalElement61,roleRequirements51),true).
clause1(hasExternalInterface(internalElement61,externalInterface51),true).
clause1(hasAttribute(internalElement61,attribute51),true).
clause1(hasAttributeName(internalElement61,'Conveyor5'),true).
clause1(identifier(internalElement61,'6493b542-8aac-41c0-bb6e-eef0d2621ae0'),true).
clause1(type(internalElement61,internalElement),true).
clause1(refBaseRoleClassPath(roleRequirements61,'IndustryMicroComputer/BASIC_19-20-06-11 Connection technology (Industry microcomputer)'),true).
clause1(type(roleRequirements61,roleRequirements),true).
clause1(hasWriterID(additionalInformation21,'AutomationML e.V.'),true).
clause1(hasWriterRelease(additionalInformation21,'1.0'),true).
clause1(hasWriterVendorURL(additionalInformation21,'www.AutomationML.org'),true).
clause1(hasWriterName(additionalInformation21,'AutomationML e.V.'),true).
clause1(type(additionalInformation21,additionalInformation),true).
clause1(hasWriterProjectTitle(additionalInformation21,'AutomationML Tutorial Examples'),true).
clause1(hasLastWritingDateTime(additionalInformation21,'2012-03-27 '),true).
clause1(hasWriterVersion(additionalInformation21,'1.0'),true).
clause1(hasWriterProjectID(additionalInformation21,'AutomationML Tutorial Examples '),true).
clause1(hasWriterVendor(additionalInformation21,'AutomationML e.V.'),true).
clause1(hasAttributeValue(attribute71,'9.0'),true).
clause1(hasAttributeName(attribute71,'eClassVersion'),true).
clause1(type(attribute71,attribute),true).
clause1(hasRefSemantic(attribute11,refSemantic11),true).
clause1(hasAttributeValue(attribute11,'1.5'),true).
clause1(hasAttributeName(attribute11,'maxConveyingSpeed'),true).
clause1(hasDataType(attribute11,'xs:double'),true).
clause1(type(attribute11,attribute),true).
clause1(hasCorrespondingAttributePath(refSemantic41,'ECLASS:0173-1#02-AAI721#002'),true).
clause1(type(refSemantic41,refSemantic),true).
clause1(refBaseClassPath(externalInterface11,'BaseInterfaceClassLib@AutomationMLInterfaceClassLib/AutomationMLBaseInterface/PortConnector'),true).
clause1(hasAttributeName(externalInterface11,'ConnectionPoint'),true).
clause1(identifier(externalInterface11,'51e272d6-0252-4ebd-b865-2ca7a202a68e'),true).
clause1(type(externalInterface11,externalInterface),true).
clause1(hasRoleRequirements(internalElement51,roleRequirements41),true).
clause1(hasExternalInterface(internalElement51,externalInterface41),true).
clause1(hasAttribute(internalElement51,attribute41),true).
clause1(hasAttributeName(internalElement51,'Conveyor4'),true).
clause1(identifier(internalElement51,'819f4954-892a-4a46-9091-b6f75ddd1332'),true).
clause1(type(internalElement51,internalElement),true).
clause1(refBaseRoleClassPath(roleRequirements51,'BaseInterfaceClassLib@AutomationMLBaseRoleClassLib/AutomationMLBaseRole/Port'),true).
clause1(type(roleRequirements51,roleRequirements),true).
clause1(hasAutomationMLVersion(additionalInformation11,'2.0'),true).
clause1(type(additionalInformation11,additionalInformation),true).
clause1(hasRefSemantic(attribute61,refSemantic61),true).
clause1(hasAttributeName(attribute61,'paperType'),true).
clause1(hasDataType(attribute61,'xs:string'),true).
clause1(type(attribute61,attribute),true).
clause1(refBaseClassPath(externalInterface61,'BaseInterfaceClassLib@AutomationMLInterfaceClassLib/AutomationMLBaseInterface/PortConnector'),true).
clause1(hasAttributeName(externalInterface61,'ConnectionPoint'),true).
clause1(identifier(externalInterface61,'f445e123-5a9e-4fac-ad1e-15623fe2a09b'),true).
clause1(type(externalInterface61,externalInterface),true).
clause1(hasCorrespondingAttributePath(refSemantic31,'ECLASS:0173-1#02-BAH608#004'),true).
clause1(type(refSemantic31,refSemantic),true).
clause1(hasRoleRequirements(internalElement41,roleRequirements31),true).
clause1(hasExternalInterface(internalElement41,externalInterface31),true).
clause1(hasAttribute(internalElement41,attribute31),true).
clause1(hasAttributeName(internalElement41,'Conveyor3'),true).
clause1(identifier(internalElement41,'23e7138b-f28f-4f45-8c0b-ee7e0de7c08f'),true).
clause1(type(internalElement41,internalElement),true).
clause1(refBaseRoleClassPath(roleRequirements41,'BaseInterfaceClassLib@AutomationMLBaseRoleClassLib/AutomationMLBaseRole/Port'),true).
clause1(type(roleRequirements41,roleRequirements),true).
clause1(hasRefSemantic(attribute51,refSemantic51),true).
clause1(hasAttributeName(attribute51,'allowsPaper'),true).
clause1(hasDataType(attribute51,'xs:string'),true).
clause1(type(attribute51,attribute),true).
clause1(refBaseClassPath(externalInterface51,'BaseInterfaceClassLib@AutomationMLInterfaceClassLib/AutomationMLBaseInterface/PortConnector'),true).
clause1(hasAttributeName(externalInterface51,'ConnectionPoint'),true).
clause1(identifier(externalInterface51,'9fc18023-1fa1-40ca-821d-7c5a67d391ce'),true).
clause1(type(externalInterface51,externalInterface),true).
clause1(hasCorrespondingAttributePath(refSemantic21,'ECLASS:0173-1#02-BAF316#002'),true).
clause1(type(refSemantic21,refSemantic),true).
clause1(hasAttribute(roleClass11,attribute91),true).
clause1(hasAttribute(roleClass11,attribute81),true).
clause1(hasAttribute(roleClass11,attribute71),true).
clause1(hasAttributeName(roleClass11,'BASIC_19-20-06-11 Connection technology (Industry microcomputer)'),true).
clause1(type(roleClass11,roleClass),true).
clause1(hasRoleRequirements(internalElement31,roleRequirements21),true).
clause1(hasExternalInterface(internalElement31,externalInterface21),true).
clause1(hasAttribute(internalElement31,attribute21),true).
clause1(hasAttributeName(internalElement31,'Conveyor2'),true).
clause1(identifier(internalElement31,'11b59bf6-44f6-4650-939f-d8e2551912a7'),true).
clause1(type(internalElement31,internalElement),true).
clause1(refBaseRoleClassPath(roleRequirements31,'BaseInterfaceClassLib@AutomationMLBaseRoleClassLib/AutomationMLBaseRole/Port'),true).
clause1(type(roleRequirements31,roleRequirements),true).
clause1(hasRefSemantic(attribute41,refSemantic41),true).
clause1(hasAttributeValue(attribute41,'35.0'),true).
clause1(hasAttributeName(attribute41,'maxTransportationWeight'),true).
clause1(hasDataType(attribute41,'xs:double'),true).
clause1(type(attribute41,attribute),true).
clause1(refBaseClassPath(externalInterface41,'BaseInterfaceClassLib@AutomationMLInterfaceClassLib/AutomationMLBaseInterface/PortConnector'),true).
clause1(hasAttributeName(externalInterface41,'ConnectionPoint'),true).
clause1(identifier(externalInterface41,'c45eca55-521a-492e-b094-472124d1ae65'),true).
clause1(type(externalInterface41,externalInterface),true).
clause1(hasCorrespondingAttributePath(refSemantic11,'ECLASS:0173-1#02-BAF685#003'),true).
clause1(type(refSemantic11,refSemantic),true).
clause1(hasAttributeValue(attribute91,'0173-1---BASIC_1_1#11-AFX038#001'),true).
clause1(hasAttributeName(attribute91,'eClassIRDI'),true).
clause1(type(attribute91,attribute),true).
clause1(hasRoleRequirements(internalElement21,roleRequirements11),true).
clause1(hasExternalInterface(internalElement21,externalInterface11),true).
clause1(hasAttribute(internalElement21,attribute11),true).
clause1(hasAttributeName(internalElement21,'Conveyor1'),true).
clause1(identifier(internalElement21,'45e20f8e-7351-4af9-bdfd-3c019674de55'),true).
clause1(type(internalElement21,internalElement),true).
clause1(refBaseRoleClassPath(roleRequirements21,'BaseInterfaceClassLib@AutomationMLBaseRoleClassLib/AutomationMLBaseRole/Port'),true).
clause1(type(roleRequirements21,roleRequirements),true).
clause1(hasRefSemantic(attribute31,refSemantic31),true).
clause1(hasAttributeValue(attribute31,'1.5'),true).
clause1(hasAttributeName(attribute31,'Min. speed of the drive'),true).
clause1(hasDataType(attribute31,'xs:double'),true).
clause1(type(attribute31,attribute),true).
clause1(hasCorrespondingAttributePath(refSemantic61,'ECLASS:0173-1#02-BAF818#002'),true).
clause1(type(refSemantic61,refSemantic),true).
clause1(refBaseClassPath(externalInterface31,'BaseInterfaceClassLib@AutomationMLInterfaceClassLib/AutomationMLBaseInterface/PortConnector'),true).
clause1(hasAttributeName(externalInterface31,'ConnectionPoint'),true).
clause1(identifier(externalInterface31,'b0e2d6a0-2d8b-44c8-921b-bf4b43de906e'),true).
clause1(type(externalInterface31,externalInterface),true).
clause1(hasRoleClassLib(cAEXFile12,roleClassLib12),true).
clause1(hasInstanceHierarchy(cAEXFile12,instanceHierarchy12),true).
clause1(hasAdditionalInfomation(cAEXFile12,additionalInformation22),true).
clause1(hasAdditionalInfomation(cAEXFile12,additionalInformation12),true).
clause1(hasSchemaVersion(cAEXFile12,'2.15'),true).
clause1(hasFileName(cAEXFile12,'seed.aml'),true).
clause1(type(cAEXFile12,cAEXFile),true).
clause1(hasRefSemantic(attribute42,refSemantic42),true).
clause1(hasAttributeName(attribute42,'paperType'),true).
clause1(hasDataType(attribute42,'xs:string'),true).
clause1(type(attribute42,attribute),true).
clause1(refBaseRoleClassPath(roleRequirements12,'BaseInterfaceClassLib@AutomationMLBaseRoleClassLib/AutomationMLBaseRole/Port'),true).
clause1(type(roleRequirements12,roleRequirements),true).
clause1(hasRoleRequirements(internalElement22,roleRequirements12),true).
clause1(hasExternalInterface(internalElement22,externalInterface12),true).
clause1(hasAttribute(internalElement22,attribute12),true).
clause1(hasAttributeName(internalElement22,'Conveyor1'),true).
clause1(identifier(internalElement22,'45e20f8e-7351-4af9-bdfd-3c019674de55'),true).
clause1(type(internalElement22,internalElement),true).
clause1(hasCorrespondingAttributePath(refSemantic32,'ECLASS:0173-1#02-AAI721#002'),true).
clause1(type(refSemantic32,refSemantic),true).
clause1(refBaseClassPath(externalInterface42,'BaseInterfaceClassLib@AutomationMLInterfaceClassLib/AutomationMLBaseInterface/PortConnector'),true).
clause1(hasAttributeName(externalInterface42,'ConnectionPoint'),true).
clause1(identifier(externalInterface42,'f445e123-5a9e-4fac-ad1e-15623fe2a09b'),true).
clause1(type(externalInterface42,externalInterface),true).
clause1(hasRefSemantic(attribute32,refSemantic32),true).
clause1(hasAttributeValue(attribute32,'35.0'),true).
clause1(hasAttributeName(attribute32,'maxTransportationWeight'),true).
clause1(hasDataType(attribute32,'xs:double'),true).
clause1(type(attribute32,attribute),true).
clause1(hasRoleRequirements(internalElement12,roleRequirements52),true).
clause1(hasInternalElement(internalElement12,internalElement52),true).
clause1(hasInternalElement(internalElement12,internalElement42),true).
clause1(hasInternalElement(internalElement12,internalElement32),true).
clause1(hasInternalElement(internalElement12,internalElement22),true).
clause1(hasAttributeName(internalElement12,'Connection'),true).
clause1(identifier(internalElement12,'acf9f51b-3fbd-4f30-891d-f8daca50ed17'),true).
clause1(type(internalElement12,internalElement),true).
clause1(hasCorrespondingAttributePath(refSemantic22,'ECLASS:0173-1#02-BAF316#002'),true).
clause1(type(refSemantic22,refSemantic),true).
clause1(refBaseClassPath(externalInterface32,'BaseInterfaceClassLib@AutomationMLInterfaceClassLib/AutomationMLBaseInterface/PortConnector'),true).
clause1(hasAttributeName(externalInterface32,'ConnectionPoint'),true).
clause1(identifier(externalInterface32,'c45eca55-521a-492e-b094-472124d1ae65'),true).
clause1(type(externalInterface32,externalInterface),true).
clause1(hasRefSemantic(attribute22,refSemantic22),true).
clause1(hasAttributeValue(attribute22,'2'),true).
clause1(hasAttributeName(attribute22,' Max.load capacity'),true).
clause1(hasDataType(attribute22,'xs:double'),true).
clause1(type(attribute22,attribute),true).
clause1(refBaseRoleClassPath(roleRequirements52,'BaseRoleClassLib@AutomationMLBaseRoleClassLib/AutomationMLBaseRole/Resource'),true).
clause1(type(roleRequirements52,roleRequirements),true).
clause1(hasCorrespondingAttributePath(refSemantic12,'ECLASS:0173-1#02-BAF685#003'),true).
clause1(type(refSemantic12,refSemantic),true).
clause1(refBaseClassPath(externalInterface22,'BaseInterfaceClassLib@AutomationMLInterfaceClassLib/AutomationMLBaseInterface/PortConnector'),true).
clause1(hasAttributeName(externalInterface22,'ConnectionPoint'),true).
clause1(identifier(externalInterface22,'c50f79eb-6634-4c7e-a32f-54bdef05cace'),true).
clause1(type(externalInterface22,externalInterface),true).
clause1(hasInternalElement(instanceHierarchy12,internalElement12),true).
clause1(hasAttributeName(instanceHierarchy12,'ConveyorSystem'),true).
clause1(type(instanceHierarchy12,instanceHierarchy),true).
clause1(hasAttributeValue(attribute72,'0173-1---BASIC_1_1#11-AFX038#001'),true).
clause1(hasAttributeName(attribute72,'eClassIRDI'),true).
clause1(type(attribute72,attribute),true).
clause1(hasRefSemantic(attribute12,refSemantic12),true).
clause1(hasAttributeValue(attribute12,'1.5'),true).
clause1(hasAttributeName(attribute12,'maxConveyingSpeed'),true).
clause1(hasDataType(attribute12,'xs:double'),true).
clause1(type(attribute12,attribute),true).
clause1(refBaseRoleClassPath(roleRequirements42,'IndustryMicroComputer/BASIC_19-20-06-11 Connection technology (Industry microcomputer)'),true).
clause1(type(roleRequirements42,roleRequirements),true).
clause1(hasRoleRequirements(internalElement52,roleRequirements42),true).
clause1(hasExternalInterface(internalElement52,externalInterface42),true).
clause1(hasAttribute(internalElement52,attribute42),true).
clause1(hasAttributeName(internalElement52,'Conveyor6'),true).
clause1(identifier(internalElement52,'6ace6117-c5ac-46c1-9536-d43d9c2a3191'),true).
clause1(type(internalElement52,internalElement),true).
clause1(refBaseClassPath(externalInterface12,'BaseInterfaceClassLib@AutomationMLInterfaceClassLib/AutomationMLBaseInterface/PortConnector'),true).
clause1(hasAttributeName(externalInterface12,'ConnectionPoint'),true).
clause1(identifier(externalInterface12,'51e272d6-0252-4ebd-b865-2ca7a202a68e'),true).
clause1(type(externalInterface12,externalInterface),true).
clause1(hasWriterID(additionalInformation22,'AutomationML e.V.'),true).
clause1(hasWriterRelease(additionalInformation22,'1.0'),true).
clause1(hasWriterVendorURL(additionalInformation22,'www.AutomationML.org'),true).
clause1(hasWriterName(additionalInformation22,'AutomationML e.V.'),true).
clause1(type(additionalInformation22,additionalInformation),true).
clause1(hasWriterProjectTitle(additionalInformation22,'AutomationML Tutorial Examples'),true).
clause1(hasLastWritingDateTime(additionalInformation22,'2012-03-27 '),true).
clause1(hasWriterVersion(additionalInformation22,'1.0'),true).
clause1(hasWriterProjectID(additionalInformation22,'AutomationML Tutorial Examples '),true).
clause1(hasWriterVendor(additionalInformation22,'AutomationML e.V.'),true).
clause1(hasAttributeValue(attribute62,'19200611'),true).
clause1(hasAttributeName(attribute62,'eClassClassificationClass'),true).
clause1(type(attribute62,attribute),true).
clause1(refBaseRoleClassPath(roleRequirements32,'BaseInterfaceClassLib@AutomationMLBaseRoleClassLib/AutomationMLBaseRole/Port'),true).
clause1(type(roleRequirements32,roleRequirements),true).
clause1(hasAttribute(roleClass12,attribute72),true).
clause1(hasAttribute(roleClass12,attribute62),true).
clause1(hasAttribute(roleClass12,attribute52),true).
clause1(hasAttributeName(roleClass12,'BASIC_19-20-06-11 Connection technology (Industry microcomputer)'),true).
clause1(type(roleClass12,roleClass),true).
clause1(hasRoleRequirements(internalElement42,roleRequirements32),true).
clause1(hasExternalInterface(internalElement42,externalInterface32),true).
clause1(hasAttribute(internalElement42,attribute32),true).
clause1(hasAttributeName(internalElement42,'Conveyor4'),true).
clause1(identifier(internalElement42,'819f4954-892a-4a46-9091-b6f75ddd1332'),true).
clause1(type(internalElement42,internalElement),true).
clause1(hasAutomationMLVersion(additionalInformation12,'2.0'),true).
clause1(type(additionalInformation12,additionalInformation),true).
clause1(hasAttributeValue(attribute52,'9.0'),true).
clause1(hasAttributeName(attribute52,'eClassVersion'),true).
clause1(type(attribute52,attribute),true).
clause1(refBaseRoleClassPath(roleRequirements22,'BaseInterfaceClassLib@AutomationMLBaseRoleClassLib/AutomationMLBaseRole/Port'),true).
clause1(type(roleRequirements22,roleRequirements),true).
clause1(hasRoleRequirements(internalElement32,roleRequirements22),true).
clause1(hasExternalInterface(internalElement32,externalInterface22),true).
clause1(hasAttribute(internalElement32,attribute22),true).
clause1(hasAttributeName(internalElement32,'Conveyor2'),true).
clause1(identifier(internalElement32,'11b59bf6-44f6-4650-939f-d8e2551912a7'),true).
clause1(type(internalElement32,internalElement),true).
clause1(hasRoleClass(roleClassLib12,roleClass12),true).
clause1(hasVersion(roleClassLib12,'1.0'),true).
clause1(hasAttributeName(roleClassLib12,'IndustryMicroComputer'),true).
clause1(type(roleClassLib12,roleClassLib),true).
clause1(hasCorrespondingAttributePath(refSemantic42,'ECLASS:0173-1#02-BAF818#002'),true).
clause1(type(refSemantic42,refSemantic),true).

