clause1(hasSupportedRoleClass(systemUnitClass31,supportedRoleClass31),true).
clause1(hasAttributeName(systemUnitClass31,'Fence'),true).
clause1(type(systemUnitClass31,systemUnitClass),true).
clause1(hasSystemUnitClassLib(cAEXFile11,systemUnitClassLib31),true).
clause1(hasSystemUnitClassLib(cAEXFile11,systemUnitClassLib21),true).
clause1(hasSystemUnitClassLib(cAEXFile11,systemUnitClassLib11),true).
clause1(hasAdditionalInfomation(cAEXFile11,additionalInformation21),true).
clause1(hasAdditionalInfomation(cAEXFile11,additionalInformation11),true).
clause1(hasSchemaVersion(cAEXFile11,'2.15'),true).
clause1(hasFileName(cAEXFile11,'seed-Bidirectional-0.aml'),true).
clause1(type(cAEXFile11,cAEXFile),true).
clause1(refBaseRoleClassPath(roleRequirements11,'MappingRoleClassLib/SystemUnitClassMapping'),true).
clause1(type(roleRequirements11,roleRequirements),true).
clause1(hasRoleRequirements(internalElement21,roleRequirements21),true).
clause1(hasAttribute(internalElement21,attribute21),true).
clause1(refBaseSystemUnitPath(internalElement21,'MappingSystemUnitClassLib/SystemUnitClassMappingObject'),true).
clause1(hasAttributeName(internalElement21,'ActiveObjetcMappingObject'),true).
clause1(identifier(internalElement21,'{9be13bdb-13f6-42c5-9be3-db3142b385af}'),true).
clause1(type(internalElement21,internalElement),true).
clause1(refRoleClassPath(supportedRoleClass61,'AutomationMLMIRoleClassLib/ManufacturingEquipment/Fence'),true).
clause1(type(supportedRoleClass61,supportedRoleClass),true).
clause1(hasSupportedRoleClass(systemUnitClass21,supportedRoleClass21),true).
clause1(hasAttributeName(systemUnitClass21,'Tool'),true).
clause1(type(systemUnitClass21,systemUnitClass),true).
clause1(hasInternalElement(systemUnitClass81,internalElement31),true).
clause1(hasAttributeName(systemUnitClass81,'FenceMapping'),true).
clause1(type(systemUnitClass81,systemUnitClass),true).
clause1(hasAttributeValue(attribute31,'SystemB/PassiveObject'),true).
clause1(hasAttributeName(attribute31,'MappedSystemUnitClassPathReference'),true).
clause1(type(attribute31,attribute),true).
clause1(hasRoleRequirements(internalElement11,roleRequirements11),true).
clause1(hasAttribute(internalElement11,attribute11),true).
clause1(refBaseSystemUnitPath(internalElement11,'MappingSystemUnitClassLib/SystemUnitClassMappingObject'),true).
clause1(hasAttributeName(internalElement11,'ActiveObjectMappingObject'),true).
clause1(identifier(internalElement11,'{8301bf6f-3034-455d-95cf-44c128b8baeb}'),true).
clause1(type(internalElement11,internalElement),true).
clause1(refRoleClassPath(supportedRoleClass51,'AutomationMLMIRoleClassLib/ManufacturingEquipment/Robot'),true).
clause1(type(supportedRoleClass51,supportedRoleClass),true).
clause1(hasSupportedRoleClass(systemUnitClass11,supportedRoleClass11),true).
clause1(hasAttributeName(systemUnitClass11,'Robot'),true).
clause1(type(systemUnitClass11,systemUnitClass),true).
clause1(hasInternalElement(systemUnitClass71,internalElement21),true).
clause1(hasAttributeName(systemUnitClass71,'ToolMapping'),true).
clause1(type(systemUnitClass71,systemUnitClass),true).
clause1(hasAttributeValue(attribute21,'SystemB/ActiveObject'),true).
clause1(hasAttributeName(attribute21,'MappedSystemUnitClassPathReference'),true).
clause1(type(attribute21,attribute),true).
clause1(refRoleClassPath(supportedRoleClass41,'AutomationMLMIRoleClassLib/ManufacturingEquipment/Tool'),true).
clause1(type(supportedRoleClass41,supportedRoleClass),true).
clause1(hasInternalElement(systemUnitClass61,internalElement11),true).
clause1(hasAttributeName(systemUnitClass61,'RobotMapping'),true).
clause1(type(systemUnitClass61,systemUnitClass),true).
clause1(hasAttributeValue(attribute11,'SystemB/ActiveObject'),true).
clause1(hasAttributeName(attribute11,'MappedSystemUnitClassPathReference'),true).
clause1(type(attribute11,attribute),true).
clause1(refRoleClassPath(supportedRoleClass31,'AutomationMLMIRoleClassLib/ManufacturingEquipment/Fence'),true).
clause1(type(supportedRoleClass31,supportedRoleClass),true).
clause1(hasLastWritingDateTime(additionalInformation21,'2012-02-20 '),true).
clause1(hasWriterID(additionalInformation21,'AutomationML e.V.'),true).
clause1(hasWriterRelease(additionalInformation21,'1.0'),true).
clause1(hasWriterVendorURL(additionalInformation21,'www.AutomationML.org'),true).
clause1(hasWriterName(additionalInformation21,'AutomationML e.V.'),true).
clause1(type(additionalInformation21,additionalInformation),true).
clause1(hasWriterProjectTitle(additionalInformation21,'AutomationML Tutorial Examples'),true).
clause1(hasWriterVersion(additionalInformation21,'1.0'),true).
clause1(hasWriterProjectID(additionalInformation21,'AutomationML Tutorial Examples '),true).
clause1(hasWriterVendor(additionalInformation21,'AutomationML e.V.'),true).
clause1(hasSupportedRoleClass(systemUnitClass51,supportedRoleClass61),true).
clause1(hasAttributeName(systemUnitClass51,'PassiveObject'),true).
clause1(type(systemUnitClass51,systemUnitClass),true).
clause1(hasSystemUnitClass(systemUnitClassLib31,systemUnitClass81),true).
clause1(hasSystemUnitClass(systemUnitClassLib31,systemUnitClass71),true).
clause1(hasSystemUnitClass(systemUnitClassLib31,systemUnitClass61),true).
clause1(hasAttributeName(systemUnitClassLib31,'SystemAMapping'),true).
clause1(type(systemUnitClassLib31,systemUnitClassLib),true).
clause1(refBaseRoleClassPath(roleRequirements31,'MappingRoleClassLib/SystemUnitClassMapping'),true).
clause1(type(roleRequirements31,roleRequirements),true).
clause1(refRoleClassPath(supportedRoleClass21,'AutomationMLMIRoleClassLib/ManufacturingEquipment/Tool'),true).
clause1(type(supportedRoleClass21,supportedRoleClass),true).
clause1(hasAutomationMLVersion(additionalInformation11,'2.0'),true).
clause1(type(additionalInformation11,additionalInformation),true).
clause1(hasSupportedRoleClass(systemUnitClass41,supportedRoleClass51),true).
clause1(hasSupportedRoleClass(systemUnitClass41,supportedRoleClass41),true).
clause1(hasAttributeName(systemUnitClass41,'ActiveObject'),true).
clause1(type(systemUnitClass41,systemUnitClass),true).
clause1(hasSystemUnitClass(systemUnitClassLib21,systemUnitClass51),true).
clause1(hasSystemUnitClass(systemUnitClassLib21,systemUnitClass41),true).
clause1(hasAttributeName(systemUnitClassLib21,'SystemB'),true).
clause1(type(systemUnitClassLib21,systemUnitClassLib),true).
clause1(refBaseRoleClassPath(roleRequirements21,'MappingRoleClassLib/SystemUnitClassMapping'),true).
clause1(type(roleRequirements21,roleRequirements),true).
clause1(hasRoleRequirements(internalElement31,roleRequirements31),true).
clause1(hasAttribute(internalElement31,attribute31),true).
clause1(refBaseSystemUnitPath(internalElement31,'MappingSystemUnitClassLib/SystemUnitClassMappingObject'),true).
clause1(hasAttributeName(internalElement31,'PassiveObjectMappingObject'),true).
clause1(identifier(internalElement31,'{1c833706-f02f-4bef-9781-5829b673b76a}'),true).
clause1(type(internalElement31,internalElement),true).
clause1(refRoleClassPath(supportedRoleClass11,'AutomationMLMIRoleClassLib/ManufacturingEquipment/Robot'),true).
clause1(type(supportedRoleClass11,supportedRoleClass),true).
clause1(hasSystemUnitClass(systemUnitClassLib11,systemUnitClass31),true).
clause1(hasSystemUnitClass(systemUnitClassLib11,systemUnitClass21),true).
clause1(hasSystemUnitClass(systemUnitClassLib11,systemUnitClass11),true).
clause1(hasAttributeName(systemUnitClassLib11,'SystemA'),true).
clause1(type(systemUnitClassLib11,systemUnitClassLib),true).
clause1(hasSupportedRoleClass(systemUnitClass32,supportedRoleClass32),true).
clause1(hasAttributeName(systemUnitClass32,'Fence'),true).
clause1(type(systemUnitClass32,systemUnitClass),true).
clause1(hasSystemUnitClassLib(cAEXFile12,systemUnitClassLib32),true).
clause1(hasSystemUnitClassLib(cAEXFile12,systemUnitClassLib22),true).
clause1(hasSystemUnitClassLib(cAEXFile12,systemUnitClassLib12),true).
clause1(hasAdditionalInfomation(cAEXFile12,additionalInformation22),true).
clause1(hasAdditionalInfomation(cAEXFile12,additionalInformation12),true).
clause1(hasSchemaVersion(cAEXFile12,'2.15'),true).
clause1(hasFileName(cAEXFile12,'seed-Bidirectional-1.aml'),true).
clause1(type(cAEXFile12,cAEXFile),true).
clause1(refBaseRoleClassPath(roleRequirements12,'MappingRoleClassLib/SystemUnitClassMapping'),true).
clause1(type(roleRequirements12,roleRequirements),true).
clause1(hasRoleRequirements(internalElement22,roleRequirements22),true).
clause1(hasAttribute(internalElement22,attribute22),true).
clause1(refBaseSystemUnitPath(internalElement22,'MappingSystemUnitClassLib/SystemUnitClassMappingObject'),true).
clause1(hasAttributeName(internalElement22,'ToolMappingObject'),true).
clause1(identifier(internalElement22,'{8301bf6f-3034-455d-95cf-44c128b8baeb}'),true).
clause1(type(internalElement22,internalElement),true).
clause1(hasSupportedRoleClass(systemUnitClass22,supportedRoleClass22),true).
clause1(hasAttributeName(systemUnitClass22,'Tool'),true).
clause1(type(systemUnitClass22,systemUnitClass),true).
clause1(hasInternalElement(systemUnitClass82,internalElement32),true).
clause1(hasAttributeName(systemUnitClass82,'PassiveObjectMapping'),true).
clause1(type(systemUnitClass82,systemUnitClass),true).
clause1(hasAttributeValue(attribute32,'SystemA/Fence'),true).
clause1(hasAttributeName(attribute32,'MappedSystemUnitClassPathReference'),true).
clause1(type(attribute32,attribute),true).
clause1(hasRoleRequirements(internalElement12,roleRequirements12),true).
clause1(hasAttribute(internalElement12,attribute12),true).
clause1(refBaseSystemUnitPath(internalElement12,'MappingSystemUnitClassLib/SystemUnitClassMappingObject'),true).
clause1(hasAttributeName(internalElement12,'RobotMappingObject'),true).
clause1(identifier(internalElement12,'{8301bf6f-3034-455d-95cf-44c128b8baeb}'),true).
clause1(type(internalElement12,internalElement),true).
clause1(refRoleClassPath(supportedRoleClass52,'AutomationMLMIRoleClassLib/ManufacturingEquipment/Fence'),true).
clause1(type(supportedRoleClass52,supportedRoleClass),true).
clause1(hasSupportedRoleClass(systemUnitClass12,supportedRoleClass12),true).
clause1(hasAttributeName(systemUnitClass12,'Robot'),true).
clause1(type(systemUnitClass12,systemUnitClass),true).
clause1(hasInternalElement(systemUnitClass72,internalElement22),true).
clause1(hasAttributeName(systemUnitClass72,'ActiveObjectMapping'),true).
clause1(type(systemUnitClass72,systemUnitClass),true).
clause1(hasAttributeValue(attribute22,'SystemA/Tool'),true).
clause1(hasAttributeName(attribute22,'MappedSystemUnitClassPathReference'),true).
clause1(type(attribute22,attribute),true).
clause1(refRoleClassPath(supportedRoleClass42,'AutomationMLMIRoleClassLib/ManufacturingEquipment/Robot'),true).
clause1(type(supportedRoleClass42,supportedRoleClass),true).
clause1(hasInternalElement(systemUnitClass62,internalElement12),true).
clause1(hasAttributeName(systemUnitClass62,'ActiveObjectMapping'),true).
clause1(type(systemUnitClass62,systemUnitClass),true).
clause1(hasAttributeValue(attribute12,'SystemA/Robot'),true).
clause1(hasAttributeName(attribute12,'MappedSystemUnitClassPathReference'),true).
clause1(type(attribute12,attribute),true).
clause1(refRoleClassPath(supportedRoleClass32,'AutomationMLMIRoleClassLib/ManufacturingEquipment/Fence'),true).
clause1(type(supportedRoleClass32,supportedRoleClass),true).
clause1(hasLastWritingDateTime(additionalInformation22,'2012-02-20 '),true).
clause1(hasWriterID(additionalInformation22,'AutomationML e.V.'),true).
clause1(hasWriterRelease(additionalInformation22,'1.0'),true).
clause1(hasWriterVendorURL(additionalInformation22,'www.AutomationML.org'),true).
clause1(hasWriterName(additionalInformation22,'AutomationML e.V.'),true).
clause1(type(additionalInformation22,additionalInformation),true).
clause1(hasWriterProjectTitle(additionalInformation22,'AutomationML Tutorial Examples'),true).
clause1(hasWriterVersion(additionalInformation22,'1.0'),true).
clause1(hasWriterProjectID(additionalInformation22,'AutomationML Tutorial Examples '),true).
clause1(hasWriterVendor(additionalInformation22,'AutomationML e.V.'),true).
clause1(hasSupportedRoleClass(systemUnitClass52,supportedRoleClass52),true).
clause1(hasAttributeName(systemUnitClass52,'PassiveObject'),true).
clause1(type(systemUnitClass52,systemUnitClass),true).
clause1(hasSystemUnitClass(systemUnitClassLib32,systemUnitClass82),true).
clause1(hasSystemUnitClass(systemUnitClassLib32,systemUnitClass72),true).
clause1(hasSystemUnitClass(systemUnitClassLib32,systemUnitClass62),true).
clause1(hasAttributeName(systemUnitClassLib32,'SystemBMapping'),true).
clause1(type(systemUnitClassLib32,systemUnitClassLib),true).
clause1(refBaseRoleClassPath(roleRequirements32,'MappingRoleClassLib/SystemUnitClassMapping'),true).
clause1(type(roleRequirements32,roleRequirements),true).
clause1(refRoleClassPath(supportedRoleClass22,'AutomationMLMIRoleClassLib/ManufacturingEquipment/Tool'),true).
clause1(type(supportedRoleClass22,supportedRoleClass),true).
clause1(hasAutomationMLVersion(additionalInformation12,'2.0'),true).
clause1(type(additionalInformation12,additionalInformation),true).
clause1(hasSupportedRoleClass(systemUnitClass42,supportedRoleClass42),true).
clause1(hasAttributeName(systemUnitClass42,'ActiveObject'),true).
clause1(type(systemUnitClass42,systemUnitClass),true).
clause1(hasSystemUnitClass(systemUnitClassLib22,systemUnitClass52),true).
clause1(hasSystemUnitClass(systemUnitClassLib22,systemUnitClass42),true).
clause1(hasAttributeName(systemUnitClassLib22,'SystemB'),true).
clause1(type(systemUnitClassLib22,systemUnitClassLib),true).
clause1(refBaseRoleClassPath(roleRequirements22,'MappingRoleClassLib/SystemUnitClassMapping'),true).
clause1(type(roleRequirements22,roleRequirements),true).
clause1(hasRoleRequirements(internalElement32,roleRequirements32),true).
clause1(hasAttribute(internalElement32,attribute32),true).
clause1(refBaseSystemUnitPath(internalElement32,'MappingSystemUnitClassLib/SystemUnitClassMappingObject'),true).
clause1(hasAttributeName(internalElement32,'FenceMappingObject'),true).
clause1(identifier(internalElement32,'{1c833706-f02f-4bef-9781-5829b673b76a}'),true).
clause1(type(internalElement32,internalElement),true).
clause1(refRoleClassPath(supportedRoleClass12,'AutomationMLMIRoleClassLib/ManufacturingEquipment/Robot'),true).
clause1(type(supportedRoleClass12,supportedRoleClass),true).
clause1(hasSystemUnitClass(systemUnitClassLib12,systemUnitClass32),true).
clause1(hasSystemUnitClass(systemUnitClassLib12,systemUnitClass22),true).
clause1(hasSystemUnitClass(systemUnitClassLib12,systemUnitClass12),true).
clause1(hasAttributeName(systemUnitClassLib12,'SystemA'),true).
clause1(type(systemUnitClassLib12,systemUnitClassLib),true).

