clause1(hasAttributeValue(attribute101,'36120401'),true).
clause1(hasAttributeName(attribute101,'eClassClassificationClass'),true).
clause1(type(attribute101,attribute),true).
clause1(hasRefSemantic(attribute81,refSemantic21),true).
clause1(hasAttributeValue(attribute81,'35.0'),true).
clause1(hasAttributeName(attribute81,'maxTransportationWeight'),true).
clause1(type(attribute81,attribute),true).
clause1(hasRoleRequirements(internalElement11,roleRequirements31),true).
clause1(hasInternalElement(internalElement11,internalElement31),true).
clause1(hasInternalElement(internalElement11,internalElement21),true).
clause1(hasAttributeName(internalElement11,'Connection'),true).
clause1(identifier(internalElement11,'acf9f51b-3fbd-4f30-891d-f8daca50ed17'),true).
clause1(type(internalElement11,internalElement),true).
clause1(hasRoleClass(roleClassLib11,roleClass11),true).
clause1(hasVersion(roleClassLib11,'1.0'),true).
clause1(hasAttributeName(roleClassLib11,'Industry microcomputer'),true).
clause1(type(roleClassLib11,roleClassLib),true).
clause1(refBaseRoleClassPath(roleRequirements11,'Industry microcomputer/BASIC_19-20-06-11 Connection technology (Industry microcomputer)'),true).
clause1(type(roleRequirements11,roleRequirements),true).
clause1(hasSystemUnitClass(systemUnitClassLib21,systemUnitClass21),true).
clause1(hasVersion(systemUnitClassLib21,'1.0'),true).
clause1(hasAttributeName(systemUnitClassLib21,'Conveyor'),true).
clause1(type(systemUnitClassLib21,systemUnitClassLib),true).
clause1(hasInternalElement(systemUnitClass21,internalElement61),true).
clause1(hasInternalElement(systemUnitClass21,internalElement51),true).
clause1(hasInternalElement(systemUnitClass21,internalElement41),true).
clause1(hasAttribute(systemUnitClass21,attribute111),true).
clause1(hasAttribute(systemUnitClass21,attribute101),true).
clause1(hasAttribute(systemUnitClass21,attribute91),true).
clause1(hasAttributeName(systemUnitClass21,'BASIC_36-12-04-01 Conveyor'),true).
clause1(type(systemUnitClass21,systemUnitClass),true).
clause1(hasRoleClassLib(cAEXFile11,roleClassLib11),true).
clause1(hasExternalReference(cAEXFile11,externalReference11),true).
clause1(hasAdditionalInfomation(cAEXFile11,additionalInformation21),true).
clause1(type(cAEXFile11,cAEXFile),true).
clause1(hasAdditionalInfomation(cAEXFile11,additionalInformation11),true).
clause1(hasSchemaVersion(cAEXFile11,'2.15'),true).
clause1(hasSystemUnitClassLib(cAEXFile11,systemUnitClassLib11),true).
clause1(hasExternalReference(cAEXFile11,externalReference21),true).
clause1(hasSystemUnitClassLib(cAEXFile11,systemUnitClassLib21),true).
clause1(hasFileName(cAEXFile11,'seed-0.aml'),true).
clause1(hasAttributeValue(attribute21,'19200611'),true).
clause1(hasAttributeName(attribute21,'eClassClassificationClass'),true).
clause1(type(attribute21,attribute),true).
clause1(hasCorrespondingAttributePath(refSemantic51,'ECLASS:0173-1#02-BAH608#004'),true).
clause1(type(refSemantic51,refSemantic),true).
clause1(refBaseClassPath(externalInterface21,'BaseInterfaceClassLib@AutomationMLInterfaceClassLib/AutomationMLBaseInterface/PortConnector'),true).
clause1(hasAttributeName(externalInterface21,'ConnectionPoint'),true).
clause1(identifier(externalInterface21,'c45eca55-521a-492e-b094-472124d1ae65'),true).
clause1(type(externalInterface21,externalInterface),true).
clause1(hasAttribute(internalElement61,attribute141),true).
clause1(hasAttributeName(internalElement61,'Conveyor3'),true).
clause1(identifier(internalElement61,'23e7138b-f28f-4f45-8c0b-ee7e0de7c08f'),true).
clause1(type(internalElement61,internalElement),true).
clause1(hasWriterProjectTitle(additionalInformation21,'AutomationML Tutorial Examples'),true).
clause1(hasWriterRelease(additionalInformation21,'1.0'),true).
clause1(hasWriterVendorURL(additionalInformation21,'www.AutomationML.org'),true).
clause1(hasWriterID(additionalInformation21,'AutomationML e.V.'),true).
clause1(type(additionalInformation21,additionalInformation),true).
clause1(hasRefSemantic(attribute71,refSemantic11),true).
clause1(hasAttributeValue(attribute71,'Carbon'),true).
clause1(hasAttributeName(attribute71,'paperType'),true).
clause1(type(attribute71,attribute),true).
clause1(hasInternalElement(systemUnitClass11,internalElement11),true).
clause1(hasAttribute(systemUnitClass11,attribute61),true).
clause1(hasAttribute(systemUnitClass11,attribute51),true).
clause1(hasAttribute(systemUnitClass11,attribute41),true).
clause1(hasAttributeName(systemUnitClass11,'BASIC_36-12-04-02 Conveyor'),true).
clause1(type(systemUnitClass11,systemUnitClass),true).
clause1(hasSystemUnitClass(systemUnitClassLib11,systemUnitClass11),true).
clause1(hasVersion(systemUnitClassLib11,'1.0'),true).
clause1(hasAttributeName(systemUnitClassLib11,'Conveyor-1'),true).
clause1(type(systemUnitClassLib11,systemUnitClassLib),true).
clause1(hasAttributeValue(attribute11,'9.0'),true).
clause1(hasAttributeName(attribute11,'eClassVersion'),true).
clause1(type(attribute11,attribute),true).
clause1(hasCorrespondingAttributePath(refSemantic41,'ECLASS:0173-1#02-BAF316#002'),true).
clause1(type(refSemantic41,refSemantic),true).
clause1(refBaseClassPath(externalInterface11,'BaseInterfaceClassLib@AutomationMLInterfaceClassLib/AutomationMLBaseInterface/PortConnector'),true).
clause1(hasAttributeName(externalInterface11,'ConnectionPoint'),true).
clause1(identifier(externalInterface11,'51e272d6-0252-4ebd-b865-2ca7a202a68e'),true).
clause1(type(externalInterface11,externalInterface),true).
clause1(hasRefSemantic(attribute141,refSemantic51),true).
clause1(hasAttributeValue(attribute141,'1.5'),true).
clause1(hasAttributeName(attribute141,'Min. speed of the drive'),true).
clause1(type(attribute141,attribute),true).
clause1(hasAttribute(internalElement51,attribute131),true).
clause1(hasAttributeName(internalElement51,'Conveyor2'),true).
clause1(identifier(internalElement51,'11b59bf6-44f6-4650-939f-d8e2551912a7'),true).
clause1(type(internalElement51,internalElement),true).
clause1(hasAutomationMLVersion(additionalInformation11,'2.0'),true).
clause1(type(additionalInformation11,additionalInformation),true).
clause1(hasAttributeValue(attribute61,'0173-1---BASIC_1_1#01-AKL503#010'),true).
clause1(hasAttributeName(attribute61,'eClassIRDI'),true).
clause1(type(attribute61,attribute),true).
clause1(hasCorrespondingAttributePath(refSemantic31,'ECLASS:0173-1#02-BAF685#003'),true).
clause1(type(refSemantic31,refSemantic),true).
clause1(hasRefSemantic(attribute131,refSemantic41),true).
clause1(hasAttributeValue(attribute131,'2'),true).
clause1(hasAttributeName(attribute131,' Max.load capacity'),true).
clause1(type(attribute131,attribute),true).
clause1(hasAttribute(internalElement41,attribute121),true).
clause1(hasAttributeName(internalElement41,'Conveyor1'),true).
clause1(identifier(internalElement41,'45e20f8e-7351-4af9-bdfd-3c019674de55'),true).
clause1(type(internalElement41,internalElement),true).
clause1(hasAttributeValue(attribute51,'36120401'),true).
clause1(hasAttributeName(attribute51,'eClassClassificationClass'),true).
clause1(type(attribute51,attribute),true).
clause1(hasCorrespondingAttributePath(refSemantic21,'ECLASS:0173-1#02-AAI721#002'),true).
clause1(type(refSemantic21,refSemantic),true).
clause1(refBaseClassPath(externalReference21,'Libs/InterfaceClass Libraries/AutomationMLInterfaceClassLib.aml'),true).
clause1(externalReferenceAlias(externalReference21,'BaseInterfaceClassLib'),true).
clause1(type(externalReference21,externalReference),true).
clause1(hasRefSemantic(attribute121,refSemantic31),true).
clause1(hasAttributeValue(attribute121,'10'),true).
clause1(hasAttributeName(attribute121,'maxConveyingSpeed'),true).
clause1(type(attribute121,attribute),true).
clause1(hasAttribute(roleClass11,attribute31),true).
clause1(hasAttribute(roleClass11,attribute21),true).
clause1(hasAttribute(roleClass11,attribute11),true).
clause1(hasAttributeName(roleClass11,'BASIC_19-20-06-11 Connection technology (Industry microcomputer)'),true).
clause1(type(roleClass11,roleClass),true).
clause1(hasRoleRequirements(internalElement31,roleRequirements21),true).
clause1(hasExternalInterface(internalElement31,externalInterface21),true).
clause1(hasAttribute(internalElement31,attribute81),true).
clause1(hasAttributeName(internalElement31,'Conveyor-2'),true).
clause1(identifier(internalElement31,'819f4954-892a-4a46-9091-b6f75ddd1332'),true).
clause1(type(internalElement31,internalElement),true).
clause1(refBaseRoleClassPath(roleRequirements31,'Industry microcomputer/BASIC_19-20-06-11 Connection technology (Industry microcomputer)'),true).
clause1(type(roleRequirements31,roleRequirements),true).
clause1(hasAttributeValue(attribute41,'9.0'),true).
clause1(hasAttributeName(attribute41,'eClassVersion'),true).
clause1(type(attribute41,attribute),true).
clause1(hasCorrespondingAttributePath(refSemantic11,'ECLASS:0173-1#02-BAF818#002'),true).
clause1(type(refSemantic11,refSemantic),true).
clause1(refBaseClassPath(externalReference11,'Libs/RoleClass Libraries/AutomationMLBaseRoleClassLib.aml'),true).
clause1(externalReferenceAlias(externalReference11,'BaseRoleClassLib'),true).
clause1(type(externalReference11,externalReference),true).
clause1(hasAttributeValue(attribute111,'0173-1---BASIC_1_1#01-AKL503#010'),true).
clause1(hasAttributeName(attribute111,'eClassIRDI'),true).
clause1(type(attribute111,attribute),true).
clause1(hasAttributeValue(attribute91,'9.0'),true).
clause1(hasAttributeName(attribute91,'eClassVersion'),true).
clause1(type(attribute91,attribute),true).
clause1(hasRoleRequirements(internalElement21,roleRequirements11),true).
clause1(hasExternalInterface(internalElement21,externalInterface11),true).
clause1(hasAttribute(internalElement21,attribute71),true).
clause1(hasAttributeName(internalElement21,'Conveyor-1'),true).
clause1(identifier(internalElement21,'45e21f8e-7351-4af9-bdfd-3c019674de55'),true).
clause1(type(internalElement21,internalElement),true).
clause1(refBaseRoleClassPath(roleRequirements21,'BaseInterfaceClassLib@AutomationMLBaseRoleClassLib/AutomationMLBaseRole/Port'),true).
clause1(type(roleRequirements21,roleRequirements),true).
clause1(hasAttributeValue(attribute31,'0173-1---BASIC_1_1#11-AFX038#001'),true).
clause1(hasAttributeName(attribute31,'eClassIRDI'),true).
clause1(type(attribute31,attribute),true).
clause1(hasRoleClassLib(cAEXFile12,roleClassLib12),true).
clause1(hasExternalReference(cAEXFile12,externalReference12),true).
clause1(hasAdditionalInfomation(cAEXFile12,additionalInformation22),true).
clause1(type(cAEXFile12,cAEXFile),true).
clause1(hasAdditionalInfomation(cAEXFile12,additionalInformation12),true).
clause1(hasSchemaVersion(cAEXFile12,'2.15'),true).
clause1(hasSystemUnitClassLib(cAEXFile12,systemUnitClassLib12),true).
clause1(hasExternalReference(cAEXFile12,externalReference22),true).
clause1(hasSystemUnitClassLib(cAEXFile12,systemUnitClassLib22),true).
clause1(hasFileName(cAEXFile12,'seed-Granularity-1.aml'),true).
clause1(hasSystemUnitClass(systemUnitClassLib12,systemUnitClass12),true).
clause1(hasVersion(systemUnitClassLib12,'1.0'),true).
clause1(hasAttributeName(systemUnitClassLib12,'Conveyor-1'),true).
clause1(type(systemUnitClassLib12,systemUnitClassLib),true).
clause1(refBaseRoleClassPath(roleRequirements12,'Industry microcomputer/BASIC_19-20-06-11 Connection technology (Industry microcomputer)'),true).
clause1(type(roleRequirements12,roleRequirements),true).
clause1(hasAttributeValue(attribute42,'9.0'),true).
clause1(hasAttributeName(attribute42,'eClassVersion'),true).
clause1(type(attribute42,attribute),true).
clause1(hasRoleRequirements(internalElement22,roleRequirements32),true).
clause1(hasRoleRequirements(internalElement22,roleRequirements22),true).
clause1(hasExternalInterface(internalElement22,externalInterface22),true).
clause1(hasAttribute(internalElement22,attribute82),true).
clause1(hasAttributeName(internalElement22,'Conveyor-2'),true).
clause1(identifier(internalElement22,'819f4954-892a-4a46-9091-b6f75ddd1332'),true).
clause1(type(internalElement22,internalElement),true).
clause1(refBaseClassPath(externalReference12,'Libs/RoleClass Libraries/AutomationMLBaseRoleClassLib.aml'),true).
clause1(externalReferenceAlias(externalReference12,'BaseRoleClassLib'),true).
clause1(type(externalReference12,externalReference),true).
clause1(hasCorrespondingAttributePath(refSemantic32,'ECLASS:0173-1#02-BAF316#002'),true).
clause1(type(refSemantic32,refSemantic),true).
clause1(hasInternalElement(systemUnitClass22,internalElement32),true).
clause1(hasAttribute(systemUnitClass22,attribute112),true).
clause1(hasAttribute(systemUnitClass22,attribute102),true).
clause1(hasAttribute(systemUnitClass22,attribute92),true).
clause1(hasAttributeName(systemUnitClass22,'BASIC_36-12-04-01 Conveyor'),true).
clause1(type(systemUnitClass22,systemUnitClass),true).
clause1(hasAttributeValue(attribute32,'0173-1---BASIC_1_1#11-AFX038#001'),true).
clause1(hasAttributeName(attribute32,'eClassIRDI'),true).
clause1(type(attribute32,attribute),true).
clause1(hasAttributeValue(attribute92,'9.0'),true).
clause1(hasAttributeName(attribute92,'eClassVersion'),true).
clause1(type(attribute92,attribute),true).
clause1(hasRoleRequirements(internalElement12,roleRequirements12),true).
clause1(hasExternalInterface(internalElement12,externalInterface12),true).
clause1(hasAttribute(internalElement12,attribute72),true).
clause1(hasAttributeName(internalElement12,'Conveyor-1'),true).
clause1(identifier(internalElement12,'45e21f8e-7351-4af9-bdfd-3c019674de55'),true).
clause1(type(internalElement12,internalElement),true).
clause1(hasCorrespondingAttributePath(refSemantic22,'ECLASS:0173-1#02-AAI721#002'),true).
clause1(type(refSemantic22,refSemantic),true).
clause1(hasInternalElement(systemUnitClass12,internalElement22),true).
clause1(hasInternalElement(systemUnitClass12,internalElement12),true).
clause1(hasAttribute(systemUnitClass12,attribute62),true).
clause1(hasAttribute(systemUnitClass12,attribute52),true).
clause1(hasAttribute(systemUnitClass12,attribute42),true).
clause1(hasAttributeName(systemUnitClass12,'BASIC_36-12-04-02 Conveyor'),true).
clause1(type(systemUnitClass12,systemUnitClass),true).
clause1(hasAttributeValue(attribute22,'19200611'),true).
clause1(hasAttributeName(attribute22,'eClassClassificationClass'),true).
clause1(type(attribute22,attribute),true).
clause1(hasRefSemantic(attribute82,refSemantic22),true).
clause1(hasAttributeValue(attribute82,'35.0'),true).
clause1(hasAttributeName(attribute82,'maxTransportationWeight'),true).
clause1(type(attribute82,attribute),true).
clause1(hasRefSemantic(attribute122,refSemantic32),true).
clause1(hasAttributeValue(attribute122,'2'),true).
clause1(hasAttributeName(attribute122,' Max.load capacity'),true).
clause1(type(attribute122,attribute),true).
clause1(hasCorrespondingAttributePath(refSemantic12,'ECLASS:0173-1#02-BAF818#002'),true).
clause1(type(refSemantic12,refSemantic),true).
clause1(refBaseClassPath(externalInterface22,'BaseInterfaceClassLib@AutomationMLInterfaceClassLib/AutomationMLBaseInterface/PortConnector'),true).
clause1(hasAttributeName(externalInterface22,'ConnectionPoint'),true).
clause1(identifier(externalInterface22,'c45eca55-521a-492e-b094-472124d1ae65'),true).
clause1(type(externalInterface22,externalInterface),true).
clause1(hasAttributeValue(attribute12,'9.0'),true).
clause1(hasAttributeName(attribute12,'eClassVersion'),true).
clause1(type(attribute12,attribute),true).
clause1(hasRefSemantic(attribute72,refSemantic12),true).
clause1(hasAttributeValue(attribute72,'Carbon'),true).
clause1(hasAttributeName(attribute72,'paperType'),true).
clause1(type(attribute72,attribute),true).
clause1(hasAttributeValue(attribute112,'0173-1---BASIC_1_1#01-AKL503#010'),true).
clause1(hasAttributeName(attribute112,'eClassIRDI'),true).
clause1(type(attribute112,attribute),true).
clause1(refBaseClassPath(externalInterface12,'BaseInterfaceClassLib@AutomationMLInterfaceClassLib/AutomationMLBaseInterface/PortConnector'),true).
clause1(hasAttributeName(externalInterface12,'ConnectionPoint'),true).
clause1(identifier(externalInterface12,'51e272d6-0252-4ebd-b865-2ca7a202a68e'),true).
clause1(type(externalInterface12,externalInterface),true).
clause1(hasWriterProjectTitle(additionalInformation22,'AutomationML Tutorial Examples'),true).
clause1(hasWriterVendorURL(additionalInformation22,'www.AutomationML.org'),true).
clause1(type(additionalInformation22,additionalInformation),true).
clause1(refBaseRoleClassPath(roleRequirements32,'Industry microcomputer/BASIC_19-20-06-11 Connection technology (Industry microcomputer)'),true).
clause1(type(roleRequirements32,roleRequirements),true).
clause1(hasAttributeValue(attribute62,'0173-1---BASIC_1_1#01-AKL503#010'),true).
clause1(hasAttributeName(attribute62,'eClassIRDI'),true).
clause1(type(attribute62,attribute),true).
clause1(hasAttributeValue(attribute102,'36120401'),true).
clause1(hasAttributeName(attribute102,'eClassClassificationClass'),true).
clause1(type(attribute102,attribute),true).
clause1(hasAttribute(roleClass12,attribute32),true).
clause1(hasAttribute(roleClass12,attribute22),true).
clause1(hasAttribute(roleClass12,attribute12),true).
clause1(hasAttributeName(roleClass12,'BASIC_19-20-06-11 Connection technology (Industry microcomputer)'),true).
clause1(type(roleClass12,roleClass),true).
clause1(hasAutomationMLVersion(additionalInformation12,'2.0'),true).
clause1(type(additionalInformation12,additionalInformation),true).
clause1(hasSystemUnitClass(systemUnitClassLib22,systemUnitClass22),true).
clause1(hasVersion(systemUnitClassLib22,'1.0'),true).
clause1(hasAttributeName(systemUnitClassLib22,'Conveyor'),true).
clause1(type(systemUnitClassLib22,systemUnitClassLib),true).
clause1(refBaseRoleClassPath(roleRequirements22,'BaseInterfaceClassLib@AutomationMLBaseRoleClassLib/AutomationMLBaseRole/Port'),true).
clause1(type(roleRequirements22,roleRequirements),true).
clause1(hasAttributeValue(attribute52,'36120401'),true).
clause1(hasAttributeName(attribute52,'eClassClassificationClass'),true).
clause1(type(attribute52,attribute),true).
clause1(hasAttribute(internalElement32,attribute122),true).
clause1(hasAttributeName(internalElement32,'Conveyor2'),true).
clause1(identifier(internalElement32,'11b59bf6-44f6-4650-939f-d8e2551912a7'),true).
clause1(type(internalElement32,internalElement),true).
clause1(refBaseClassPath(externalReference22,'Libs/InterfaceClass Libraries/AutomationMLInterfaceClassLib.aml'),true).
clause1(externalReferenceAlias(externalReference22,'BaseInterfaceClassLib'),true).
clause1(type(externalReference22,externalReference),true).
clause1(hasRoleClass(roleClassLib12,roleClass12),true).
clause1(hasVersion(roleClassLib12,'1.0'),true).
clause1(hasAttributeName(roleClassLib12,'Industry microcomputer'),true).
clause1(type(roleClassLib12,roleClassLib),true).

