clause1(hasRoleClassLib(cAEXFile11,roleClassLib11),true).
clause1(hasInstanceHierarchy(cAEXFile11,instanceHierarchy11),true).
clause1(hasAdditionalInfomation(cAEXFile11,additionalInformation21),true).
clause1(hasAdditionalInfomation(cAEXFile11,additionalInformation11),true).
clause1(hasSchemaVersion(cAEXFile11,'2.15'),true).
clause1(hasFileName(cAEXFile11,'seed.aml'),true).
clause1(type(cAEXFile11,cAEXFile),true).
clause1(refBaseRoleClassPath(roleRequirements11,'BaseInterfaceClassLib@AutomationMLBaseRoleClassLib/AutomationMLBaseRole/Port'),true).
clause1(type(roleRequirements11,roleRequirements),true).
clause1(hasRefSemantic(attribute41,refSemantic41),true).
clause1(type(attribute41,attribute),true).
clause1(refBaseRoleClassPath(roleRequirements71,'BaseRoleClassLib@AutomationMLBaseRoleClassLib/AutomationMLBaseRole/Resource'),true).
clause1(type(roleRequirements71,roleRequirements),true).
clause1(hasCorrespondingAttributePath(refSemantic31,'ECLASS:0173-1#02-BAH608#004'),true).
clause1(type(refSemantic31,refSemantic),true).
clause1(type(externalInterface41,externalInterface),true).
clause1(hasAttributeValue(attribute91,'0173-1---BASIC_1_1#11-AFX038#001'),true).
clause1(hasAttributeName(attribute91,'eClassIRDI'),true).
clause1(type(attribute91,attribute),true).
clause1(hasRefSemantic(attribute31,refSemantic31),true).
clause1(type(attribute31,attribute),true).
clause1(refBaseRoleClassPath(roleRequirements61,'IndustryMicroComputer/BASIC_19-20-06-11 Connection technology (Industry microcomputer)'),true).
clause1(type(roleRequirements61,roleRequirements),true).
clause1(hasAttribute(internalElement11,attribute61),true).
clause1(hasRoleRequirements(internalElement11,roleRequirements61),true).
clause1(hasExternalInterface(internalElement11,externalInterface21),true).
clause1(hasExternalInterface(internalElement11,externalInterface51),true).
clause1(identifier(internalElement11,'acf9f51b-3fbd-4f30-891d-f8daca50ed17'),true).
clause1(type(internalElement11,internalElement),true).
clause1(hasRoleRequirements(internalElement11,roleRequirements21),true).
clause1(hasExternalInterface(internalElement11,externalInterface41),true).
clause1(hasAttribute(internalElement11,attribute31),true).
clause1(hasAttributeName(internalElement11,'Connection'),true).
clause1(hasRoleRequirements(internalElement11,roleRequirements31),true).
clause1(hasAttribute(internalElement11,attribute41),true).
clause1(hasAttribute(internalElement11,attribute11),true).
clause1(hasRoleRequirements(internalElement11,roleRequirements41),true).
clause1(hasAttribute(internalElement11,attribute21),true).
clause1(hasRoleRequirements(internalElement11,roleRequirements11),true).
clause1(hasExternalInterface(internalElement11,externalInterface61),true).
clause1(hasRoleRequirements(internalElement11,roleRequirements71),true).
clause1(hasExternalInterface(internalElement11,externalInterface11),true).
clause1(hasExternalInterface(internalElement11,externalInterface31),true).
clause1(hasAttribute(internalElement11,attribute51),true).
clause1(hasRoleRequirements(internalElement11,roleRequirements51),true).
clause1(hasCorrespondingAttributePath(refSemantic21,'ECLASS:0173-1#02-BAF316#002'),true).
clause1(type(refSemantic21,refSemantic),true).
clause1(type(externalInterface31,externalInterface),true).
clause1(hasAttributeValue(attribute81,'19200611'),true).
clause1(hasAttributeName(attribute81,'eClassClassificationClass'),true).
clause1(type(attribute81,attribute),true).
clause1(hasRefSemantic(attribute21,refSemantic21),true).
clause1(type(attribute21,attribute),true).
clause1(refBaseRoleClassPath(roleRequirements51,'BaseInterfaceClassLib@AutomationMLBaseRoleClassLib/AutomationMLBaseRole/Port'),true).
clause1(type(roleRequirements51,roleRequirements),true).
clause1(hasCorrespondingAttributePath(refSemantic11,'ECLASS:0173-1#02-BAF685#003'),true).
clause1(type(refSemantic11,refSemantic),true).
clause1(type(externalInterface21,externalInterface),true).
clause1(hasInternalElement(instanceHierarchy11,internalElement11),true).
clause1(hasAttributeName(instanceHierarchy11,'ConveyorSystem'),true).
clause1(type(instanceHierarchy11,instanceHierarchy),true).
clause1(hasAttributeValue(attribute71,'9.0'),true).
clause1(hasAttributeName(attribute71,'eClassVersion'),true).
clause1(type(attribute71,attribute),true).
clause1(hasRefSemantic(attribute11,refSemantic11),true).
clause1(type(attribute11,attribute),true).
clause1(refBaseRoleClassPath(roleRequirements41,'BaseInterfaceClassLib@AutomationMLBaseRoleClassLib/AutomationMLBaseRole/Port'),true).
clause1(type(roleRequirements41,roleRequirements),true).
clause1(hasCorrespondingAttributePath(refSemantic61,'ECLASS:0173-1#02-BAF818#002'),true).
clause1(type(refSemantic61,refSemantic),true).
clause1(type(externalInterface11,externalInterface),true).
clause1(hasWriterID(additionalInformation21,'AutomationML e.V.'),true).
clause1(hasWriterRelease(additionalInformation21,'1.0'),true).
clause1(hasWriterVendorURL(additionalInformation21,'www.AutomationML.org'),true).
clause1(hasWriterName(additionalInformation21,'AutomationML e.V.'),true).
clause1(type(additionalInformation21,additionalInformation),true).
clause1(hasWriterProjectTitle(additionalInformation21,'AutomationML Tutorial Examples'),true).
clause1(hasLastWritingDateTime(additionalInformation21,'2012-03-27 '),true).
clause1(hasWriterVersion(additionalInformation21,'1.0'),true).
clause1(hasWriterProjectID(additionalInformation21,'AutomationML Tutorial Examples '),true).
clause1(hasWriterVendor(additionalInformation21,'AutomationML e.V.'),true).
clause1(hasRefSemantic(attribute61,refSemantic61),true).
clause1(type(attribute61,attribute),true).
clause1(refBaseRoleClassPath(roleRequirements31,'BaseInterfaceClassLib@AutomationMLBaseRoleClassLib/AutomationMLBaseRole/Port'),true).
clause1(type(roleRequirements31,roleRequirements),true).
clause1(hasAttribute(roleClass11,attribute91),true).
clause1(hasAttribute(roleClass11,attribute81),true).
clause1(hasAttribute(roleClass11,attribute71),true).
clause1(hasAttributeName(roleClass11,'BASIC_19-20-06-11 Connection technology (Industry microcomputer)'),true).
clause1(type(roleClass11,roleClass),true).
clause1(hasCorrespondingAttributePath(refSemantic51,'ECLASS:0173-1#07-CAA016#001'),true).
clause1(type(refSemantic51,refSemantic),true).
clause1(type(externalInterface61,externalInterface),true).
clause1(hasAutomationMLVersion(additionalInformation11,'2.0'),true).
clause1(type(additionalInformation11,additionalInformation),true).
clause1(hasRefSemantic(attribute51,refSemantic51),true).
clause1(type(attribute51,attribute),true).
clause1(refBaseRoleClassPath(roleRequirements21,'BaseInterfaceClassLib@AutomationMLBaseRoleClassLib/AutomationMLBaseRole/Port'),true).
clause1(type(roleRequirements21,roleRequirements),true).
clause1(hasRoleClass(roleClassLib11,roleClass11),true).
clause1(hasVersion(roleClassLib11,'1.0'),true).
clause1(hasAttributeName(roleClassLib11,'IndustryMicroComputer'),true).
clause1(type(roleClassLib11,roleClassLib),true).
clause1(hasCorrespondingAttributePath(refSemantic41,'ECLASS:0173-1#02-AAI721#002'),true).
clause1(type(refSemantic41,refSemantic),true).
clause1(type(externalInterface51,externalInterface),true).

clause1(hasRoleClassLib(cAEXFile12,roleClassLib12),true).
clause1(hasInstanceHierarchy(cAEXFile12,instanceHierarchy12),true).
clause1(hasAdditionalInfomation(cAEXFile12,additionalInformation22),true).
clause1(hasAdditionalInfomation(cAEXFile12,additionalInformation12),true).
clause1(hasSchemaVersion(cAEXFile12,'2.15'),true).
clause1(hasFileName(cAEXFile12,'seed.aml'),true).
clause1(type(cAEXFile12,cAEXFile),true).
clause1(refBaseRoleClassPath(roleRequirements12,'BaseInterfaceClassLib@AutomationMLBaseRoleClassLib/AutomationMLBaseRole/Port'),true).
clause1(type(roleRequirements12,roleRequirements),true).
clause1(hasRefSemantic(attribute42,refSemantic42),true).
clause1(type(attribute42,attribute),true).
clause1(hasCorrespondingAttributePath(refSemantic32,'ECLASS:0173-1#02-AAI721#002'),true).
clause1(type(refSemantic32,refSemantic),true).
clause1(type(externalInterface42,externalInterface),true).
clause1(hasRefSemantic(attribute32,refSemantic32),true).
clause1(type(attribute32,attribute),true).
clause1(hasExternalInterface(internalElement12,externalInterface22),true).
clause1(identifier(internalElement12,'acf9f51b-3fbd-4f30-891d-f8daca50ed17'),true).
clause1(type(internalElement12,internalElement),true).
clause1(hasRoleRequirements(internalElement12,roleRequirements22),true).
clause1(hasExternalInterface(internalElement12,externalInterface42),true).
clause1(hasAttribute(internalElement12,attribute32),true).
clause1(hasAttributeName(internalElement12,'Connection'),true).
clause1(hasRoleRequirements(internalElement12,roleRequirements32),true).
clause1(hasAttribute(internalElement12,attribute42),true).
clause1(hasAttribute(internalElement12,attribute12),true).
clause1(hasRoleRequirements(internalElement12,roleRequirements42),true).
clause1(hasAttribute(internalElement12,attribute22),true).
clause1(hasRoleRequirements(internalElement12,roleRequirements12),true).
clause1(hasExternalInterface(internalElement12,externalInterface12),true).
clause1(hasExternalInterface(internalElement12,externalInterface32),true).
clause1(hasRoleRequirements(internalElement12,roleRequirements52),true).
clause1(hasCorrespondingAttributePath(refSemantic22,'ECLASS:0173-1#02-BAF316#002'),true).
clause1(type(refSemantic22,refSemantic),true).
clause1(type(externalInterface32,externalInterface),true).
clause1(hasRefSemantic(attribute22,refSemantic22),true).
clause1(type(attribute22,attribute),true).
clause1(refBaseRoleClassPath(roleRequirements52,'BaseRoleClassLib@AutomationMLBaseRoleClassLib/AutomationMLBaseRole/Resource'),true).
clause1(type(roleRequirements52,roleRequirements),true).
clause1(hasCorrespondingAttributePath(refSemantic12,'ECLASS:0173-1#02-BAF685#003'),true).
clause1(type(refSemantic12,refSemantic),true).
clause1(type(externalInterface22,externalInterface),true).
clause1(hasInternalElement(instanceHierarchy12,internalElement12),true).
clause1(hasAttributeName(instanceHierarchy12,'ConveyorSystem'),true).
clause1(type(instanceHierarchy12,instanceHierarchy),true).
clause1(hasAttributeValue(attribute72,'0173-1---BASIC_1_1#11-AFX038#001'),true).
clause1(hasAttributeName(attribute72,'eClassIRDI'),true).
clause1(type(attribute72,attribute),true).
clause1(hasRefSemantic(attribute12,refSemantic12),true).
clause1(type(attribute12,attribute),true).
clause1(refBaseRoleClassPath(roleRequirements42,'IndustryMicroComputer/BASIC_19-20-06-11 Connection technology (Industry microcomputer)'),true).
clause1(type(roleRequirements42,roleRequirements),true).
clause1(type(externalInterface12,externalInterface),true).
clause1(hasWriterID(additionalInformation22,'AutomationML e.V.'),true).
clause1(hasWriterRelease(additionalInformation22,'1.0'),true).
clause1(hasWriterVendorURL(additionalInformation22,'www.AutomationML.org'),true).
clause1(hasWriterName(additionalInformation22,'AutomationML e.V.'),true).
clause1(type(additionalInformation22,additionalInformation),true).
clause1(hasWriterProjectTitle(additionalInformation22,'AutomationML Tutorial Examples'),true).
clause1(hasLastWritingDateTime(additionalInformation22,'2012-03-27 '),true).
clause1(hasWriterVersion(additionalInformation22,'1.0'),true).
clause1(hasWriterProjectID(additionalInformation22,'AutomationML Tutorial Examples '),true).
clause1(hasWriterVendor(additionalInformation22,'AutomationML e.V.'),true).
clause1(hasAttributeValue(attribute62,'19200611'),true).
clause1(hasAttributeName(attribute62,'eClassClassificationClass'),true).
clause1(type(attribute62,attribute),true).
clause1(refBaseRoleClassPath(roleRequirements32,'BaseInterfaceClassLib@AutomationMLBaseRoleClassLib/AutomationMLBaseRole/Port'),true).
clause1(type(roleRequirements32,roleRequirements),true).
clause1(hasAttribute(roleClass12,attribute72),true).
clause1(hasAttribute(roleClass12,attribute62),true).
clause1(hasAttribute(roleClass12,attribute52),true).
clause1(hasAttributeName(roleClass12,'BASIC_19-20-06-11 Connection technology (Industry microcomputer)'),true).
clause1(type(roleClass12,roleClass),true).
clause1(hasAutomationMLVersion(additionalInformation12,'2.0'),true).
clause1(type(additionalInformation12,additionalInformation),true).
clause1(hasAttributeValue(attribute52,'9.0'),true).
clause1(hasAttributeName(attribute52,'eClassVersion'),true).
clause1(type(attribute52,attribute),true).
clause1(refBaseRoleClassPath(roleRequirements22,'BaseInterfaceClassLib@AutomationMLBaseRoleClassLib/AutomationMLBaseRole/Port'),true).
clause1(type(roleRequirements22,roleRequirements),true).
clause1(hasRoleClass(roleClassLib12,roleClass12),true).
clause1(hasVersion(roleClassLib12,'1.0'),true).
clause1(hasAttributeName(roleClassLib12,'IndustryMicroComputer'),true).
clause1(type(roleClassLib12,roleClassLib),true).
clause1(hasCorrespondingAttributePath(refSemantic42,'ECLASS:0173-1#02-BAF818#002'),true).
clause1(type(refSemantic42,refSemantic),true).

