clause1(hasSystemUnitClass(systemUnitClassLib11,systemUnitClass11),true).
clause1(hasVersion(systemUnitClassLib11,'1.0'),true).
clause1(hasAttributeName(systemUnitClassLib11,'Conveyors'),true).
clause1(type(systemUnitClassLib11,systemUnitClassLib),true).
clause1(hasSystemUnitClassLib(cAEXFile11,systemUnitClassLib11),true).
clause1(hasInstanceHierarchy(cAEXFile11,instanceHierarchy11),true).
clause1(hasExternalReference(cAEXFile11,externalReference21),true).
clause1(hasExternalReference(cAEXFile11,externalReference11),true).
clause1(hasAdditionalInfomation(cAEXFile11,additionalInformation21),true).
clause1(hasAdditionalInfomation(cAEXFile11,additionalInformation11),true).
clause1(hasSchemaVersion(cAEXFile11,'2.15'),true).
clause1(hasFileName(cAEXFile11,'seed-Datatype-0.aml'),true).
clause1(type(cAEXFile11,cAEXFile),true).
clause1(refBaseRoleClassPath(roleRequirements11,'BaseInterfaceClassLib@AutomationMLBaseRoleClassLib/AutomationMLBaseRole/Port'),true).
clause1(type(roleRequirements11,roleRequirements),true).
clause1(hasAttributeValue(attribute41,'36120401'),true).
clause1(hasAttributeName(attribute41,'eClassClassificationClass'),true).
clause1(type(attribute41,attribute),true).
clause1(hasRoleRequirements(internalElement21,roleRequirements51),true).
clause1(hasInternalElement(internalElement21,internalElement61),true).
clause1(hasInternalElement(internalElement21,internalElement51),true).
clause1(hasInternalElement(internalElement21,internalElement41),true).
clause1(hasInternalElement(internalElement21,internalElement31),true).
clause1(hasAttributeName(internalElement21,'Connection'),true).
clause1(identifier(internalElement21,'acf9f51b-3fbd-4f30-891d-f8daca50ed17'),true).
clause1(type(internalElement21,internalElement),true).
clause1(refBaseClassPath(externalReference11,'Libs/RoleClass Libraries/AutomationMLBaseRoleClassLib.aml'),true).
clause1(externalReferenceAlias(externalReference11,'BaseRoleClassLib'),true).
clause1(type(externalReference11,externalReference),true).
clause1(hasCorrespondingAttributePath(refSemantic31,'ECLASS:0173-1#02-BAF685#003'),true).
clause1(type(refSemantic31,refSemantic),true).
clause1(refBaseClassPath(externalInterface41,'BaseInterfaceClassLib@AutomationMLInterfaceClassLib/AutomationMLBaseInterface/PortConnector'),true).
clause1(hasAttributeName(externalInterface41,'ConnectionPoint'),true).
clause1(identifier(externalInterface41,'c45eca55-521a-492e-b094-472124d1ae65'),true).
clause1(type(externalInterface41,externalInterface),true).
clause1(hasAttributeValue(attribute31,'9.0'),true).
clause1(hasAttributeName(attribute31,'eClassVersion'),true).
clause1(type(attribute31,attribute),true).
clause1(hasRefSemantic(attribute91,refSemantic61),true).
clause1(hasAttributeValue(attribute91,'35.0'),true).
clause1(hasAttributeName(attribute91,'maxTransportationWeight'),true).
clause1(type(attribute91,attribute),true).
clause1(hasAttribute(internalElement11,attribute21),true).
clause1(hasAttribute(internalElement11,attribute11),true).
clause1(refBaseSystemUnitPath(internalElement11,'NE150SUCLibrary/PCERequest'),true).
clause1(hasAttributeName(internalElement11,'TIRC'),true).
clause1(identifier(internalElement11,'8a38e7be-bbfc-4a91-a244-1974990c7bc2'),true).
clause1(type(internalElement11,internalElement),true).
clause1(hasCorrespondingAttributePath(refSemantic21,'NE 160 v1.0 Annex 2.1.2'),true).
clause1(type(refSemantic21,refSemantic),true).
clause1(refBaseClassPath(externalInterface31,'BaseInterfaceClassLib@AutomationMLInterfaceClassLib/AutomationMLBaseInterface/PortConnector'),true).
clause1(hasAttributeName(externalInterface31,'ConnectionPoint'),true).
clause1(identifier(externalInterface31,'b0e2d6a0-2d8b-44c8-921b-bf4b43de906e'),true).
clause1(type(externalInterface31,externalInterface),true).
clause1(hasInternalElement(systemUnitClass11,internalElement21),true).
clause1(hasAttribute(systemUnitClass11,attribute51),true).
clause1(hasAttribute(systemUnitClass11,attribute41),true).
clause1(hasAttribute(systemUnitClass11,attribute31),true).
clause1(hasAttributeName(systemUnitClass11,'BASIC_36-12-04-01 Conveyor'),true).
clause1(type(systemUnitClass11,systemUnitClass),true).
clause1(refBaseRoleClassPath(roleRequirements51,'BaseRoleClassLib@AutomationMLBaseRoleClassLib/AutomationMLBaseRole/Resource'),true).
clause1(type(roleRequirements51,roleRequirements),true).
clause1(hasRefSemantic(attribute21,refSemantic21),true).
clause1(hasAttributeValue(attribute21,'2016'),true).
clause1(hasAttributeName(attribute21,'ExportDate'),true).
clause1(hasDataType(attribute21,'xs:datetime'),true).
clause1(type(attribute21,attribute),true).
clause1(hasRefSemantic(attribute81,refSemantic51),true).
clause1(hasAttributeValue(attribute81,'1.5'),true).
clause1(hasAttributeName(attribute81,'Min. speed of the drive'),true).
clause1(type(attribute81,attribute),true).
clause1(hasRoleRequirements(internalElement61,roleRequirements41),true).
clause1(hasExternalInterface(internalElement61,externalInterface41),true).
clause1(hasAttribute(internalElement61,attribute91),true).
clause1(hasAttributeName(internalElement61,'Conveyor4'),true).
clause1(identifier(internalElement61,'819f4954-892a-4a46-9091-b6f75ddd1332'),true).
clause1(type(internalElement61,internalElement),true).
clause1(hasCorrespondingAttributePath(refSemantic11,'NE 150 v1.0 Annex 2.1.2'),true).
clause1(type(refSemantic11,refSemantic),true).
clause1(refBaseClassPath(externalInterface21,'BaseInterfaceClassLib@AutomationMLInterfaceClassLib/AutomationMLBaseInterface/PortConnector'),true).
clause1(hasAttributeName(externalInterface21,'ConnectionPoint'),true).
clause1(identifier(externalInterface21,'c50f79eb-6634-4c7e-a32f-54bdef05cace'),true).
clause1(type(externalInterface21,externalInterface),true).
clause1(hasInternalElement(instanceHierarchy11,internalElement11),true).
clause1(hasAttributeName(instanceHierarchy11,'NE150DemoProject'),true).
clause1(type(instanceHierarchy11,instanceHierarchy),true).
clause1(refBaseRoleClassPath(roleRequirements41,'BaseInterfaceClassLib@AutomationMLBaseRoleClassLib/AutomationMLBaseRole/Port'),true).
clause1(type(roleRequirements41,roleRequirements),true).
clause1(hasRefSemantic(attribute11,refSemantic11),true).
clause1(hasAttributeValue(attribute11,'2014'),true).
clause1(hasAttributeName(attribute11,'ManufactureDate'),true).
clause1(hasDataType(attribute11,'xs:dateTime'),true).
clause1(type(attribute11,attribute),true).
clause1(hasRefSemantic(attribute71,refSemantic41),true).
clause1(hasAttributeValue(attribute71,'2'),true).
clause1(hasAttributeName(attribute71,' Max.load capacity'),true).
clause1(type(attribute71,attribute),true).
clause1(hasRoleRequirements(internalElement51,roleRequirements31),true).
clause1(hasExternalInterface(internalElement51,externalInterface31),true).
clause1(hasAttribute(internalElement51,attribute81),true).
clause1(hasAttributeName(internalElement51,'Conveyor3'),true).
clause1(identifier(internalElement51,'23e7138b-f28f-4f45-8c0b-ee7e0de7c08f'),true).
clause1(type(internalElement51,internalElement),true).
clause1(hasCorrespondingAttributePath(refSemantic61,'ECLASS:0173-1#02-AAI721#002'),true).
clause1(type(refSemantic61,refSemantic),true).
clause1(refBaseClassPath(externalInterface11,'BaseInterfaceClassLib@AutomationMLInterfaceClassLib/AutomationMLBaseInterface/PortConnector'),true).
clause1(hasAttributeName(externalInterface11,'ConnectionPoint'),true).
clause1(identifier(externalInterface11,'51e272d6-0252-4ebd-b865-2ca7a202a68e'),true).
clause1(type(externalInterface11,externalInterface),true).
clause1(hasWriterID(additionalInformation21,'AutomationML e.V.'),true).
clause1(hasWriterRelease(additionalInformation21,'1.0'),true).
clause1(hasWriterProjectID(additionalInformation21,'AutomationML Tutorial Examples
			'),true).
clause1(hasWriterVendorURL(additionalInformation21,'www.AutomationML.org'),true).
clause1(hasLastWritingDateTime(additionalInformation21,'2012-02-20
			'),true).
clause1(hasWriterName(additionalInformation21,'AutomationML e.V.'),true).
clause1(type(additionalInformation21,additionalInformation),true).
clause1(hasWriterProjectTitle(additionalInformation21,'AutomationML Tutorial Examples'),true).
clause1(hasWriterVersion(additionalInformation21,'1.0'),true).
clause1(hasWriterVendor(additionalInformation21,'AutomationML e.V.'),true).
clause1(refBaseRoleClassPath(roleRequirements31,'BaseInterfaceClassLib@AutomationMLBaseRoleClassLib/AutomationMLBaseRole/Port'),true).
clause1(type(roleRequirements31,roleRequirements),true).
clause1(hasRefSemantic(attribute61,refSemantic31),true).
clause1(hasAttributeValue(attribute61,'1.5'),true).
clause1(hasAttributeName(attribute61,'maxConveyingSpeed'),true).
clause1(type(attribute61,attribute),true).
clause1(hasRoleRequirements(internalElement41,roleRequirements21),true).
clause1(hasExternalInterface(internalElement41,externalInterface21),true).
clause1(hasAttribute(internalElement41,attribute71),true).
clause1(hasAttributeName(internalElement41,'Conveyor2'),true).
clause1(identifier(internalElement41,'11b59bf6-44f6-4650-939f-d8e2551912a7'),true).
clause1(type(internalElement41,internalElement),true).
clause1(hasCorrespondingAttributePath(refSemantic51,'ECLASS:0173-1#02-BAH608#004'),true).
clause1(type(refSemantic51,refSemantic),true).
clause1(hasAutomationMLVersion(additionalInformation11,'2.0'),true).
clause1(type(additionalInformation11,additionalInformation),true).
clause1(refBaseRoleClassPath(roleRequirements21,'BaseInterfaceClassLib@AutomationMLBaseRoleClassLib/AutomationMLBaseRole/Port'),true).
clause1(type(roleRequirements21,roleRequirements),true).
clause1(hasAttributeValue(attribute51,'0173-1---BASIC_1_1#01-AKL503#010'),true).
clause1(hasAttributeName(attribute51,'eClassIRDI'),true).
clause1(type(attribute51,attribute),true).
clause1(hasRoleRequirements(internalElement31,roleRequirements11),true).
clause1(hasExternalInterface(internalElement31,externalInterface11),true).
clause1(hasAttribute(internalElement31,attribute61),true).
clause1(hasAttributeName(internalElement31,'Conveyor1'),true).
clause1(identifier(internalElement31,'45e20f8e-7351-4af9-bdfd-3c019674de55'),true).
clause1(type(internalElement31,internalElement),true).
clause1(refBaseClassPath(externalReference21,'Libs/InterfaceClass Libraries/AutomationMLInterfaceClassLib.aml'),true).
clause1(externalReferenceAlias(externalReference21,'BaseInterfaceClassLib'),true).
clause1(type(externalReference21,externalReference),true).
clause1(hasCorrespondingAttributePath(refSemantic41,'ECLASS:0173-1#02-BAF316#002'),true).
clause1(type(refSemantic41,refSemantic),true).
clause1(hasSystemUnitClass(systemUnitClassLib12,systemUnitClass12),true).
clause1(hasVersion(systemUnitClassLib12,'1.0'),true).
clause1(hasAttributeName(systemUnitClassLib12,'Conveyors'),true).
clause1(type(systemUnitClassLib12,systemUnitClassLib),true).
clause1(hasSystemUnitClassLib(cAEXFile12,systemUnitClassLib12),true).
clause1(hasInstanceHierarchy(cAEXFile12,instanceHierarchy12),true).
clause1(hasExternalReference(cAEXFile12,externalReference22),true).
clause1(hasExternalReference(cAEXFile12,externalReference12),true).
clause1(hasAdditionalInfomation(cAEXFile12,additionalInformation22),true).
clause1(hasAdditionalInfomation(cAEXFile12,additionalInformation12),true).
clause1(hasSchemaVersion(cAEXFile12,'2.15'),true).
clause1(hasFileName(cAEXFile12,'seed-Datatype-1.aml'),true).
clause1(type(cAEXFile12,cAEXFile),true).
clause1(refBaseRoleClassPath(roleRequirements12,'BaseInterfaceClassLib@AutomationMLBaseRoleClassLib/AutomationMLBaseRole/Port'),true).
clause1(type(roleRequirements12,roleRequirements),true).
clause1(hasAttributeValue(attribute42,'36120401'),true).
clause1(hasAttributeName(attribute42,'eClassClassificationClass'),true).
clause1(type(attribute42,attribute),true).
clause1(hasRoleRequirements(internalElement22,roleRequirements12),true).
clause1(hasExternalInterface(internalElement22,externalInterface12),true).
clause1(hasAttribute(internalElement22,attribute62),true).
clause1(hasAttributeName(internalElement22,'Conveyor1'),true).
clause1(identifier(internalElement22,'45e20f8e-7351-4af9-bdfd-3c019674de55'),true).
clause1(type(internalElement22,internalElement),true).
clause1(refBaseClassPath(externalReference12,'Libs/RoleClass Libraries/AutomationMLBaseRoleClassLib.aml'),true).
clause1(externalReferenceAlias(externalReference12,'BaseRoleClassLib'),true).
clause1(type(externalReference12,externalReference),true).
clause1(hasCorrespondingAttributePath(refSemantic32,'ECLASS:0173-1#02-BAF685#003'),true).
clause1(type(refSemantic32,refSemantic),true).
clause1(refBaseClassPath(externalInterface42,'BaseInterfaceClassLib@AutomationMLInterfaceClassLib/AutomationMLBaseInterface/PortConnector'),true).
clause1(hasAttributeName(externalInterface42,'ConnectionPoint'),true).
clause1(identifier(externalInterface42,'c45eca55-521a-492e-b094-472124d1ae65'),true).
clause1(type(externalInterface42,externalInterface),true).
clause1(hasAttributeValue(attribute32,'9.0'),true).
clause1(hasAttributeName(attribute32,'eClassVersion'),true).
clause1(type(attribute32,attribute),true).
clause1(hasRefSemantic(attribute92,refSemantic62),true).
clause1(hasAttributeValue(attribute92,'35.0'),true).
clause1(hasAttributeName(attribute92,'maxTransportationWeight'),true).
clause1(type(attribute92,attribute),true).
clause1(hasAttribute(internalElement12,attribute22),true).
clause1(hasAttribute(internalElement12,attribute12),true).
clause1(refBaseSystemUnitPath(internalElement12,'NE150SUCLibrary/PCERequest'),true).
clause1(hasAttributeName(internalElement12,'TIRC'),true).
clause1(identifier(internalElement12,'8a38e7be-bbfc-4a91-a244-1974990c7bc2'),true).
clause1(type(internalElement12,internalElement),true).
clause1(hasCorrespondingAttributePath(refSemantic22,'NE 160 v1.0 Annex 2.1.2'),true).
clause1(type(refSemantic22,refSemantic),true).
clause1(refBaseClassPath(externalInterface32,'BaseInterfaceClassLib@AutomationMLInterfaceClassLib/AutomationMLBaseInterface/PortConnector'),true).
clause1(hasAttributeName(externalInterface32,'ConnectionPoint'),true).
clause1(identifier(externalInterface32,'b0e2d6a0-2d8b-44c8-921b-bf4b43de906e'),true).
clause1(type(externalInterface32,externalInterface),true).
clause1(hasInternalElement(systemUnitClass12,internalElement52),true).
clause1(hasInternalElement(systemUnitClass12,internalElement42),true).
clause1(hasInternalElement(systemUnitClass12,internalElement32),true).
clause1(hasInternalElement(systemUnitClass12,internalElement22),true).
clause1(hasAttribute(systemUnitClass12,attribute52),true).
clause1(hasAttribute(systemUnitClass12,attribute42),true).
clause1(hasAttribute(systemUnitClass12,attribute32),true).
clause1(hasAttributeName(systemUnitClass12,'BASIC_36-12-04-01 Conveyor'),true).
clause1(type(systemUnitClass12,systemUnitClass),true).
clause1(hasRefSemantic(attribute22,refSemantic22),true).
clause1(hasAttributeValue(attribute22,'2016'),true).
clause1(hasAttributeName(attribute22,'ExportDate'),true).
clause1(hasDataType(attribute22,'xs:date'),true).
clause1(type(attribute22,attribute),true).
clause1(hasRefSemantic(attribute82,refSemantic52),true).
clause1(hasAttributeValue(attribute82,'1.5'),true).
clause1(hasAttributeName(attribute82,'Min. speed of the drive'),true).
clause1(type(attribute82,attribute),true).
clause1(hasCorrespondingAttributePath(refSemantic12,'NE 150 v1.0 Annex 2.1.2'),true).
clause1(type(refSemantic12,refSemantic),true).
clause1(refBaseClassPath(externalInterface22,'BaseInterfaceClassLib@AutomationMLInterfaceClassLib/AutomationMLBaseInterface/PortConnector'),true).
clause1(hasAttributeName(externalInterface22,'ConnectionPoint'),true).
clause1(identifier(externalInterface22,'c50f79eb-6634-4c7e-a32f-54bdef05cace'),true).
clause1(type(externalInterface22,externalInterface),true).
clause1(hasInternalElement(instanceHierarchy12,internalElement12),true).
clause1(hasAttributeName(instanceHierarchy12,'NE150DemoProject'),true).
clause1(type(instanceHierarchy12,instanceHierarchy),true).
clause1(refBaseRoleClassPath(roleRequirements42,'BaseInterfaceClassLib@AutomationMLBaseRoleClassLib/AutomationMLBaseRole/Port'),true).
clause1(type(roleRequirements42,roleRequirements),true).
clause1(hasRefSemantic(attribute12,refSemantic12),true).
clause1(hasAttributeValue(attribute12,'2014'),true).
clause1(hasAttributeName(attribute12,'ManufactureDate'),true).
clause1(hasDataType(attribute12,'xs:date'),true).
clause1(type(attribute12,attribute),true).
clause1(hasRefSemantic(attribute72,refSemantic42),true).
clause1(hasAttributeValue(attribute72,'2'),true).
clause1(hasAttributeName(attribute72,' Max.load capacity'),true).
clause1(type(attribute72,attribute),true).
clause1(hasRoleRequirements(internalElement52,roleRequirements42),true).
clause1(hasExternalInterface(internalElement52,externalInterface42),true).
clause1(hasAttribute(internalElement52,attribute92),true).
clause1(hasAttributeName(internalElement52,'Conveyor4'),true).
clause1(identifier(internalElement52,'819f4954-892a-4a46-9091-b6f75ddd1332'),true).
clause1(type(internalElement52,internalElement),true).
clause1(hasCorrespondingAttributePath(refSemantic62,'ECLASS:0173-1#02-AAI721#002'),true).
clause1(type(refSemantic62,refSemantic),true).
clause1(refBaseClassPath(externalInterface12,'BaseInterfaceClassLib@AutomationMLInterfaceClassLib/AutomationMLBaseInterface/PortConnector'),true).
clause1(hasAttributeName(externalInterface12,'ConnectionPoint'),true).
clause1(identifier(externalInterface12,'51e272d6-0252-4ebd-b865-2ca7a202a68e'),true).
clause1(type(externalInterface12,externalInterface),true).
clause1(hasWriterID(additionalInformation22,'AutomationML e.V.'),true).
clause1(hasWriterRelease(additionalInformation22,'1.0'),true).
clause1(hasWriterProjectID(additionalInformation22,'AutomationML Tutorial Examples
			'),true).
clause1(hasWriterVendorURL(additionalInformation22,'www.AutomationML.org'),true).
clause1(hasLastWritingDateTime(additionalInformation22,'2012-02-20
			'),true).
clause1(hasWriterName(additionalInformation22,'AutomationML e.V.'),true).
clause1(type(additionalInformation22,additionalInformation),true).
clause1(hasWriterProjectTitle(additionalInformation22,'AutomationML Tutorial Examples'),true).
clause1(hasWriterVersion(additionalInformation22,'1.0'),true).
clause1(hasWriterVendor(additionalInformation22,'AutomationML e.V.'),true).
clause1(refBaseRoleClassPath(roleRequirements32,'BaseInterfaceClassLib@AutomationMLBaseRoleClassLib/AutomationMLBaseRole/Port'),true).
clause1(type(roleRequirements32,roleRequirements),true).
clause1(hasRefSemantic(attribute62,refSemantic32),true).
clause1(hasAttributeValue(attribute62,'1.5'),true).
clause1(hasAttributeName(attribute62,'maxConveyingSpeed'),true).
clause1(type(attribute62,attribute),true).
clause1(hasRoleRequirements(internalElement42,roleRequirements32),true).
clause1(hasExternalInterface(internalElement42,externalInterface32),true).
clause1(hasAttribute(internalElement42,attribute82),true).
clause1(hasAttributeName(internalElement42,'Conveyor3'),true).
clause1(identifier(internalElement42,'23e7138b-f28f-4f45-8c0b-ee7e0de7c08f'),true).
clause1(type(internalElement42,internalElement),true).
clause1(hasCorrespondingAttributePath(refSemantic52,'ECLASS:0173-1#02-BAH608#004'),true).
clause1(type(refSemantic52,refSemantic),true).
clause1(hasAutomationMLVersion(additionalInformation12,'2.0'),true).
clause1(type(additionalInformation12,additionalInformation),true).
clause1(refBaseRoleClassPath(roleRequirements22,'BaseInterfaceClassLib@AutomationMLBaseRoleClassLib/AutomationMLBaseRole/Port'),true).
clause1(type(roleRequirements22,roleRequirements),true).
clause1(hasAttributeValue(attribute52,'0173-1---BASIC_1_1#01-AKL503#010'),true).
clause1(hasAttributeName(attribute52,'eClassIRDI'),true).
clause1(type(attribute52,attribute),true).
clause1(hasRoleRequirements(internalElement32,roleRequirements22),true).
clause1(hasExternalInterface(internalElement32,externalInterface22),true).
clause1(hasAttribute(internalElement32,attribute72),true).
clause1(hasAttributeName(internalElement32,'Conveyor2'),true).
clause1(identifier(internalElement32,'11b59bf6-44f6-4650-939f-d8e2551912a7'),true).
clause1(type(internalElement32,internalElement),true).
clause1(refBaseClassPath(externalReference22,'Libs/InterfaceClass Libraries/AutomationMLInterfaceClassLib.aml'),true).
clause1(externalReferenceAlias(externalReference22,'BaseInterfaceClassLib'),true).
clause1(type(externalReference22,externalReference),true).
clause1(hasCorrespondingAttributePath(refSemantic42,'ECLASS:0173-1#02-BAF316#002'),true).
clause1(type(refSemantic42,refSemantic),true).

